export type CreatorFeatureParityEntry = {
    featureId: string;
    routeSurface: string;
    creatorPermission: string;
    sourceOfTruth: string;
    statusStates: readonly string[];
    submitUpdateAction: string;
    userFacingConsumer: string;
    adminFacingConsumer: string;
    telemetry: readonly string[];
    debug: string;
    fourxxPolicy: string;
    memoryLessonIfIssueFound: string;
};

export const CREATOR_FEATURE_PARITY_MAP: readonly CreatorFeatureParityEntry[] = [
    {
        featureId: "creator_dashboard_stats",
        routeSurface: "/dashboard/creator",
        creatorPermission: "creator.dashboard.view",
        sourceOfTruth: "creator analytics/person metrics hydration",
        statusStates: ["hydrated", "stale", "empty", "failed"],
        submitUpdateAction: "read only",
        userFacingConsumer: "creator dashboard stats",
        adminFacingConsumer: "admin analytics/debug creator lane",
        telemetry: ["creator_dashboard_viewed"],
        debug: "creator_lane_debug",
        fourxxPolicy: "auth-role-drift-4xx-policy",
        memoryLessonIfIssueFound: "Check source metrics and admin hydration before changing display math.",
    },
    {
        featureId: "creator_settings",
        routeSurface: "/dashboard/creator/settings",
        creatorPermission: "creator.settings.write",
        sourceOfTruth: "creator settings resolver and creator profile contract",
        statusStates: ["draft", "saved", "needs_changes", "failed"],
        submitUpdateAction: "creator settings update action",
        userFacingConsumer: "creator profile",
        adminFacingConsumer: "admin creator account controls",
        telemetry: ["creator_settings_viewed", "creator_settings_saved"],
        debug: "creator_settings_debug",
        fourxxPolicy: "creator_permission_denied",
        memoryLessonIfIssueFound: "Reuse creator settings contracts before adding local settings state.",
    },
    {
        featureId: "creator_monetization",
        routeSurface: "/dashboard/creator/monetization",
        creatorPermission: "creator.monetization.view",
        sourceOfTruth: "creator monetization contracts",
        statusStates: ["not_configured", "pending", "active", "blocked"],
        submitUpdateAction: "creator monetization settings action",
        userFacingConsumer: "creator profile monetization affordances",
        adminFacingConsumer: "creator monetization readiness lock",
        telemetry: ["creator_monetization_viewed"],
        debug: "creator_monetization_debug",
        fourxxPolicy: "creator_not_configured",
        memoryLessonIfIssueFound: "Do not mix revenue, entitlement, and display state in a component.",
    },
    {
        featureId: "fan_pass",
        routeSurface: "/creator fan pass",
        creatorPermission: "creator.fan_pass.manage",
        sourceOfTruth: "fan pass entitlement and paid-source GumDrop contract",
        statusStates: ["draft", "active", "paused", "expired", "blocked"],
        submitUpdateAction: "fan pass settings action",
        userFacingConsumer: "fan pass purchase/access UI",
        adminFacingConsumer: "fan pass entitlement debug",
        telemetry: ["fan_pass_viewed"],
        debug: "fan_pass_debug",
        fourxxPolicy: "approval_required",
        memoryLessonIfIssueFound: "Paid-source rules must stay outside creator UI shortcuts.",
    },
    {
        featureId: "creator_profile_timeline_broadcasts",
        routeSurface: "/creator/[username]",
        creatorPermission: "creator.profile.write",
        sourceOfTruth: "creator profile timeline and broadcast contracts",
        statusStates: ["draft", "published", "hidden", "failed"],
        submitUpdateAction: "creator broadcast/profile update action",
        userFacingConsumer: "public creator profile",
        adminFacingConsumer: "admin creator/debug profile lane",
        telemetry: ["creator_profile_viewed", "creator_broadcast_created"],
        debug: "creator_profile_debug",
        fourxxPolicy: "creator_permission_denied",
        memoryLessonIfIssueFound: "Actor and target creator IDs must stay separate.",
    },
    {
        featureId: "creator_drop_manager",
        routeSurface: "/dashboard/creator/drops",
        creatorPermission: "creator.drop.submit",
        sourceOfTruth: "src/app/api/creator/drops/route.ts and admin drops review",
        statusStates: ["draft", "submitted", "pending_review", "approved", "rejected", "needs_changes", "expired"],
        submitUpdateAction: "/api/creator/drops POST/PUT",
        userFacingConsumer: "public drop discovery after approval only",
        adminFacingConsumer: "/admin/drops pending creator submission queue",
        telemetry: ["creator_drop_submit_succeeded", "admin_creator_drop_approved", "admin_creator_drop_rejected"],
        debug: "creator_drop_workflow",
        fourxxPolicy: "creator-drop-4xx-policy",
        memoryLessonIfIssueFound: "Inspect the full creator UI to admin approval to user visibility chain.",
    },
    {
        featureId: "creator_chat_pricing_status",
        routeSurface: "/dashboard/creator/chat",
        creatorPermission: "creator.chat.manage",
        sourceOfTruth: "creator chat pricing/status contract",
        statusStates: ["not_configured", "active", "paused", "failed"],
        submitUpdateAction: "creator chat settings action",
        userFacingConsumer: "chat composer pricing and access",
        adminFacingConsumer: "admin chat/debug lane",
        telemetry: ["creator_chat_settings_saved"],
        debug: "creator_chat_debug",
        fourxxPolicy: "creator_permission_denied",
        memoryLessonIfIssueFound: "Do not let chat UI invent pricing truth.",
    },
    {
        featureId: "creator_notifications",
        routeSurface: "/dashboard/creator/notifications",
        creatorPermission: "creator.notifications.manage",
        sourceOfTruth: "notification preference and PWA prompt contracts",
        statusStates: ["enabled", "disabled", "blocked", "failed"],
        submitUpdateAction: "creator notification preference action",
        userFacingConsumer: "follower notification delivery",
        adminFacingConsumer: "notification PWA score lock",
        telemetry: ["notification_permission_requested"],
        debug: "notifications_debug",
        fourxxPolicy: "auth-role-drift-4xx-policy",
        memoryLessonIfIssueFound: "Notification links must degrade safely when creator content state changes.",
    },
    {
        featureId: "creator_subscribers_fans",
        routeSurface: "/dashboard/creator/fans",
        creatorPermission: "creator.fans.view",
        sourceOfTruth: "creator relationship/subscription contracts",
        statusStates: ["hydrated", "stale", "empty", "failed"],
        submitUpdateAction: "read only",
        userFacingConsumer: "follow/subscription affordances",
        adminFacingConsumer: "creator analytics/debug relationships",
        telemetry: ["creator_followed"],
        debug: "creator_relationship_debug",
        fourxxPolicy: "creator_permission_denied",
        memoryLessonIfIssueFound: "Do not count stale or projected relationships as live creator truth.",
    },
    {
        featureId: "creator_media_uploads",
        routeSurface: "/dashboard/creator/drops uploads",
        creatorPermission: "creator.media.upload",
        sourceOfTruth: "creator drop assets route and media access policy",
        statusStates: ["queued", "uploading", "uploaded", "failed", "blocked"],
        submitUpdateAction: "/api/creator/drops/assets",
        userFacingConsumer: "approved drop media only",
        adminFacingConsumer: "admin drop media review",
        telemetry: ["asset_upload_succeeded", "asset_upload_failed"],
        debug: "media_storage_access_debug",
        fourxxPolicy: "media_access_denied",
        memoryLessonIfIssueFound: "Private media cannot become user visible until approval and access checks pass.",
    },
] as const;
