import type { SettingsSurface, SettingsToolContract } from "@/lib/settings/user-settings-contract";

export const CREATOR_DASHBOARD_SETTINGS_SURFACE: SettingsSurface = "creator_dashboard_settings";

export const CREATOR_DASHBOARD_SETTINGS_TOOLS: SettingsToolContract[] = [
  {
    id: "public_profile",
    label: "Public profile",
    surfaceOwner: "creator_dashboard_settings",
    allowedRoles: ["creator", "admin"],
    sourceTruth: "creator_settings",
    route: "/dashboard/creator",
    readEndpoint: "/api/creators/[username]",
    writeEndpoint: "/api/creator/settings",
    simulativeAllowed: false,
    legacyStatus: "canonical",
    requiredTelemetryEvents: ["creator_dashboard_settings_viewed", "creator_settings_section_opened"],
  },
  {
    id: "broadcasts",
    label: "Broadcasts",
    surfaceOwner: "creator_dashboard_settings",
    allowedRoles: ["creator", "admin"],
    sourceTruth: "creator_broadcasts",
    route: "/dashboard/creator",
    readEndpoint: "/api/creator/broadcasts",
    writeEndpoint: "/api/creator/broadcasts",
    simulativeAllowed: false,
    legacyStatus: "canonical",
    requiredTelemetryEvents: ["creator_broadcast_manager_viewed", "creator_broadcast_created"],
  },
  {
    id: "fan_pass",
    label: "Fan Pass",
    surfaceOwner: "creator_dashboard_settings",
    allowedRoles: ["creator", "admin"],
    sourceTruth: "creator_settings",
    route: "/dashboard/creator",
    readEndpoint: "/api/creator/settings",
    writeEndpoint: "/api/creator/settings",
    simulativeAllowed: false,
    legacyStatus: "canonical",
    requiredTelemetryEvents: ["creator_settings_section_opened"],
  },
  {
    id: "messages",
    label: "Messages",
    surfaceOwner: "creator_dashboard_settings",
    allowedRoles: ["creator", "admin"],
    sourceTruth: "server_truth",
    route: "/dashboard/chat",
    readEndpoint: "/api/creator/messages",
    writeEndpoint: "/api/creator/messages",
    simulativeAllowed: false,
    legacyStatus: "canonical",
    requiredTelemetryEvents: ["creator_settings_section_opened"],
  },
  {
    id: "requests",
    label: "Requests",
    surfaceOwner: "creator_dashboard_settings",
    allowedRoles: ["creator", "admin"],
    sourceTruth: "server_truth",
    route: "/dashboard/creator",
    readEndpoint: "/api/creator/requests",
    writeEndpoint: "/api/creator/requests",
    simulativeAllowed: false,
    legacyStatus: "canonical",
    requiredTelemetryEvents: ["creator_settings_section_opened"],
  },
  {
    id: "bookings",
    label: "Live time / bookings",
    surfaceOwner: "creator_dashboard_settings",
    allowedRoles: ["creator", "admin"],
    sourceTruth: "creator_settings",
    route: "/dashboard/creator",
    readEndpoint: "/api/creator/bookings",
    writeEndpoint: "/api/creator/bookings",
    simulativeAllowed: false,
    legacyStatus: "canonical",
    requiredTelemetryEvents: ["creator_settings_section_opened"],
  },
  {
    id: "availability",
    label: "Availability",
    surfaceOwner: "creator_dashboard_settings",
    allowedRoles: ["creator", "admin"],
    sourceTruth: "creator_settings",
    route: "/dashboard/creator",
    readEndpoint: "/api/creator/settings",
    writeEndpoint: "/api/creator/settings",
    simulativeAllowed: false,
    legacyStatus: "canonical",
    requiredTelemetryEvents: ["creator_settings_section_opened"],
  },
  {
    id: "earnings",
    label: "Earnings / payout",
    surfaceOwner: "creator_dashboard_settings",
    allowedRoles: ["creator", "admin"],
    sourceTruth: "server_truth",
    route: "/dashboard/creator",
    readEndpoint: "/api/creator/settings",
    writeEndpoint: "/api/creator/payouts",
    simulativeAllowed: false,
    legacyStatus: "canonical",
    requiredTelemetryEvents: ["creator_settings_section_opened"],
  },
  {
    id: "notifications_audience",
    label: "Notifications / audience",
    surfaceOwner: "creator_dashboard_settings",
    allowedRoles: ["creator", "admin"],
    sourceTruth: "server_truth",
    route: "/dashboard/creator",
    readEndpoint: "/api/creator/settings",
    writeEndpoint: "/api/creator/relationships",
    simulativeAllowed: false,
    legacyStatus: "canonical",
    requiredTelemetryEvents: ["creator_settings_section_opened"],
  },
];
