export const USER_MOBILE_BOTTOM_NAV_HEIGHT = "3.5rem";
export const USER_MOBILE_BOTTOM_NAV_SAFE_GAP = "0.85rem";
export const USER_MOBILE_BOTTOM_NAV_BOTTOM_OFFSET = `calc(env(safe-area-inset-bottom) + ${USER_MOBILE_BOTTOM_NAV_SAFE_GAP})`;
export const USER_MOBILE_BOTTOM_NAV_RESERVED_HEIGHT = `calc(${USER_MOBILE_BOTTOM_NAV_HEIGHT} + ${USER_MOBILE_BOTTOM_NAV_BOTTOM_OFFSET})`;
export const USER_MOBILE_FLOATING_CONTROL_BOTTOM_OFFSET = `calc(${USER_MOBILE_BOTTOM_NAV_RESERVED_HEIGHT} + ${USER_MOBILE_BOTTOM_NAV_SAFE_GAP})`;
export const USER_MOBILE_CHAT_TOP_GAP = "0.75rem";
export const USER_MOBILE_CHAT_TOP_RESERVED_HEIGHT = `calc(env(safe-area-inset-top) + 4rem + ${USER_MOBILE_CHAT_TOP_GAP})`;
export const USER_MOBILE_CHAT_CONTROL_GAP = "0.875rem";
export const USER_MOBILE_CHAT_BOTTOM_RESERVED_HEIGHT = USER_MOBILE_BOTTOM_NAV_RESERVED_HEIGHT;
export const USER_MOBILE_CHAT_BOTTOM_NAV_SAFE_OFFSET = `var(--user-mobile-chat-bottom-reserved-height, ${USER_MOBILE_CHAT_BOTTOM_RESERVED_HEIGHT})`;
export const USER_MOBILE_CHAT_CONTROL_BOTTOM_OFFSET = USER_MOBILE_CHAT_CONTROL_GAP;
export const USER_MOBILE_CHAT_VIEWPORT_HEIGHT = "var(--chat-visual-viewport-height, 100dvh)";
export const USER_MOBILE_CHAT_ANDROID_PWA_VISUAL_HEIGHT = "var(--kd-android-pwa-visual-height, var(--chat-visual-viewport-height, 100dvh))";
export const USER_MOBILE_CHAT_ANDROID_PWA_BOTTOM_NAV_HEIGHT = "var(--kd-android-pwa-bottom-nav-height, var(--user-mobile-chat-bottom-reserved-height, 0px))";
export const USER_MOBILE_CHAT_ANDROID_PWA_BOTTOM_SAFE_PADDING = "var(--kd-android-pwa-bottom-safe-padding, 0px)";
export const USER_MOBILE_CHAT_ANDROID_PWA_BOTTOM_RESERVED_HEIGHT =
    `calc(${USER_MOBILE_CHAT_ANDROID_PWA_BOTTOM_NAV_HEIGHT} + ${USER_MOBILE_CHAT_ANDROID_PWA_BOTTOM_SAFE_PADDING})`;
export const USER_MOBILE_CHAT_VIEWPORT_SHELL_HEIGHT = `calc(${USER_MOBILE_CHAT_VIEWPORT_HEIGHT} - var(--root-shell-top-spacing, ${USER_MOBILE_CHAT_TOP_RESERVED_HEIGHT}))`;
export const USER_MOBILE_CHAT_ANDROID_PWA_VIEWPORT_SHELL_HEIGHT =
    `calc(${USER_MOBILE_CHAT_ANDROID_PWA_VISUAL_HEIGHT} - var(--root-shell-top-spacing, ${USER_MOBILE_CHAT_TOP_RESERVED_HEIGHT}))`;
export const CHAT_LIST_CONTROL_HEIGHT = "3.25rem";

export const CHAT_LIST_CONTROLS_BOTTOM_OFFSET = USER_MOBILE_CHAT_CONTROL_BOTTOM_OFFSET;
export const CHAT_LIST_FLOATING_ACTION_BOTTOM_OFFSET = CHAT_LIST_CONTROLS_BOTTOM_OFFSET;
export const CHAT_LIST_SCROLL_PADDING_BOTTOM = `calc(${CHAT_LIST_CONTROLS_BOTTOM_OFFSET} + ${CHAT_LIST_CONTROL_HEIGHT} + ${USER_MOBILE_CHAT_CONTROL_GAP})`;
export const CHAT_THREAD_COMPOSER_PADDING_BOTTOM = USER_MOBILE_CHAT_CONTROL_BOTTOM_OFFSET;
