export const USER_MOBILE_BOTTOM_NAV_HEIGHT = "3.5rem";
export const USER_MOBILE_BOTTOM_NAV_SAFE_GAP = "0.85rem";
export const USER_MOBILE_BOTTOM_NAV_BOTTOM_OFFSET = `calc(env(safe-area-inset-bottom) + ${USER_MOBILE_BOTTOM_NAV_SAFE_GAP})`;
export const USER_MOBILE_BOTTOM_NAV_RESERVED_HEIGHT = `calc(${USER_MOBILE_BOTTOM_NAV_HEIGHT} + ${USER_MOBILE_BOTTOM_NAV_BOTTOM_OFFSET})`;
export const USER_MOBILE_CHAT_CONTROL_GAP = "1rem";
export const USER_MOBILE_CHAT_BOTTOM_RESERVED_HEIGHT = `calc(${USER_MOBILE_BOTTOM_NAV_RESERVED_HEIGHT} + ${USER_MOBILE_CHAT_CONTROL_GAP})`;

export const CHAT_LIST_CONTROLS_BOTTOM_OFFSET = USER_MOBILE_CHAT_BOTTOM_RESERVED_HEIGHT;
export const CHAT_LIST_FLOATING_ACTION_BOTTOM_OFFSET = "0px";
export const CHAT_LIST_SCROLL_PADDING_BOTTOM = `calc(${USER_MOBILE_CHAT_BOTTOM_RESERVED_HEIGHT} + 5rem)`;
export const CHAT_THREAD_COMPOSER_PADDING_BOTTOM = USER_MOBILE_CHAT_BOTTOM_RESERVED_HEIGHT;
