export type SettingSurface = "account" | "creator" | "privacy" | "support" | "danger_zone";
export type SettingConnectionStatus = "connected" | "link_only" | "client_action" | "not_configured" | "intentionally_hidden";
export type SettingStaleConflictStatus = "canonical" | "stale_duplicate_removed" | "unsafe_unknown";
export type SettingVisibility = "user" | "creator" | "admin" | "guest";

export type SettingItem = {
  settingId: string;
  label: string;
  surface: SettingSurface;
  routeSource: string;
  componentSource: string;
  backendRouteOrAction: string;
  stateSource: string;
  defaultValue: string;
  saveBehavior: SettingConnectionStatus;
  telemetryEvents: string[];
  debugVisibility: string;
  featureRegistrationId: string;
  visibility: SettingVisibility[];
  consentImpact: "none" | "minimal_analytics" | "full_behavioral" | "required_integrity";
  accountSafetyImpact: "none" | "low" | "medium" | "high";
  userFacingImpact: string;
  staleConflictStatus: SettingStaleConflictStatus;
};

export const SETTINGS_TELEMETRY_EVENTS = [
  "settings_surface_viewed",
  "setting_toggle_changed",
  "setting_action_clicked",
  "setting_save_succeeded",
  "setting_save_failed",
  "account_delete_clicked",
  "account_delete_confirm_opened",
  "account_delete_confirmed",
  "account_delete_cancelled",
  "account_delete_request_submitted",
  "account_delete_failed",
  "account_delete_completed",
  "data_export_requested",
  "creator_setting_updated",
] as const;

export const SETTINGS_DEBUG_LANE = {
  laneId: "settings_health",
  label: "Settings health",
  sourceOwner: "settings",
  sourceOfTruth: "src/lib/debug/settings-debug-validator-authority.ts",
  drilldownTarget: "/admin/debug?tab=advanced#settings-health",
  rawDetailsDefaultOpen: false,
  oneSourceOfTruth: true,
} as const;

const accountSource = {
  routeSource: "/settings with /dashboard/settings, /dashboard/profile, /profile/settings, and /account redirect aliases",
  componentSource: "src/components/Settings/UserSettingsPage.tsx",
  backendRouteOrAction: "/api/user/profile",
  stateSource: "users/{uid}",
  featureRegistrationId: "user_dashboard",
  visibility: ["user", "creator", "admin"] as SettingVisibility[],
  staleConflictStatus: "canonical" as const,
};

const creatorSource = {
  routeSource: "/dashboard/creator/settings",
  componentSource: "src/components/Creators/CreatorDashboardSettingsHub.tsx",
  backendRouteOrAction: "/api/creator/settings",
  stateSource: "users/{uid}.creatorSettings",
  featureRegistrationId: "creator_settings",
  visibility: ["creator", "admin"] as SettingVisibility[],
  staleConflictStatus: "canonical" as const,
};

export const SETTINGS_SURFACE_ITEMS = [
  {
    ...accountSource,
    settingId: "profile_basics",
    label: "Profile basics",
    surface: "account",
    defaultValue: "current authenticated user profile",
    saveBehavior: "connected",
    telemetryEvents: ["settings_surface_viewed", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "none",
    accountSafetyImpact: "low",
    userFacingImpact: "Controls display name, username, avatar, and basic account identity.",
  },
  {
    ...accountSource,
    settingId: "account_timezone",
    label: "Timezone",
    surface: "account",
    defaultValue: "Auto",
    saveBehavior: "connected",
    telemetryEvents: ["setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "none",
    accountSafetyImpact: "none",
    userFacingImpact: "Controls localized account presentation.",
  },
  {
    ...accountSource,
    settingId: "notification_preferences",
    label: "Notification preferences",
    surface: "account",
    defaultValue: "service notices required, optional alerts enabled",
    saveBehavior: "connected",
    telemetryEvents: ["setting_toggle_changed", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "required_integrity",
    accountSafetyImpact: "medium",
    userFacingImpact: "Controls browser, in-app, new release, and ending soon alerts.",
  },
  {
    ...accountSource,
    settingId: "anonymous_analytics",
    label: "Anonymous analytics",
    surface: "privacy",
    defaultValue: "off unless user grants optional tracking",
    saveBehavior: "connected",
    telemetryEvents: ["setting_toggle_changed", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "minimal_analytics",
    accountSafetyImpact: "medium",
    userFacingImpact: "Controls consent-safe anonymous measurement.",
  },
  {
    ...accountSource,
    settingId: "account_linked_analytics",
    label: "Account-linked analytics",
    surface: "privacy",
    defaultValue: "off unless user grants identified analytics",
    saveBehavior: "connected",
    telemetryEvents: ["setting_toggle_changed", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "full_behavioral",
    accountSafetyImpact: "medium",
    userFacingImpact: "Controls identified analytics and linked-person measurement.",
  },
  {
    ...accountSource,
    settingId: "activity_recommendations",
    label: "Activity recommendations",
    surface: "privacy",
    defaultValue: "off unless identified analytics is enabled",
    saveBehavior: "connected",
    telemetryEvents: ["setting_toggle_changed", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "full_behavioral",
    accountSafetyImpact: "medium",
    userFacingImpact: "Controls recommendation eligibility from user activity.",
  },
  {
    ...accountSource,
    settingId: "honor_global_privacy_control",
    label: "Honor Global Privacy Control",
    surface: "privacy",
    defaultValue: "enabled",
    saveBehavior: "connected",
    telemetryEvents: ["setting_toggle_changed", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "required_integrity",
    accountSafetyImpact: "high",
    userFacingImpact: "Controls whether browser GPC is honored in account privacy state.",
  },
  {
    ...accountSource,
    settingId: "essential_only_mode",
    label: "Essential Only Mode",
    surface: "privacy",
    defaultValue: "optional tracking off after action",
    saveBehavior: "connected",
    telemetryEvents: ["setting_action_clicked", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "required_integrity",
    accountSafetyImpact: "high",
    userFacingImpact: "Turns off optional analytics and recommendations immediately.",
  },
  {
    ...accountSource,
    settingId: "download_my_data",
    label: "Download My Data",
    surface: "privacy",
    backendRouteOrAction: "/api/user/data",
    stateSource: "authenticated user export collections",
    defaultValue: "on-demand authenticated JSON export",
    saveBehavior: "connected",
    telemetryEvents: ["setting_action_clicked", "data_export_requested", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "required_integrity",
    accountSafetyImpact: "high",
    userFacingImpact: "Exports account, privacy, activity, creator, security, and analytics records scoped to the caller.",
  },
  {
    ...accountSource,
    settingId: "privacy_policy",
    label: "Privacy Policy",
    surface: "privacy",
    backendRouteOrAction: "/privacy",
    stateSource: "src/lib/platform-config.ts",
    defaultValue: "latest privacy policy route",
    saveBehavior: "link_only",
    telemetryEvents: ["setting_action_clicked"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "none",
    accountSafetyImpact: "low",
    userFacingImpact: "Links to privacy policy copy.",
  },
  {
    ...accountSource,
    settingId: "faq",
    label: "FAQ",
    surface: "support",
    backendRouteOrAction: "/faq",
    stateSource: "FAQ route",
    defaultValue: "support route link",
    saveBehavior: "link_only",
    telemetryEvents: ["setting_action_clicked"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "none",
    accountSafetyImpact: "low",
    userFacingImpact: "Links to FAQ help.",
  },
  {
    ...accountSource,
    settingId: "support",
    label: "Support",
    surface: "support",
    backendRouteOrAction: "/dashboard/support",
    stateSource: "support inbox routes",
    defaultValue: "support inbox route link",
    saveBehavior: "link_only",
    telemetryEvents: ["setting_action_clicked"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "required_integrity",
    accountSafetyImpact: "medium",
    userFacingImpact: "Links to authenticated support.",
  },
  {
    ...accountSource,
    settingId: "policies",
    label: "Policies",
    surface: "support",
    backendRouteOrAction: "/privacy",
    stateSource: "legal routes",
    defaultValue: "policy route link",
    saveBehavior: "link_only",
    telemetryEvents: ["setting_action_clicked"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "none",
    accountSafetyImpact: "low",
    userFacingImpact: "Links to policy copy.",
  },
  {
    ...accountSource,
    settingId: "sign_out",
    label: "Sign out",
    surface: "account",
    backendRouteOrAction: "AuthContext.logout",
    stateSource: "Firebase Auth client session",
    defaultValue: "current session",
    saveBehavior: "client_action",
    telemetryEvents: ["setting_action_clicked"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "required_integrity",
    accountSafetyImpact: "medium",
    userFacingImpact: "Signs the current session out.",
  },
  {
    ...accountSource,
    settingId: "delete_account",
    label: "Delete Account",
    surface: "danger_zone",
    backendRouteOrAction: "/api/user/delete",
    stateSource: "authenticated user deletion route",
    defaultValue: "confirmation required",
    saveBehavior: "connected",
    telemetryEvents: ["account_delete_clicked", "account_delete_confirm_opened", "account_delete_confirmed", "account_delete_request_submitted", "account_delete_failed", "account_delete_completed"],
    debugVisibility: "account_safety, settings_health",
    consentImpact: "required_integrity",
    accountSafetyImpact: "high",
    userFacingImpact: "Starts confirmed authenticated account deletion.",
  },
  {
    ...creatorSource,
    settingId: "profile_basics",
    label: "Profile basics",
    surface: "creator",
    defaultValue: "display name, bio, profile photo",
    saveBehavior: "connected",
    telemetryEvents: ["settings_surface_viewed", "creator_setting_updated", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "required_integrity",
    accountSafetyImpact: "medium",
    userFacingImpact: "Controls public creator profile name, bio, and photo.",
  },
  {
    ...creatorSource,
    settingId: "creator_profile_visibility",
    label: "Creator profile visibility",
    surface: "creator",
    defaultValue: "profile route visible when creator identity is routable",
    saveBehavior: "connected",
    telemetryEvents: ["creator_setting_updated", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "required_integrity",
    accountSafetyImpact: "medium",
    userFacingImpact: "Controls public creator profile readiness through profile basics and routing.",
  },
  {
    ...creatorSource,
    settingId: "fan_pass_enabled",
    label: "Enable Fan Pass",
    surface: "creator",
    defaultValue: "creator settings default",
    saveBehavior: "connected",
    telemetryEvents: ["setting_toggle_changed", "creator_setting_updated", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "required_integrity",
    accountSafetyImpact: "high",
    userFacingImpact: "Controls whether Fan Pass appears on fan-facing creator surfaces.",
  },
  {
    ...creatorSource,
    settingId: "fan_pass_pricing",
    label: "Fan Pass price GD",
    surface: "creator",
    defaultValue: "CREATOR_SUBSCRIPTION_MIN_GD or creator saved price",
    saveBehavior: "connected",
    telemetryEvents: ["creator_setting_updated", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "required_integrity",
    accountSafetyImpact: "high",
    userFacingImpact: "Controls paid-GD Fan Pass pricing; does not change payment math.",
  },
  {
    ...creatorSource,
    settingId: "creator_experiences_enabled",
    label: "GumDrop experiences",
    surface: "creator",
    defaultValue: "creator request and call defaults",
    saveBehavior: "connected",
    telemetryEvents: ["setting_toggle_changed", "creator_setting_updated", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "required_integrity",
    accountSafetyImpact: "high",
    userFacingImpact: "Controls public request and live-time availability.",
  },
  {
    ...creatorSource,
    settingId: "paid_message_price_gd",
    label: "Paid message price GD",
    surface: "creator",
    defaultValue: "creator settings default when messaging is enabled",
    saveBehavior: "connected",
    telemetryEvents: ["creator_setting_updated"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "required_integrity",
    accountSafetyImpact: "medium",
    userFacingImpact: "Maps legacy paid message pricing to creator settings only when present.",
  },
  {
    ...creatorSource,
    settingId: "custom_request_min_gd",
    label: "Request base price GD",
    surface: "creator",
    defaultValue: "creator request base price",
    saveBehavior: "connected",
    telemetryEvents: ["creator_setting_updated", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "required_integrity",
    accountSafetyImpact: "high",
    userFacingImpact: "Controls custom request pricing from creator settings.",
  },
  {
    ...creatorSource,
    settingId: "live_call_enabled",
    label: "Enable live time",
    surface: "creator",
    defaultValue: "creator booking default",
    saveBehavior: "connected",
    telemetryEvents: ["setting_toggle_changed", "creator_setting_updated", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "required_integrity",
    accountSafetyImpact: "high",
    userFacingImpact: "Controls whether live-time booking appears.",
  },
  {
    ...creatorSource,
    settingId: "live_call_price_gd",
    label: "Call price per minute GD",
    surface: "creator",
    defaultValue: "creator call price",
    saveBehavior: "connected",
    telemetryEvents: ["creator_setting_updated", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "required_integrity",
    accountSafetyImpact: "high",
    userFacingImpact: "Controls creator call pricing without changing booking math.",
  },
  {
    ...creatorSource,
    settingId: "live_call_duration_minutes",
    label: "Call duration minutes",
    surface: "creator",
    defaultValue: "booking route duration input",
    saveBehavior: "not_configured",
    telemetryEvents: ["creator_setting_updated"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "required_integrity",
    accountSafetyImpact: "medium",
    userFacingImpact: "Not currently rendered in Creator Settings; booking flow owns duration selection.",
  },
  {
    ...creatorSource,
    settingId: "live_call_weeklyAvailability",
    label: "Weekly availability",
    surface: "creator",
    defaultValue: "availabilityWindows in creator settings",
    saveBehavior: "not_configured",
    telemetryEvents: ["creator_setting_updated"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "required_integrity",
    accountSafetyImpact: "medium",
    userFacingImpact: "Not currently rendered in this compact settings panel; booking manager owns availability detail.",
  },
  {
    ...creatorSource,
    settingId: "broadcasts_enabled",
    label: "Enable broadcasts",
    surface: "creator",
    defaultValue: "creator settings default",
    saveBehavior: "connected",
    telemetryEvents: ["setting_toggle_changed", "creator_setting_updated", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "required_integrity",
    accountSafetyImpact: "medium",
    userFacingImpact: "Controls whether creator broadcasts can be sent and surfaced.",
  },
  {
    ...creatorSource,
    settingId: "broadcast_audience",
    label: "Default audience",
    surface: "creator",
    defaultValue: "followers",
    saveBehavior: "connected",
    telemetryEvents: ["creator_setting_updated", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "required_integrity",
    accountSafetyImpact: "medium",
    userFacingImpact: "Controls default broadcast targeting.",
  },
  {
    ...creatorSource,
    settingId: "timeline_enabled",
    label: "Show profile timeline",
    surface: "creator",
    defaultValue: "enabled",
    saveBehavior: "connected",
    telemetryEvents: ["setting_toggle_changed", "creator_setting_updated", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "minimal_analytics",
    accountSafetyImpact: "medium",
    userFacingImpact: "Controls public creator timeline visibility.",
  },
  {
    ...creatorSource,
    settingId: "show_drops_on_timeline",
    label: "Show approved drops",
    surface: "creator",
    defaultValue: "enabled",
    saveBehavior: "connected",
    telemetryEvents: ["setting_toggle_changed", "creator_setting_updated", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "minimal_analytics",
    accountSafetyImpact: "medium",
    userFacingImpact: "Controls whether approved Drops appear on the profile timeline.",
  },
  {
    ...creatorSource,
    settingId: "show_broadcasts_on_timeline",
    label: "Show broadcasts",
    surface: "creator",
    defaultValue: "enabled",
    saveBehavior: "connected",
    telemetryEvents: ["setting_toggle_changed", "creator_setting_updated", "setting_save_succeeded", "setting_save_failed"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "minimal_analytics",
    accountSafetyImpact: "medium",
    userFacingImpact: "Controls whether broadcasts appear on the profile timeline.",
  },
  {
    ...creatorSource,
    settingId: "creator_drop_manager",
    label: "Creator Drop Manager",
    surface: "creator",
    backendRouteOrAction: "/dashboard/creator/drops",
    stateSource: "creator drop manager routes",
    defaultValue: "manager drilldown",
    saveBehavior: "link_only",
    telemetryEvents: ["setting_action_clicked"],
    debugVisibility: SETTINGS_DEBUG_LANE.laneId,
    consentImpact: "required_integrity",
    accountSafetyImpact: "medium",
    userFacingImpact: "Hands off Drop creation and management to Creator Drop Manager.",
  },
] as const satisfies readonly SettingItem[];

export function getSettingsSurfaceItems(surface?: SettingSurface) {
  return SETTINGS_SURFACE_ITEMS.filter((item) => !surface || item.surface === surface);
}

export function getDisconnectedSettings() {
  return SETTINGS_SURFACE_ITEMS.filter((item) => {
    const typedItem = item as SettingItem;
    return typedItem.saveBehavior === "not_configured" || typedItem.staleConflictStatus === "unsafe_unknown";
  });
}

export function getSettingsDebugLaneSummary() {
  const disconnected = getDisconnectedSettings();
  return {
    ...SETTINGS_DEBUG_LANE,
    status: disconnected.length > 0 ? "source_ready_with_honest_not_configured_items" : "source_ready",
    visibleSettingCount: SETTINGS_SURFACE_ITEMS.length,
    disconnectedSettingCount: disconnected.length,
    backlogItems: disconnected.map((item) => ({
      settingId: item.settingId,
      surface: item.surface,
      missingRouteOrAction: item.backendRouteOrAction,
      scoreImpact: item.accountSafetyImpact === "high" ? "high" : "medium",
      nextFix: item.userFacingImpact,
    })),
  };
}
