export const API_COST_CLASSES = [
  "free_read",
  "firestore_read",
  "firestore_write",
  "firestore_transaction",
  "firestore_listener",
  "storage_egress",
  "ga_quota",
  "ai_paid",
  "sql_dataconnect_agent_context_mirror",
  "sql_forbidden",
  "cloud_run_compute",
  "payment_sensitive",
  "support_admin",
  "unknown",
] as const;

export type ApiCostClass = (typeof API_COST_CLASSES)[number];
export type ApiCachePolicy = "static" | "swr" | "hot_cache" | "no_store";
export type ApiAuthRequired = "none" | "user" | "admin";

export type ApiCostContract = {
  routePattern: string;
  methods: string[];
  costClass: ApiCostClass;
  ratePolicy: string;
  cachePolicy: ApiCachePolicy;
  authRequired: ApiAuthRequired;
  trustedOriginRequired: boolean;
  budgetGuardRequired: boolean;
  maxExpectedCallsPerUserPerMinute?: number;
  maxExpectedFirestoreReadsPerCall?: number;
  maxExpectedFirestoreWritesPerCall?: number;
  maxExpectedStorageBytesPerCall?: number;
  maxExpectedAiTokensPerCall?: number;
  notes: string;
};

export const ALL_API_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE"] as const;

export const API_COST_CONTRACTS: ApiCostContract[] = [
  {
    routePattern: "/api/health",
    methods: ["GET"],
    costClass: "free_read",
    ratePolicy: "none",
    cachePolicy: "no_store",
    authRequired: "none",
    trustedOriginRequired: false,
    budgetGuardRequired: false,
    maxExpectedCallsPerUserPerMinute: 60,
    notes: "Health check is intentionally unauthenticated, no-store, and must not touch Google paid services.",
  },
  {
    routePattern: "/api/wallet/packages",
    methods: ["GET"],
    costClass: "free_read",
    ratePolicy: "STANDARD",
    cachePolicy: "static",
    authRequired: "none",
    trustedOriginRequired: false,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 20,
    notes: "Static package metadata; no Firestore/Payment calls allowed.",
  },
  {
    routePattern: "/api/admin/ai/**",
    methods: [...ALL_API_METHODS],
    costClass: "ai_paid",
    ratePolicy: "ADMIN_AI_* adaptive limits",
    cachePolicy: "no_store",
    authRequired: "admin",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 12,
    maxExpectedAiTokensPerCall: 4_000,
    maxExpectedStorageBytesPerCall: 10_485_760,
    notes: "Admin-only Vertex/Gemini surface. Uploaded template/reference images retain the canonical 10 MiB file cap; paid generation requires a feature toggle, model allowlist, bounded inputs/outputs, cost estimate, and telemetry/debug evidence.",
  },
  {
    routePattern: "/api/admin/debug/assistant/**",
    methods: [...ALL_API_METHODS],
    costClass: "ai_paid",
    ratePolicy: "ADMIN_DEBUG_ASSISTANT adaptive limits",
    cachePolicy: "no_store",
    authRequired: "admin",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 12,
    maxExpectedAiTokensPerCall: 4_000,
    notes: "Admin-only AI assistant. Must stay behind admin auth, trusted origin, and adaptive budget guard.",
  },
  {
    routePattern: "/api/admin/analytics/**",
    methods: [...ALL_API_METHODS],
    costClass: "ga_quota",
    ratePolicy: "ADMIN_ANALYTICS / ADMIN_ANALYTICS_REALTIME_ADAPTIVE",
    cachePolicy: "hot_cache",
    authRequired: "admin",
    trustedOriginRequired: false,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 90,
    maxExpectedFirestoreReadsPerCall: 500,
    notes: "Admin GA/Data API surface. Must prefer snapshot/hot-cache layers, return quota where supported, and emit quota/debug evidence.",
  },
  {
    routePattern: "/api/admin/support/**",
    methods: [...ALL_API_METHODS],
    costClass: "support_admin",
    ratePolicy: "ADMIN",
    cachePolicy: "no_store",
    authRequired: "admin",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 30,
    maxExpectedFirestoreReadsPerCall: 80,
    maxExpectedFirestoreWritesPerCall: 4,
    notes: "Admin support inbox reads/replies across nested support messages and must preserve admin auth and user privacy.",
  },
  {
    routePattern: "/api/admin-ui-test-session",
    methods: ["GET"],
    costClass: "free_read",
    ratePolicy: "none; disabled unless local admin UI fixture flag is enabled",
    cachePolicy: "no_store",
    authRequired: "none",
    trustedOriginRequired: false,
    budgetGuardRequired: false,
    maxExpectedCallsPerUserPerMinute: 6,
    notes: "Local admin UI test bootstrap only. It sets an ephemeral fixture cookie when explicitly enabled and must not touch Firestore, providers, billing, or production admin truth.",
  },
  {
    routePattern: "/api/admin/content",
    methods: [...ALL_API_METHODS],
    costClass: "storage_egress",
    ratePolicy: "MEDIA_PROXY / ADMIN_STORAGE_UPLOAD",
    cachePolicy: "no_store",
    authRequired: "admin",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 30,
    maxExpectedStorageBytesPerCall: 262_144_000,
    notes: "Admin content/storage surface. Storage list/read paths stay MEDIA_PROXY rate limited; uploads use ADMIN_STORAGE_UPLOAD. Storage calls must stay admin-only and expose short-lived admin preview URLs only.",
  },
  {
    routePattern: "/api/admin/creator-agreements",
    methods: [...ALL_API_METHODS],
    costClass: "storage_egress",
    ratePolicy: "MEDIA_PROXY",
    cachePolicy: "no_store",
    authRequired: "admin",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 30,
    maxExpectedStorageBytesPerCall: 12_582_912,
    maxExpectedFirestoreReadsPerCall: 20,
    maxExpectedFirestoreWritesPerCall: 8,
    notes: "Admin creator agreement document surface. Storage calls must stay admin-only, MEDIA_PROXY rate limited, path-scoped to creator-agreements/, and expose metadata or short-lived signed document previews only.",
  },
  {
    routePattern: "/api/admin/user/[userId]/creator-onboarding/id-document",
    methods: ["GET"],
    costClass: "storage_egress",
    ratePolicy: "MEDIA_PROXY",
    cachePolicy: "no_store",
    authRequired: "admin",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 15,
    maxExpectedStorageBytesPerCall: 15_728_640,
    maxExpectedFirestoreReadsPerCall: 1,
    notes: "Admin creator ID document preview surface. Storage calls must stay admin-only, MEDIA_PROXY rate limited, path-scoped to creator-onboarding/{userId}/id/{side}/, and never expose raw Storage URLs.",
  },
  {
    routePattern: "/api/admin/**",
    methods: [...ALL_API_METHODS],
    costClass: "firestore_read",
    ratePolicy: "ADMIN / route-specific admin limits",
    cachePolicy: "no_store",
    authRequired: "admin",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 30,
    maxExpectedFirestoreReadsPerCall: 250,
    maxExpectedFirestoreWritesPerCall: 20,
    notes: "Default admin API contract. Mutations require trusted origin; heavy reads should be bounded or cached.",
  },
  {
    routePattern: "/api/analytics/**",
    methods: [...ALL_API_METHODS],
    costClass: "firestore_write",
    ratePolicy: "ANALYTICS_WRITE",
    cachePolicy: "no_store",
    authRequired: "none",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 30,
    maxExpectedFirestoreWritesPerCall: 4,
    notes: "Telemetry ingest must preserve consent/session enrichment and avoid unbounded write fanout.",
  },
  {
    routePattern: "/api/internal/analytics/materialize-user-index",
    methods: ["POST"],
    costClass: "firestore_transaction",
    ratePolicy: "CRON",
    cachePolicy: "no_store",
    authRequired: "none",
    trustedOriginRequired: false,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 12,
    maxExpectedFirestoreReadsPerCall: 2_000,
    maxExpectedFirestoreWritesPerCall: 50,
    notes: "Service-to-service CRON bearer authentication is the trusted-origin exemption. The v3 analytics materializer consumes at most 5 leased requests and 200 facts per subject; 50-record lineage query caps keep the conservative source bound below 2,000 reads and 50 writes per call, with a 30-second runtime cap, retry backoff, and deterministic receipts.",
  },
  {
    routePattern: "/api/auth/**",
    methods: [...ALL_API_METHODS],
    costClass: "firestore_read",
    ratePolicy: "STANDARD / SENSITIVE_WRITE",
    cachePolicy: "no_store",
    authRequired: "none",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 20,
    maxExpectedFirestoreReadsPerCall: 12,
    notes: "Auth helper endpoints may be public but must stay trusted-origin and rate limited.",
  },
  {
    routePattern: "/api/chat/attachments/**",
    methods: [...ALL_API_METHODS],
    costClass: "storage_egress",
    ratePolicy: "STANDARD / MEDIA_PROXY",
    cachePolicy: "no_store",
    authRequired: "user",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 20,
    maxExpectedStorageBytesPerCall: 20_000_000,
    notes: "Chat attachment preparation/completion touches Storage and must stay user-scoped, rate limited, and bounded.",
  },
  {
    routePattern: "/api/chat/**",
    methods: [...ALL_API_METHODS],
    costClass: "payment_sensitive",
    ratePolicy: "STANDARD / SENSITIVE_WRITE",
    cachePolicy: "no_store",
    authRequired: "user",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 20,
    maxExpectedFirestoreReadsPerCall: 80,
    maxExpectedFirestoreWritesPerCall: 10,
    notes: "Chat can debit paid-source GumDrops. Keep business logic server-authoritative and rate limited.",
  },
  {
    routePattern: "/api/bug-reports",
    methods: ["POST"],
    costClass: "firestore_transaction",
    ratePolicy: "STANDARD",
    cachePolicy: "no_store",
    authRequired: "user",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 20,
    maxExpectedFirestoreReadsPerCall: 4,
    maxExpectedFirestoreWritesPerCall: 4,
    notes: "User bug report intake is same-origin, authenticated, body-bounded, deduped, and writes one report plus an optional reward-source transaction.",
  },
  {
    routePattern: "/api/checkin",
    methods: ["POST"],
    costClass: "firestore_transaction",
    ratePolicy: "SENSITIVE_WRITE",
    cachePolicy: "no_store",
    authRequired: "user",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 3,
    maxExpectedFirestoreReadsPerCall: 10,
    maxExpectedFirestoreWritesPerCall: 8,
    notes: "Daily check-in writes reward-source balance and must remain idempotent and rate limited.",
  },
  {
    routePattern: "/api/creator/discovery",
    methods: ["GET"],
    costClass: "firestore_read",
    ratePolicy: "RELAXED",
    cachePolicy: "swr",
    authRequired: "none",
    trustedOriginRequired: false,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 60,
    maxExpectedFirestoreReadsPerCall: 60,
    notes: "Public creator discovery must be bounded and should prefer cache/server seeding.",
  },
  {
    routePattern: "/api/creator/drops/assets",
    methods: [...ALL_API_METHODS],
    costClass: "storage_egress",
    ratePolicy: "STANDARD / MEDIA_PROXY",
    cachePolicy: "no_store",
    authRequired: "user",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 20,
    maxExpectedStorageBytesPerCall: 262_144_000,
    notes: "Creator Drop asset upload/download surface; the canonical product and global-cost limit is 250 MiB per file, and access must stay creator/user-scoped and rate limited.",
  },
  {
    routePattern: "/api/creator/onboarding/agreement-document",
    methods: ["GET"],
    costClass: "storage_egress",
    ratePolicy: "MEDIA_PROXY",
    cachePolicy: "no_store",
    authRequired: "user",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 15,
    maxExpectedStorageBytesPerCall: 12_582_912,
    maxExpectedFirestoreReadsPerCall: 2,
    notes: "Creator agreement document preview is authenticated, creator-scoped, MEDIA_PROXY rate limited, path-scoped to creator-agreements/, and exposes only short-lived signed document URLs.",
  },
  {
    routePattern: "/api/creator/bookings",
    methods: [...ALL_API_METHODS],
    costClass: "payment_sensitive",
    ratePolicy: "SENSITIVE_WRITE",
    cachePolicy: "no_store",
    authRequired: "user",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 5,
    maxExpectedFirestoreReadsPerCall: 80,
    maxExpectedFirestoreWritesPerCall: 12,
    notes: "Creator booking spend uses paid-source balance only.",
  },
  {
    routePattern: "/api/creator/requests",
    methods: [...ALL_API_METHODS],
    costClass: "payment_sensitive",
    ratePolicy: "SENSITIVE_WRITE",
    cachePolicy: "no_store",
    authRequired: "user",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 5,
    maxExpectedFirestoreReadsPerCall: 80,
    maxExpectedFirestoreWritesPerCall: 12,
    notes: "Creator request spend uses paid-source balance only.",
  },
  {
    routePattern: "/api/creator/subscriptions",
    methods: [...ALL_API_METHODS],
    costClass: "payment_sensitive",
    ratePolicy: "SENSITIVE_WRITE",
    cachePolicy: "no_store",
    authRequired: "user",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 5,
    maxExpectedFirestoreReadsPerCall: 80,
    maxExpectedFirestoreWritesPerCall: 12,
    notes: "Creator subscriptions use paid-source balance and deterministic idempotency.",
  },
  {
    routePattern: "/api/creator/messages",
    methods: [...ALL_API_METHODS],
    costClass: "payment_sensitive",
    ratePolicy: "SENSITIVE_WRITE",
    cachePolicy: "no_store",
    authRequired: "user",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 20,
    maxExpectedFirestoreReadsPerCall: 80,
    maxExpectedFirestoreWritesPerCall: 12,
    notes: "Creator private messages may spend paid-source GumDrops.",
  },
  {
    routePattern: "/api/creator/**",
    methods: [...ALL_API_METHODS],
    costClass: "firestore_write",
    ratePolicy: "STANDARD / SENSITIVE_WRITE",
    cachePolicy: "no_store",
    authRequired: "user",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 20,
    maxExpectedFirestoreReadsPerCall: 80,
    maxExpectedFirestoreWritesPerCall: 12,
    notes: "Default creator API contract; creator state changes must be user-scoped, trusted-origin, and rate limited.",
  },
  {
    routePattern: "/api/creators/**",
    methods: ["GET"],
    costClass: "firestore_read",
    ratePolicy: "RELAXED",
    cachePolicy: "swr",
    authRequired: "none",
    trustedOriginRequired: false,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 60,
    maxExpectedFirestoreReadsPerCall: 40,
    notes: "Public creator profile data must be sanitized and bounded.",
  },
  {
    routePattern: "/api/cron/**",
    methods: [...ALL_API_METHODS],
    costClass: "cloud_run_compute",
    ratePolicy: "CRON",
    cachePolicy: "no_store",
    authRequired: "none",
    trustedOriginRequired: false,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 6,
    maxExpectedFirestoreReadsPerCall: 500,
    maxExpectedFirestoreWritesPerCall: 500,
    notes: "Cron endpoints are explicitly exempt from trusted-origin because they use cron secret/request verification. Batches must stay bounded.",
  },
  {
    routePattern: "/api/debug/evidence",
    methods: ["POST"],
    costClass: "firestore_write",
    ratePolicy: "ANALYTICS_WRITE",
    cachePolicy: "no_store",
    authRequired: "none",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 30,
    maxExpectedFirestoreWritesPerCall: 2,
    notes: "Client debug evidence ingest must be same-origin, redacted, and non-blocking.",
  },
  {
    routePattern: "/api/drops/content",
    methods: ["GET"],
    costClass: "storage_egress",
    ratePolicy: "MEDIA_PROXY",
    cachePolicy: "no_store",
    authRequired: "user",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 15,
    maxExpectedStorageBytesPerCall: 50_000_000,
    notes: "Unlocked media proxy must enforce entitlement, range-aware rate limiting, no-store cache, and raw URL hiding.",
  },
  {
    routePattern: "/api/drops/unlock",
    methods: ["POST"],
    costClass: "payment_sensitive",
    ratePolicy: "SENSITIVE_WRITE",
    cachePolicy: "no_store",
    authRequired: "user",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 3,
    maxExpectedFirestoreReadsPerCall: 20,
    maxExpectedFirestoreWritesPerCall: 12,
    notes: "Drop unlock spends GumDrops in a Firestore transaction and must preserve idempotency.",
  },
  {
    routePattern: "/api/drops",
    methods: ["GET"],
    costClass: "firestore_read",
    ratePolicy: "RELAXED",
    cachePolicy: "swr",
    authRequired: "none",
    trustedOriginRequired: false,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 60,
    maxExpectedFirestoreReadsPerCall: 24,
    notes: "Public Drops feed uses SWR + ETag and bounded pagination.",
  },
  {
    routePattern: "/api/drops/**",
    methods: [...ALL_API_METHODS],
    costClass: "firestore_write",
    ratePolicy: "STANDARD",
    cachePolicy: "no_store",
    authRequired: "none",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 20,
    maxExpectedFirestoreReadsPerCall: 40,
    maxExpectedFirestoreWritesPerCall: 4,
    notes: "Default Drops interaction contract. Writes must be trusted-origin and bounded; normal unlock/payment surfaces have stricter contracts.",
  },
  {
    routePattern: "/api/notifications",
    methods: [...ALL_API_METHODS],
    costClass: "firestore_write",
    ratePolicy: "STANDARD",
    cachePolicy: "no_store",
    authRequired: "user",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 20,
    maxExpectedFirestoreReadsPerCall: 60,
    maxExpectedFirestoreWritesPerCall: 10,
    notes: "Notification inbox read/action state must stay user-scoped and rate limited.",
  },
  {
    routePattern: "/api/notifications/push-token",
    methods: ["POST", "DELETE"],
    costClass: "firestore_write",
    ratePolicy: "STANDARD",
    cachePolicy: "no_store",
    authRequired: "user",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 20,
    maxExpectedFirestoreReadsPerCall: 2,
    maxExpectedFirestoreWritesPerCall: 4,
    notes: "Push token registration/revocation is caller-scoped, same-origin, rate limited, and stores redacted token metadata without sending push notifications.",
  },
  {
    routePattern: "/api/paypal/**",
    methods: [...ALL_API_METHODS],
    costClass: "payment_sensitive",
    ratePolicy: "SENSITIVE_WRITE",
    cachePolicy: "no_store",
    authRequired: "user",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 3,
    maxExpectedFirestoreReadsPerCall: 20,
    maxExpectedFirestoreWritesPerCall: 12,
    notes: "PayPal routes are payment-sensitive and require trusted origin, authenticated caller, locks, and idempotent ledger writes.",
  },
  {
    routePattern: "/api/privacy/consent",
    methods: [...ALL_API_METHODS],
    costClass: "firestore_write",
    ratePolicy: "STANDARD",
    cachePolicy: "no_store",
    authRequired: "none",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 20,
    maxExpectedFirestoreWritesPerCall: 2,
    notes: "Privacy consent writes are allowed but must keep consent and telemetry truth intact.",
  },
  {
    routePattern: "/api/security/log-attempt",
    methods: [...ALL_API_METHODS],
    costClass: "firestore_write",
    ratePolicy: "ANALYTICS_WRITE",
    cachePolicy: "no_store",
    authRequired: "none",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 30,
    maxExpectedFirestoreWritesPerCall: 2,
    notes: "Security attempt logging must stay bounded and same-origin.",
  },
  {
    routePattern: "/api/settings/landing/upload",
    methods: [...ALL_API_METHODS],
    costClass: "storage_egress",
    ratePolicy: "ADMIN",
    cachePolicy: "no_store",
    authRequired: "admin",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 30,
    maxExpectedStorageBytesPerCall: 10_000_000,
    notes: "Admin landing asset upload must stay admin-only and bounded.",
  },
  {
    routePattern: "/api/settings/landing",
    methods: [...ALL_API_METHODS],
    costClass: "firestore_read",
    ratePolicy: "RELAXED",
    cachePolicy: "swr",
    authRequired: "none",
    trustedOriginRequired: false,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 60,
    maxExpectedFirestoreReadsPerCall: 8,
    notes: "Public landing settings are low-cost reads and should stay cached/bounded.",
  },
  {
    routePattern: "/api/support/**",
    methods: [...ALL_API_METHODS],
    costClass: "support_admin",
    ratePolicy: "STANDARD / SENSITIVE_WRITE",
    cachePolicy: "no_store",
    authRequired: "user",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 20,
    maxExpectedFirestoreReadsPerCall: 60,
    maxExpectedFirestoreWritesPerCall: 10,
    notes: "Support routes must keep users scoped to their own threads and nested messages; guest entry stays same-origin and bounded.",
  },
  {
    routePattern: "/api/tasks/**",
    methods: [...ALL_API_METHODS],
    costClass: "firestore_write",
    ratePolicy: "STANDARD",
    cachePolicy: "no_store",
    authRequired: "user",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 20,
    maxExpectedFirestoreReadsPerCall: 50,
    maxExpectedFirestoreWritesPerCall: 8,
    notes: "Tasks/reminders/feedback writes must stay user-scoped and bounded.",
  },
  {
    routePattern: "/api/user/check-username",
    methods: [...ALL_API_METHODS],
    costClass: "firestore_read",
    ratePolicy: "STANDARD",
    cachePolicy: "no_store",
    authRequired: "none",
    trustedOriginRequired: false,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 20,
    maxExpectedFirestoreReadsPerCall: 8,
    notes: "Public username availability lookup must stay rate limited and bounded.",
  },
  {
    routePattern: "/api/user/**",
    methods: [...ALL_API_METHODS],
    costClass: "firestore_write",
    ratePolicy: "STANDARD / SENSITIVE_WRITE",
    cachePolicy: "no_store",
    authRequired: "user",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 20,
    maxExpectedFirestoreReadsPerCall: 50,
    maxExpectedFirestoreWritesPerCall: 10,
    notes: "User profile/activity routes must stay caller-scoped, trusted-origin for mutations, and rate limited.",
  },
  {
    routePattern: "/api/viewer/**",
    methods: [...ALL_API_METHODS],
    costClass: "firestore_write",
    ratePolicy: "STANDARD",
    cachePolicy: "no_store",
    authRequired: "none",
    trustedOriginRequired: true,
    budgetGuardRequired: true,
    maxExpectedCallsPerUserPerMinute: 20,
    maxExpectedFirestoreWritesPerCall: 6,
    notes: "Viewer watch telemetry writes must stay bounded and must not reveal locked content.",
  },
] as const satisfies ApiCostContract[];

function routePatternToRegExp(pattern: string) {
  const deepWildcardPlaceholder = "__KD_DEEP_WILDCARD__";
  const escaped = pattern
    .replace(/\*\*/g, deepWildcardPlaceholder)
    .replace(/[.+?^${}()|[\]\\]/g, "\\$&")
    .replace(/\*/g, "[^/]*")
    .replaceAll(deepWildcardPlaceholder, ".*");
  return new RegExp(`^${escaped}$`);
}

function patternSpecificity(pattern: string) {
  return pattern.replace(/\*\*/g, "").replace(/\*/g, "").length;
}

export function matchApiCostContract(routePath: string) {
  return [...API_COST_CONTRACTS]
    .sort((left, right) => patternSpecificity(right.routePattern) - patternSpecificity(left.routePattern))
    .find((contract) => routePatternToRegExp(contract.routePattern).test(routePath)) ?? null;
}
