import "server-only";

import type { CreatorDiscoveryProfile } from "@/lib/creator-public-pages";
import type { Drop } from "@/types/db";

const LOCAL_PREVIEW_SOURCE = "local_preview_fixture";

/**
 * Local-preview-only public discovery data. These records intentionally contain
 * no protected media URLs, private creator data, or provider-backed values.
 */
export const PUBLIC_DISCOVERY_PREVIEW_DROPS: Drop[] = [
    {
        id: "local-preview-cherry-static",
        creatorId: "local-preview-mira-neon",
        title: "Cherry Static Afterglow",
        description: "Local preview fixture for a live public Drop card. Its protected media remains sealed until a real unlock flow is available.",
        imageUrl: "/candy-3d-glass.png",
        contentUrl: "",
        contentUrls: [],
        unlockCost: 140,
        validFrom: 1_704_067_200_000,
        validUntil: 1_893_456_000_000,
        status: "active",
        approvalStatus: "approved",
        createdByRole: "creator",
        sourceTruth: LOCAL_PREVIEW_SOURCE,
        publicDiscovery: true,
        rotationEligibility: true,
        totalUnlocks: 48,
        totalViews: 314,
        createdAt: 1_704_067_200_000,
        type: "content",
        ctaText: "Unwrap your KandyDrops",
        accentColor: "#f472b6",
        tags: ["Preview", "Cherry", "Late night"],
    },
    {
        id: "local-preview-sugar-forecast",
        creatorId: "local-preview-aria-glow",
        title: "Sugar Forecast: Golden Hour",
        description: "A bright local preview fixture with public card metadata only. No files or internal preview content are included.",
        imageUrl: "/candy-main.svg",
        contentUrl: "",
        contentUrls: [],
        unlockCost: 90,
        validFrom: 1_704_153_600_000,
        validUntil: 1_893_542_400_000,
        status: "active",
        approvalStatus: "approved",
        createdByRole: "creator",
        sourceTruth: LOCAL_PREVIEW_SOURCE,
        publicDiscovery: true,
        rotationEligibility: true,
        totalUnlocks: 27,
        totalViews: 182,
        createdAt: 1_704_153_600_000,
        type: "content",
        ctaText: "Unwrap your KandyDrops",
        accentColor: "#facc15",
        tags: ["Preview", "Golden hour", "Fresh"],
    },
    {
        id: "local-preview-lemon-loop",
        creatorId: "local-preview-zoe-signal",
        title: "Midnight Lemon Loop",
        description: "A longer title fixture for rail and card truncation. The visible cover is public, while all internal content remains absent from this module.",
        imageUrl: "/candy-3d-glass.png",
        contentUrl: "",
        contentUrls: [],
        unlockCost: 220,
        validFrom: 1_704_240_000_000,
        validUntil: 1_893_628_800_000,
        status: "active",
        approvalStatus: "approved",
        createdByRole: "creator",
        sourceTruth: LOCAL_PREVIEW_SOURCE,
        publicDiscovery: true,
        rotationEligibility: true,
        totalUnlocks: 63,
        totalViews: 407,
        createdAt: 1_704_240_000_000,
        type: "content",
        ctaText: "Unwrap your KandyDrops",
        accentColor: "#a3e635",
        tags: ["Preview", "Citrus", "Live"],
    },
    {
        id: "local-preview-velvet-peach",
        creatorId: "local-preview-nova-sugar",
        title: "Velvet Peach Signal",
        description: "A soft-toned local preview fixture for public discovery layouts, with safe text and a local cover only.",
        imageUrl: "/candy-main.svg",
        contentUrl: "",
        contentUrls: [],
        unlockCost: 175,
        validFrom: 1_704_326_400_000,
        validUntil: 1_893_715_200_000,
        status: "active",
        approvalStatus: "approved",
        createdByRole: "creator",
        sourceTruth: LOCAL_PREVIEW_SOURCE,
        publicDiscovery: true,
        rotationEligibility: true,
        totalUnlocks: 35,
        totalViews: 251,
        createdAt: 1_704_326_400_000,
        type: "content",
        ctaText: "Unwrap your KandyDrops",
        accentColor: "#c084fc",
        tags: ["Preview", "Peach", "Spotlight"],
    },
];

/**
 * Local-preview-only creator discovery records paired with the fixture Drops.
 * Photo URLs point only to public local brand assets.
 */
export const PUBLIC_DISCOVERY_PREVIEW_CREATORS: CreatorDiscoveryProfile[] = [
    {
        uid: "local-preview-mira-neon",
        displayName: "Mira Neon",
        username: "mira-neon",
        photoURL: "/candy-3d-glass.png",
        bio: "After-dark color studies and slow-burn Drop moments for local preview.",
        isVerified: true,
        activeDropCount: 1,
        followerCount: 1280,
        notificationsEnabledCount: 164,
    },
    {
        uid: "local-preview-aria-glow",
        displayName: "Aria Glow",
        username: "aria-glow",
        photoURL: "/candy-main.svg",
        bio: "Golden-hour sweetness, small rituals, and bright public card samples.",
        isVerified: true,
        activeDropCount: 1,
        followerCount: 936,
        notificationsEnabledCount: 121,
    },
    {
        uid: "local-preview-zoe-signal",
        displayName: "Zoe Signal",
        username: "zoe-signal",
        photoURL: "/candy-3d-glass.png",
        bio: "Citrus-tinted late-night releases for deterministic local discovery rails.",
        isVerified: false,
        activeDropCount: 1,
        followerCount: 742,
        notificationsEnabledCount: 87,
    },
    {
        uid: "local-preview-nova-sugar",
        displayName: "Nova Sugar",
        username: "nova-sugar",
        photoURL: "/candy-main.svg",
        bio: "Soft color, quiet glamour, and public-safe preview worlds.",
        isVerified: true,
        activeDropCount: 1,
        followerCount: 1104,
        notificationsEnabledCount: 149,
    },
];
