export const SECURITY_AUTH_LEVELS = ["none", "user", "admin", "cron", "webhook"] as const;
export const SECURITY_RATE_POLICIES = [
  "none",
  "strict",
  "standard",
  "relaxed",
  "admin",
  "sensitive_write",
  "heavy_read",
  "analytics_write",
  "media_proxy",
  "cron",
  "ai_budgeted",
] as const;

export type SecurityAuthRequired = (typeof SECURITY_AUTH_LEVELS)[number];
export type SecurityRateLimitPolicy = (typeof SECURITY_RATE_POLICIES)[number];
export type SecurityCsrfRisk = "none" | "low" | "medium" | "high";
export type SecurityCostRisk = "low" | "medium" | "high" | "critical";

export type SecurityRouteContract = {
  routePattern: string;
  methods: string[];
  authRequired: SecurityAuthRequired;
  trustedOriginRequired: boolean;
  appCheckRecommended: boolean;
  rateLimitPolicy: SecurityRateLimitPolicy;
  bodyLimitBytes?: number;
  idempotencyRequired: boolean;
  csrfRisk: SecurityCsrfRisk;
  costRisk: SecurityCostRisk;
  sensitiveWrites: boolean;
  expectedFailureCodes: string[];
};

export type AppCheckReadinessContract = {
  enabledClientSide: boolean;
  sendsTokenToCustomBackend: boolean;
  serverVerifiesToken: boolean;
  enforcementMode: "off" | "monitor" | "enforce";
  protectedSurfaces: string[];
  rolloutNotes: string;
};

export const APP_CHECK_READINESS_CONTRACT: AppCheckReadinessContract = {
  enabledClientSide: false,
  sendsTokenToCustomBackend: false,
  serverVerifiesToken: false,
  enforcementMode: "off",
  protectedSurfaces: [
    "/api/analytics/**",
    "/api/debug/evidence",
    "/api/drops/unlock",
    "/api/chat/**",
    "/api/support/**",
    "/api/creator/**",
    "/api/drops/content",
  ],
  rolloutNotes:
    "Current source contract records App Check as readiness-only. Roll out monitor mode first, verify real traffic, then enforce high-abuse custom backend routes without breaking PayPal webhooks or cron routes.",
};

export const SECURITY_ROUTE_CONTRACTS: SecurityRouteContract[] = [
  {
    routePattern: "/api/health",
    methods: ["GET"],
    authRequired: "none",
    trustedOriginRequired: false,
    appCheckRecommended: false,
    rateLimitPolicy: "none",
    idempotencyRequired: false,
    csrfRisk: "none",
    costRisk: "low",
    sensitiveWrites: false,
    expectedFailureCodes: [],
  },
  {
    routePattern: "/api/wallet/packages",
    methods: ["GET"],
    authRequired: "none",
    trustedOriginRequired: false,
    appCheckRecommended: false,
    rateLimitPolicy: "relaxed",
    idempotencyRequired: false,
    csrfRisk: "none",
    costRisk: "low",
    sensitiveWrites: false,
    expectedFailureCodes: ["invalid_method"],
  },
  {
    routePattern: "/api/drops",
    methods: ["GET"],
    authRequired: "none",
    trustedOriginRequired: false,
    appCheckRecommended: true,
    rateLimitPolicy: "relaxed",
    idempotencyRequired: false,
    csrfRisk: "none",
    costRisk: "medium",
    sensitiveWrites: false,
    expectedFailureCodes: ["invalid_query"],
  },
  {
    routePattern: "/api/drops/unlock",
    methods: ["POST"],
    authRequired: "user",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "sensitive_write",
    bodyLimitBytes: 12_288,
    idempotencyRequired: true,
    csrfRisk: "high",
    costRisk: "critical",
    sensitiveWrites: true,
    expectedFailureCodes: ["unauthorized", "drop_not_found", "already_unlocked", "insufficient_gumdrops", "invalid_unlock_request"],
  },
  {
    routePattern: "/api/drops/content",
    methods: ["GET"],
    authRequired: "user",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "media_proxy",
    idempotencyRequired: false,
    csrfRisk: "medium",
    costRisk: "critical",
    sensitiveWrites: false,
    expectedFailureCodes: ["unauthorized", "forbidden", "drop_not_unlocked", "content_not_found"],
  },
  {
    routePattern: "/api/drops/**",
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE"],
    authRequired: "none",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "standard",
    bodyLimitBytes: 32_768,
    idempotencyRequired: false,
    csrfRisk: "medium",
    costRisk: "medium",
    sensitiveWrites: true,
    expectedFailureCodes: ["unauthorized", "forbidden", "invalid_drop_request"],
  },
  {
    routePattern: "/api/creator/discovery",
    methods: ["GET"],
    authRequired: "none",
    trustedOriginRequired: false,
    appCheckRecommended: true,
    rateLimitPolicy: "relaxed",
    idempotencyRequired: false,
    csrfRisk: "none",
    costRisk: "medium",
    sensitiveWrites: false,
    expectedFailureCodes: ["invalid_query"],
  },
  {
    routePattern: "/api/creators/**",
    methods: ["GET"],
    authRequired: "none",
    trustedOriginRequired: false,
    appCheckRecommended: true,
    rateLimitPolicy: "relaxed",
    idempotencyRequired: false,
    csrfRisk: "none",
    costRisk: "medium",
    sensitiveWrites: false,
    expectedFailureCodes: ["creator_not_found", "creator_unavailable"],
  },
  {
    routePattern: "/api/creator/bookings",
    methods: ["POST"],
    authRequired: "user",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "sensitive_write",
    bodyLimitBytes: 32_768,
    idempotencyRequired: true,
    csrfRisk: "high",
    costRisk: "critical",
    sensitiveWrites: true,
    expectedFailureCodes: [
      "unauthorized",
      "creator_or_user_not_found",
      "creator_unavailable",
      "bookings_unavailable",
      "creator_availability_not_configured",
      "slot_outside_availability",
      "slot_already_booked",
      "insufficient_paid_gumdrops",
      "invalid_booking_request",
    ],
  },
  {
    routePattern: "/api/creator/subscriptions",
    methods: ["POST", "DELETE"],
    authRequired: "user",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "sensitive_write",
    bodyLimitBytes: 32_768,
    idempotencyRequired: true,
    csrfRisk: "high",
    costRisk: "critical",
    sensitiveWrites: true,
    expectedFailureCodes: [
      "unauthorized",
      "creator_or_user_not_found",
      "creator_unavailable",
      "subscriptions_unavailable",
      "insufficient_paid_gumdrops",
      "already_active",
      "invalid_subscription_request",
    ],
  },
  {
    routePattern: "/api/creator/requests",
    methods: ["POST"],
    authRequired: "user",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "sensitive_write",
    bodyLimitBytes: 32_768,
    idempotencyRequired: true,
    csrfRisk: "high",
    costRisk: "critical",
    sensitiveWrites: true,
    expectedFailureCodes: ["unauthorized", "creator_unavailable", "requests_unavailable", "insufficient_paid_gumdrops", "invalid_request"],
  },
  {
    routePattern: "/api/creator/**",
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE"],
    authRequired: "user",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "standard",
    bodyLimitBytes: 32_768,
    idempotencyRequired: false,
    csrfRisk: "medium",
    costRisk: "high",
    sensitiveWrites: true,
    expectedFailureCodes: ["unauthorized", "forbidden", "invalid_creator_request"],
  },
  {
    routePattern: "/api/chat/**",
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE"],
    authRequired: "user",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "sensitive_write",
    bodyLimitBytes: 64_000,
    idempotencyRequired: true,
    csrfRisk: "high",
    costRisk: "critical",
    sensitiveWrites: true,
    expectedFailureCodes: ["unauthorized", "forbidden", "insufficient_paid_gumdrops", "thread_not_found", "invalid_chat_request"],
  },
  {
    routePattern: "/api/support/**",
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE"],
    authRequired: "user",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "sensitive_write",
    bodyLimitBytes: 64_000,
    idempotencyRequired: false,
    csrfRisk: "high",
    costRisk: "medium",
    sensitiveWrites: true,
    expectedFailureCodes: ["unauthorized", "forbidden", "thread_not_found", "invalid_support_request", "support_permission_denied"],
  },
  {
    routePattern: "/api/admin/ai/**",
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE"],
    authRequired: "admin",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "ai_budgeted",
    bodyLimitBytes: 128_000,
    idempotencyRequired: false,
    csrfRisk: "high",
    costRisk: "critical",
    sensitiveWrites: true,
    expectedFailureCodes: ["unauthorized", "forbidden", "ai_disabled", "budget_exceeded", "invalid_ai_request"],
  },
  {
    routePattern: "/api/admin/analytics/**",
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE"],
    authRequired: "admin",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "heavy_read",
    bodyLimitBytes: 64_000,
    idempotencyRequired: false,
    csrfRisk: "high",
    costRisk: "high",
    sensitiveWrites: true,
    expectedFailureCodes: ["unauthorized", "forbidden", "quota_exceeded", "analytics_unavailable"],
  },
  {
    routePattern: "/api/admin/support/**",
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE"],
    authRequired: "admin",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "admin",
    bodyLimitBytes: 64_000,
    idempotencyRequired: false,
    csrfRisk: "high",
    costRisk: "medium",
    sensitiveWrites: true,
    expectedFailureCodes: ["unauthorized", "forbidden", "thread_not_found", "support_permission_denied"],
  },
  {
    routePattern: "/api/admin/content",
    methods: ["GET", "POST", "DELETE"],
    authRequired: "admin",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "media_proxy",
    bodyLimitBytes: 262_144_000,
    idempotencyRequired: false,
    csrfRisk: "high",
    costRisk: "critical",
    sensitiveWrites: true,
    expectedFailureCodes: [
      "unauthorized",
      "forbidden",
      "invalid_file",
      "file_too_large",
      "invalid_content_type",
      "invalid_storage_path",
      "storage_bucket_unavailable",
      "upload_failed",
      "invalid_storage_reference",
      "file_not_found",
    ],
  },
  {
    routePattern: "/api/admin/**",
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE"],
    authRequired: "admin",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "admin",
    bodyLimitBytes: 64_000,
    idempotencyRequired: false,
    csrfRisk: "high",
    costRisk: "high",
    sensitiveWrites: true,
    expectedFailureCodes: ["unauthorized", "forbidden", "invalid_admin_request"],
  },
  {
    routePattern: "/api/analytics/**",
    methods: ["POST"],
    authRequired: "none",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "analytics_write",
    bodyLimitBytes: 64_000,
    idempotencyRequired: false,
    csrfRisk: "medium",
    costRisk: "medium",
    sensitiveWrites: true,
    expectedFailureCodes: ["consent_denied", "invalid_analytics_payload", "payload_too_large"],
  },
  {
    routePattern: "/api/debug/evidence",
    methods: ["POST"],
    authRequired: "none",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "analytics_write",
    bodyLimitBytes: 64_000,
    idempotencyRequired: false,
    csrfRisk: "medium",
    costRisk: "medium",
    sensitiveWrites: true,
    expectedFailureCodes: ["invalid_debug_evidence", "payload_too_large"],
  },
  {
    routePattern: "/api/paypal/webhook/**",
    methods: ["POST"],
    authRequired: "webhook",
    trustedOriginRequired: false,
    appCheckRecommended: false,
    rateLimitPolicy: "strict",
    bodyLimitBytes: 256_000,
    idempotencyRequired: true,
    csrfRisk: "none",
    costRisk: "critical",
    sensitiveWrites: true,
    expectedFailureCodes: ["invalid_signature", "duplicate_event", "invalid_webhook_payload"],
  },
  {
    routePattern: "/api/paypal/**",
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE"],
    authRequired: "user",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "sensitive_write",
    bodyLimitBytes: 32_768,
    idempotencyRequired: true,
    csrfRisk: "high",
    costRisk: "critical",
    sensitiveWrites: true,
    expectedFailureCodes: ["unauthorized", "payment_failed", "duplicate_transaction", "invalid_payment_request"],
  },
  {
    routePattern: "/api/privacy/consent",
    methods: ["POST", "GET"],
    authRequired: "none",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "standard",
    bodyLimitBytes: 16_384,
    idempotencyRequired: false,
    csrfRisk: "medium",
    costRisk: "low",
    sensitiveWrites: true,
    expectedFailureCodes: ["invalid_consent_request"],
  },
  {
    routePattern: "/api/security/log-attempt",
    methods: ["POST"],
    authRequired: "none",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "analytics_write",
    bodyLimitBytes: 16_384,
    idempotencyRequired: false,
    csrfRisk: "medium",
    costRisk: "low",
    sensitiveWrites: true,
    expectedFailureCodes: ["invalid_security_event"],
  },
  {
    routePattern: "/api/notifications",
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE"],
    authRequired: "user",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "standard",
    bodyLimitBytes: 32_768,
    idempotencyRequired: false,
    csrfRisk: "medium",
    costRisk: "medium",
    sensitiveWrites: true,
    expectedFailureCodes: ["unauthorized", "notification_not_found", "invalid_notification_request"],
  },
  {
    routePattern: "/api/user/check-username",
    methods: ["GET"],
    authRequired: "none",
    trustedOriginRequired: false,
    appCheckRecommended: true,
    rateLimitPolicy: "standard",
    idempotencyRequired: false,
    csrfRisk: "none",
    costRisk: "medium",
    sensitiveWrites: false,
    expectedFailureCodes: ["invalid_username"],
  },
  {
    routePattern: "/api/user/**",
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE"],
    authRequired: "user",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "standard",
    bodyLimitBytes: 32_768,
    idempotencyRequired: false,
    csrfRisk: "medium",
    costRisk: "medium",
    sensitiveWrites: true,
    expectedFailureCodes: ["unauthorized", "forbidden", "invalid_user_request"],
  },
  {
    routePattern: "/api/cron/**",
    methods: ["GET", "POST"],
    authRequired: "cron",
    trustedOriginRequired: false,
    appCheckRecommended: false,
    rateLimitPolicy: "cron",
    bodyLimitBytes: 64_000,
    idempotencyRequired: true,
    csrfRisk: "none",
    costRisk: "high",
    sensitiveWrites: true,
    expectedFailureCodes: ["unauthorized", "invalid_cron_secret", "job_already_running"],
  },
  {
    routePattern: "/api/viewer/**",
    methods: ["POST", "GET"],
    authRequired: "none",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "analytics_write",
    bodyLimitBytes: 64_000,
    idempotencyRequired: false,
    csrfRisk: "medium",
    costRisk: "medium",
    sensitiveWrites: true,
    expectedFailureCodes: ["consent_denied", "invalid_watch_payload", "payload_too_large"],
  },
  {
    routePattern: "/api/**",
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE"],
    authRequired: "user",
    trustedOriginRequired: true,
    appCheckRecommended: true,
    rateLimitPolicy: "standard",
    bodyLimitBytes: 32_768,
    idempotencyRequired: false,
    csrfRisk: "medium",
    costRisk: "medium",
    sensitiveWrites: true,
    expectedFailureCodes: ["unauthorized", "forbidden", "invalid_request"],
  },
] as const satisfies SecurityRouteContract[];

function routePatternToRegExp(pattern: string) {
  const deepWildcardPlaceholder = "__KD_DEEP_WILDCARD__";
  const escaped = pattern
    .replace(/\*\*/g, deepWildcardPlaceholder)
    .replace(/[.+?^${}()|[\]\\]/g, "\\$&")
    .replace(/\*/g, "[^/]*")
    .replaceAll(deepWildcardPlaceholder, ".*");
  return new RegExp(`^${escaped}$`, "u");
}

function patternSpecificity(pattern: string) {
  return pattern.replace(/\*\*/g, "").replace(/\*/g, "").length;
}

export function matchSecurityRouteContract(routePath: string) {
  return [...SECURITY_ROUTE_CONTRACTS]
    .sort((left, right) => patternSpecificity(right.routePattern) - patternSpecificity(left.routePattern))
    .find((contract) => routePatternToRegExp(contract.routePattern).test(routePath)) ?? null;
}
