import type { PublicReleaseNotesDocument } from "./release-version-contract";

export const PUBLIC_RELEASE_NOTES_FALLBACK = {
  "currentVersion": "1.5.93",
  "betaReleaseCounter": 593,
  "channel": "beta",
  "generatedAt": "2026-06-18T11:37:09.483Z",
  "generatedAtUtc": "2026-06-18T11:37:09.483Z",
  "lastCommitSha": "e6216fcf3b43ea17bac16676ec02bc1e2cba533f",
  "notes": [
    {
      "version": "1.5.93",
      "previousVersion": "1.5.92",
      "betaReleaseCounter": 593,
      "previousBetaReleaseCounter": 592,
      "commitSha": "e6216fcf3b43ea17bac16676ec02bc1e2cba533f",
      "commitTitle": "analytics: label launch recovery proof windows",
      "commitCount": 2,
      "commitShas": [
        "a6e5357dee5b27a8be25c7ec3259401f6d119d07",
        "e6216fcf3b43ea17bac16676ec02bc1e2cba533f"
      ],
      "committedAt": "2026-06-18T11:36:29.000Z",
      "generatedAt": "2026-06-18T11:37:09.481Z",
      "committedAtUtc": "2026-06-18T11:36:29.000Z",
      "generatedAtUtc": "2026-06-18T11:37:09.481Z",
      "updatedAtUtc": "2026-06-18T11:37:09.481Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and reliability improvements for chat, Beta readiness, and behind-the-scenes analytics.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved chat media sizing and message-thread scrolling.",
        "Improved guest analytics and admin truth checks behind the scenes.",
        "Updated Beta readiness evidence so stale or missing launch evidence stays visible."
      ],
      "audience": "all",
      "technicalDetails": [
        "Grouped 2 commits into one accepted patch batch."
      ],
      "affectedSurfaces": [
        "admin",
        "navigation"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/admin-surface-modal-replacement.generated.json",
        "agent/state/analytics-panel-hydration.generated.json",
        "agent/state/current-beta-exit-status.generated.json",
        "agent/state/launch-analytics-recovery.generated.json",
        "agent/state/public-beta-score.generated.json",
        "agent/state/source-agreement-failure-detail.generated.json",
        "docs/agent-truth/admin-surface-modal-replacement.md",
        "docs/agent-truth/analytics-panel-hydration.md",
        "docs/agent-truth/launch-analytics-recovery.md",
        "docs/agent-truth/source-agreement-failure-detail.md",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-admin-debug-control-tower.ts",
        "scripts/agent/validate-analytics-panel-hydration.ts",
        "src/app/admin/analytics/hooks/useAdminAnalyticsState.tsx",
        "src/components/Admin/AiDropCoverGeneratorPanel.tsx",
        "src/components/Admin/AiDropDescriptionGeneratorPanel.tsx",
        "src/components/Admin/CreateDropModal.tsx",
        "src/lib/analytics/person-metrics-hydration.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "src/lib/server/admin-analytics-historical-validation.ts",
        "src/types/admin-analytics.ts",
        "tests/unit/admin-analytics-page.spec.tsx",
        "tests/unit/admin-data-validation.spec.ts"
      ],
      "sourceCommit": "e6216fcf3b43ea17bac16676ec02bc1e2cba533f"
    },
    {
      "version": "1.5.92",
      "previousVersion": "1.5.91",
      "betaReleaseCounter": 592,
      "previousBetaReleaseCounter": 591,
      "commitSha": "dbb8b712b77473f9f9f50561ba7e8cc8e88c9a4d",
      "commitTitle": "fix(admin): simplify surface actions",
      "commitCount": 2,
      "commitShas": [
        "a369a651d2012b5dd8190eb3c2421ed5dfa37df8",
        "dbb8b712b77473f9f9f50561ba7e8cc8e88c9a4d"
      ],
      "committedAt": "2026-06-18T11:00:21.000Z",
      "generatedAt": "2026-06-18T11:12:34.826Z",
      "committedAtUtc": "2026-06-18T11:00:21.000Z",
      "generatedAtUtc": "2026-06-18T11:12:34.826Z",
      "updatedAtUtc": "2026-06-18T11:12:34.826Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and reliability improvements for chat, Beta readiness, and behind-the-scenes analytics.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved chat media sizing and message-thread scrolling.",
        "Improved guest analytics and admin truth checks behind the scenes.",
        "Updated Beta readiness evidence so stale or missing launch evidence stays visible."
      ],
      "audience": "all",
      "technicalDetails": [
        "Grouped 2 commits into one accepted patch batch."
      ],
      "affectedSurfaces": [
        "navigation"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/admin-surface-modal-replacement.generated.json",
        "agent/state/analytics-panel-hydration.generated.json",
        "agent/state/current-beta-exit-status.generated.json",
        "agent/state/launch-analytics-recovery.generated.json",
        "agent/state/public-beta-score.generated.json",
        "agent/state/source-agreement-failure-detail.generated.json",
        "docs/agent-truth/admin-surface-modal-replacement.md",
        "docs/agent-truth/analytics-panel-hydration.md",
        "docs/agent-truth/launch-analytics-recovery.md",
        "docs/agent-truth/source-agreement-failure-detail.md",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-admin-debug-control-tower.ts",
        "scripts/agent/validate-analytics-panel-hydration.ts",
        "src/components/Admin/AiDropCoverGeneratorPanel.tsx",
        "src/components/Admin/AiDropDescriptionGeneratorPanel.tsx",
        "src/components/Admin/CreateDropModal.tsx",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "src/lib/telemetry-catalog.ts"
      ],
      "sourceCommit": "dbb8b712b77473f9f9f50561ba7e8cc8e88c9a4d"
    },
    {
      "version": "1.5.91",
      "previousVersion": "1.5.90",
      "betaReleaseCounter": 591,
      "previousBetaReleaseCounter": 590,
      "commitSha": "edcc1b76f3c3f12aded0051b5cd9f4d3743bad93",
      "commitTitle": "fix(admin): simplify surface actions",
      "commitCount": 2,
      "commitShas": [
        "3e4bb6df95eb7268be35a461862114b1a8f1e562",
        "edcc1b76f3c3f12aded0051b5cd9f4d3743bad93"
      ],
      "committedAt": "2026-06-18T10:45:02.000Z",
      "generatedAt": "2026-06-18T10:45:47.559Z",
      "committedAtUtc": "2026-06-18T10:45:02.000Z",
      "generatedAtUtc": "2026-06-18T10:45:47.559Z",
      "updatedAtUtc": "2026-06-18T10:45:47.559Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and reliability improvements for chat, Beta readiness, and behind-the-scenes analytics.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved chat media sizing and message-thread scrolling.",
        "Improved guest analytics and admin truth checks behind the scenes.",
        "Updated Beta readiness evidence so stale or missing launch evidence stays visible."
      ],
      "audience": "all",
      "technicalDetails": [
        "Grouped 2 commits into one accepted patch batch."
      ],
      "affectedSurfaces": [
        "admin",
        "navigation"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/admin-surface-modal-replacement.generated.json",
        "agent/state/analytics-panel-hydration.generated.json",
        "agent/state/launch-analytics-recovery.generated.json",
        "agent/state/source-agreement-failure-detail.generated.json",
        "docs/agent-truth/admin-surface-modal-replacement.md",
        "docs/agent-truth/analytics-panel-hydration.md",
        "docs/agent-truth/launch-analytics-recovery.md",
        "docs/agent-truth/source-agreement-failure-detail.md",
        "public/kandydrops-release-notes.json",
        "src/app/admin/analytics/page.tsx",
        "src/components/Admin/CreateDropModal.tsx",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/admin-analytics-page.spec.tsx"
      ],
      "sourceCommit": "edcc1b76f3c3f12aded0051b5cd9f4d3743bad93"
    },
    {
      "version": "1.5.90",
      "previousVersion": "1.5.89",
      "betaReleaseCounter": 590,
      "previousBetaReleaseCounter": 589,
      "commitSha": "404d9037c67fdad6398e002b31985b2c31c62b12",
      "commitTitle": "fix(admin): simplify surface actions",
      "commitCount": 5,
      "commitShas": [
        "6cd20ca9ab677996e9a22af28a97e4c1177e55c0",
        "889367e7f7863e2684264003cbb4a133c63891ef",
        "76843f60d482cf7bbe05c9e5f404858fe04782aa",
        "80d1eec4ad6f6140871934d0d6effca5551188cc",
        "404d9037c67fdad6398e002b31985b2c31c62b12"
      ],
      "committedAt": "2026-06-18T10:18:19.000Z",
      "generatedAt": "2026-06-18T10:27:15.177Z",
      "committedAtUtc": "2026-06-18T10:18:19.000Z",
      "generatedAtUtc": "2026-06-18T10:27:15.177Z",
      "updatedAtUtc": "2026-06-18T10:27:15.177Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and reliability improvements for chat, Beta readiness, and behind-the-scenes analytics.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved chat media sizing and message-thread scrolling.",
        "Improved guest analytics and admin truth checks behind the scenes.",
        "Updated Beta readiness evidence so stale or missing launch evidence stays visible."
      ],
      "audience": "all",
      "technicalDetails": [
        "Grouped 5 commits into one accepted patch batch."
      ],
      "affectedSurfaces": [
        "account-onboarding",
        "admin",
        "navigation"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/admin-surface-modal-replacement.generated.json",
        "agent/state/analytics-panel-hydration.generated.json",
        "agent/state/current-beta-exit-status.generated.json",
        "agent/state/event-translation-bridge.generated.json",
        "agent/state/launch-analytics-recovery.generated.json",
        "agent/state/person-metrics-hydration.generated.json",
        "agent/state/public-beta-score.generated.json",
        "agent/state/source-agreement-failure-detail.generated.json",
        "docs/agent-truth/admin-surface-modal-replacement.md",
        "docs/agent-truth/analytics-panel-hydration.md",
        "docs/agent-truth/event-translation-bridge.md",
        "docs/agent-truth/launch-analytics-recovery.md",
        "docs/agent-truth/person-metrics-hydration.md",
        "docs/agent-truth/source-agreement-failure-detail.md",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-admin-debug-control-tower.ts",
        "scripts/agent/validate-analytics-panel-hydration.ts",
        "src/app/admin/analytics/components/AdminAnalyticsOperationsTab.tsx",
        "src/app/admin/analytics/hooks/useAdminAnalyticsState.tsx",
        "src/app/admin/analytics/page.tsx",
        "src/components/Admin/Analytics/AdminOnboardingAnalyticsModules.tsx",
        "src/lib/admin-analytics-auth-outcome-split.ts",
        "src/lib/admin-analytics-contracts.ts",
        "src/lib/admin-analytics-event-mix.ts",
        "src/lib/admin-analytics-guest-bounce-quality.ts",
        "src/lib/admin-analytics-journey-funnel.ts",
        "src/lib/admin-analytics-live-interaction-stream.ts",
        "src/lib/admin-analytics-live-pulse.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "src/lib/server/admin-analytics-historical-validation.ts",
        "src/types/admin-analytics.ts",
        "tests/unit/admin-analytics-event-mix.spec.ts",
        "tests/unit/admin-analytics-guest-bounce-quality.spec.ts",
        "tests/unit/admin-analytics-journey-funnel.spec.ts",
        "tests/unit/admin-analytics-live-interaction-stream.spec.ts",
        "tests/unit/admin-analytics-page.spec.tsx",
        "tests/unit/admin-data-validation.spec.ts",
        "tests/unit/admin-onboarding-analytics-mobile.spec.ts",
        "tests/unit/analytics-panel-hydration.spec.ts"
      ],
      "sourceCommit": "404d9037c67fdad6398e002b31985b2c31c62b12"
    },
    {
      "version": "1.5.89",
      "previousVersion": "1.5.88",
      "betaReleaseCounter": 589,
      "previousBetaReleaseCounter": 588,
      "commitSha": "12391873198f9457193476fd262075283ffa11aa",
      "commitTitle": "fix(admin): simplify surface actions",
      "commitCount": 3,
      "commitShas": [
        "b923482e963babe6db4367c780fe43df88cc8388",
        "6d8f75b9ff4f23fa9c506ec651ca264d3c387918",
        "12391873198f9457193476fd262075283ffa11aa"
      ],
      "committedAt": "2026-06-18T06:54:00.000Z",
      "generatedAt": "2026-06-18T07:00:28.928Z",
      "committedAtUtc": "2026-06-18T06:54:00.000Z",
      "generatedAtUtc": "2026-06-18T07:00:28.928Z",
      "updatedAtUtc": "2026-06-18T07:00:28.928Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and reliability improvements for chat, Beta readiness, and behind-the-scenes analytics.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved chat media sizing and message-thread scrolling.",
        "Improved guest analytics and admin truth checks behind the scenes.",
        "Updated Beta readiness evidence so stale or missing launch evidence stays visible."
      ],
      "audience": "all",
      "technicalDetails": [
        "Grouped 3 commits into one accepted patch batch."
      ],
      "affectedSurfaces": [
        "admin",
        "navigation"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/admin-surface-modal-replacement.generated.json",
        "agent/state/analytics-panel-hydration.generated.json",
        "agent/state/current-beta-exit-status.generated.json",
        "agent/state/launch-analytics-recovery.generated.json",
        "agent/state/public-beta-score.generated.json",
        "docs/agent-truth/admin-surface-modal-replacement.md",
        "docs/agent-truth/analytics-panel-hydration.md",
        "docs/agent-truth/launch-analytics-recovery.md",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-admin-debug-control-tower.ts",
        "scripts/agent/validate-analytics-panel-hydration.ts",
        "src/app/admin/debug/components/DebugControlTower.tsx",
        "src/app/admin/roster/page.tsx",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/admin-debug-control-tower-component.spec.tsx",
        "tests/unit/admin-debug-control-tower.spec.ts"
      ],
      "sourceCommit": "12391873198f9457193476fd262075283ffa11aa"
    },
    {
      "version": "1.5.88",
      "previousVersion": "1.5.87",
      "betaReleaseCounter": 588,
      "previousBetaReleaseCounter": 587,
      "commitSha": "e03a49c5ce8a670671c5b440496f8cb7bd07893f",
      "commitTitle": "fix(admin): simplify surface actions",
      "commitCount": 2,
      "commitShas": [
        "d2cbf3d54f31d5c7c8b6cd3a2ba9475f3c35f9d8",
        "e03a49c5ce8a670671c5b440496f8cb7bd07893f"
      ],
      "committedAt": "2026-06-18T05:31:53.000Z",
      "generatedAt": "2026-06-18T05:45:25.379Z",
      "committedAtUtc": "2026-06-18T05:31:53.000Z",
      "generatedAtUtc": "2026-06-18T05:45:25.379Z",
      "updatedAtUtc": "2026-06-18T05:45:25.379Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and reliability improvements for chat, Beta readiness, and behind-the-scenes analytics.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved chat media sizing and message-thread scrolling.",
        "Improved guest analytics and admin truth checks behind the scenes.",
        "Updated Beta readiness evidence so stale or missing launch evidence stays visible."
      ],
      "audience": "all",
      "technicalDetails": [
        "Grouped 2 commits into one accepted patch batch."
      ],
      "affectedSurfaces": [
        "admin",
        "navigation"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/admin-surface-modal-replacement.generated.json",
        "agent/state/analytics-panel-hydration.generated.json",
        "agent/state/current-beta-exit-status.generated.json",
        "agent/state/event-translation-bridge.generated.json",
        "agent/state/launch-analytics-recovery.generated.json",
        "agent/state/person-metrics-hydration.generated.json",
        "agent/state/public-beta-score.generated.json",
        "docs/agent-truth/admin-surface-modal-replacement.md",
        "docs/agent-truth/analytics-panel-hydration.md",
        "docs/agent-truth/event-translation-bridge.md",
        "docs/agent-truth/launch-analytics-recovery.md",
        "docs/agent-truth/person-metrics-hydration.md",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-analytics-panel-hydration.ts",
        "scripts/agent/validate-creator-monetization-readiness-lock.ts",
        "scripts/agent/validate-debug-signal-actionability.ts",
        "scripts/agent/validate-debug-signal-grouping.ts",
        "scripts/agent/validate-final-parity-telemetry-lock.ts",
        "scripts/agent/validate-media-discovery-score-lock.ts",
        "scripts/agent/validate-score-80-refresh-pass.ts",
        "src/app/admin/analytics/page.tsx",
        "src/app/admin/debug/components/DebugPanelStatusBySection.tsx",
        "src/lib/analytics/event-translation-bridge.ts",
        "src/lib/analytics/person-metrics-hydration.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/admin-analytics-page.spec.tsx"
      ],
      "sourceCommit": "e03a49c5ce8a670671c5b440496f8cb7bd07893f"
    },
    {
      "version": "1.5.87",
      "previousVersion": "1.5.86",
      "betaReleaseCounter": 587,
      "previousBetaReleaseCounter": 586,
      "commitSha": "05f05c4d3941ab1999608032c4bd72e5da6064b2",
      "commitTitle": "fix(admin): simplify surface actions",
      "commitCount": 1,
      "commitShas": [
        "05f05c4d3941ab1999608032c4bd72e5da6064b2"
      ],
      "committedAt": "2026-06-18T04:06:35.000Z",
      "generatedAt": "2026-06-18T04:21:01.560Z",
      "committedAtUtc": "2026-06-18T04:06:35.000Z",
      "generatedAtUtc": "2026-06-18T04:21:01.560Z",
      "updatedAtUtc": "2026-06-18T04:21:01.560Z",
      "category": "Fixed",
      "title": "Admin moderation review is clearer",
      "summary": "Admin moderation now separates weak evidence, missing proof, and confirmed review states more clearly.",
      "userFacingTitle": "Admin moderation review is clearer",
      "surfaceCategory": "App experience",
      "bullets": [
        "Clarified admin moderation risk states without treating weak evidence as confirmed proof.",
        "Kept missing evidence visible so review queues do not look healthier than they are."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "admin"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "docs/agent-truth/admin-moderation-real-risk.md",
        "scripts/agent/validate-admin-moderation-real-risk.ts",
        "src/components/Admin/AdminModerationConsole.tsx",
        "tests/unit/admin-moderation-console-ui.spec.ts"
      ],
      "sourceCommit": "05f05c4d3941ab1999608032c4bd72e5da6064b2"
    },
    {
      "version": "1.5.86",
      "previousVersion": "1.5.85",
      "betaReleaseCounter": 586,
      "previousBetaReleaseCounter": 585,
      "commitSha": "777e86944a2ff4de132ac4040959fd5261e84326",
      "commitTitle": "fix(admin): simplify surface actions",
      "commitCount": 3,
      "commitShas": [
        "d4184ef0ca51c45eb662489ab064016adbcf3d25",
        "9bc587e3d122a0e82a0ae7174ab247b517fc1a85",
        "777e86944a2ff4de132ac4040959fd5261e84326"
      ],
      "committedAt": "2026-06-18T02:40:58.000Z",
      "generatedAt": "2026-06-18T02:42:05.593Z",
      "committedAtUtc": "2026-06-18T02:40:58.000Z",
      "generatedAtUtc": "2026-06-18T02:42:05.593Z",
      "updatedAtUtc": "2026-06-18T02:42:05.593Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and reliability improvements for chat, Beta readiness, and behind-the-scenes analytics.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved chat media sizing and message-thread scrolling.",
        "Improved guest analytics and admin truth checks behind the scenes.",
        "Updated Beta readiness evidence so stale or missing launch evidence stays visible."
      ],
      "audience": "all",
      "technicalDetails": [
        "Grouped 3 commits into one accepted patch batch."
      ],
      "affectedSurfaces": [
        "admin",
        "navigation"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/admin-surface-modal-replacement.generated.json",
        "agent/state/analytics-panel-hydration.generated.json",
        "agent/state/current-beta-exit-status.generated.json",
        "agent/state/launch-analytics-recovery.generated.json",
        "agent/state/public-beta-score.generated.json",
        "docs/agent-truth/admin-surface-modal-replacement.md",
        "docs/agent-truth/analytics-panel-hydration.md",
        "docs/agent-truth/launch-analytics-recovery.md",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-admin-debug-control-tower.ts",
        "scripts/agent/validate-analytics-panel-hydration.ts",
        "src/app/admin/analytics/components/AdminAnalyticsOperationsTab.tsx",
        "src/app/admin/analytics/hooks/useAdminAnalyticsState.tsx",
        "src/app/admin/analytics/page.tsx",
        "src/components/Admin/CreateDropModal.tsx",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/admin-analytics-page.spec.tsx",
        "tests/unit/create-drop-modal-upload-block.spec.tsx"
      ],
      "sourceCommit": "777e86944a2ff4de132ac4040959fd5261e84326"
    },
    {
      "version": "1.5.85",
      "previousVersion": "1.5.84",
      "betaReleaseCounter": 585,
      "previousBetaReleaseCounter": 584,
      "commitSha": "470a3623e547c6f5f32d0f87ef98745c49fc7574",
      "commitTitle": "fix(admin): simplify surface actions",
      "commitCount": 1,
      "commitShas": [
        "470a3623e547c6f5f32d0f87ef98745c49fc7574"
      ],
      "committedAt": "2026-06-18T01:10:02.000Z",
      "generatedAt": "2026-06-18T01:20:18.629Z",
      "committedAtUtc": "2026-06-18T01:10:02.000Z",
      "generatedAtUtc": "2026-06-18T01:20:18.629Z",
      "updatedAtUtc": "2026-06-18T01:20:18.629Z",
      "category": "Fixed",
      "title": "Cleaner admin drop actions",
      "summary": "Admin drop actions now stay in the page by default, so admins can review and finish the task without a separate overlay.",
      "userFacingTitle": "Cleaner admin drop actions",
      "surfaceCategory": "App experience",
      "bullets": [
        "Admin drop actions open in place by default.",
        "Creator drop submission keeps its existing flow."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "admin"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/state/admin-surface-modal-replacement.generated.json",
        "docs/agent-truth/admin-surface-modal-replacement.md",
        "src/components/Admin/CreateDropModal.tsx"
      ],
      "sourceCommit": "470a3623e547c6f5f32d0f87ef98745c49fc7574"
    },
    {
      "version": "1.5.84",
      "previousVersion": "1.5.83",
      "betaReleaseCounter": 584,
      "previousBetaReleaseCounter": 583,
      "commitSha": "7c0de649892079e85dbc8884035baf6602656fcb",
      "commitTitle": "fix(admin): simplify surface actions",
      "commitCount": 2,
      "commitShas": [
        "5d2504fb030e5ef22a7e91f0f10b349297488326",
        "7c0de649892079e85dbc8884035baf6602656fcb"
      ],
      "committedAt": "2026-06-18T00:39:28.000Z",
      "generatedAt": "2026-06-18T00:41:45.267Z",
      "committedAtUtc": "2026-06-18T00:39:28.000Z",
      "generatedAtUtc": "2026-06-18T00:41:45.267Z",
      "updatedAtUtc": "2026-06-18T00:41:45.267Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and reliability improvements for chat, Beta readiness, and behind-the-scenes analytics.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved chat media sizing and message-thread scrolling.",
        "Improved guest analytics and admin truth checks behind the scenes.",
        "Updated Beta readiness evidence so stale or missing launch evidence stays visible."
      ],
      "audience": "all",
      "technicalDetails": [
        "Grouped 2 commits into one accepted patch batch."
      ],
      "affectedSurfaces": [
        "admin",
        "drops-viewer",
        "navigation"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/admin-surface-modal-replacement.generated.json",
        "agent/state/current-beta-exit-status.generated.json",
        "agent/state/public-beta-score.generated.json",
        "docs/agent-truth/admin-surface-modal-replacement.md",
        "public/kandydrops-release-notes.json",
        "src/app/admin/analytics/page.tsx",
        "src/app/admin/drops/page.tsx",
        "src/components/Admin/CreateDropModal.tsx",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/admin-analytics-page.spec.tsx",
        "tests/unit/admin-drops-fixture-boundary.spec.ts",
        "tests/unit/create-drop-modal-upload-block.spec.tsx"
      ],
      "sourceCommit": "7c0de649892079e85dbc8884035baf6602656fcb"
    },
    {
      "version": "1.5.83",
      "previousVersion": "1.5.82",
      "betaReleaseCounter": 583,
      "previousBetaReleaseCounter": 582,
      "commitSha": "29341a2449f0d25faf3caa2ed8173e33bb86415f",
      "commitTitle": "fix(admin): simplify surface actions",
      "commitCount": 1,
      "commitShas": [
        "29341a2449f0d25faf3caa2ed8173e33bb86415f"
      ],
      "committedAt": "2026-06-18T00:20:04.000Z",
      "generatedAt": "2026-06-18T00:20:36.966Z",
      "committedAtUtc": "2026-06-18T00:20:04.000Z",
      "generatedAtUtc": "2026-06-18T00:20:36.966Z",
      "updatedAtUtc": "2026-06-18T00:20:36.966Z",
      "category": "Fixed",
      "title": "Clearer Admin Analytics source status",
      "summary": "Improved Admin Analytics so source agreement, launch history recovery, and missing evidence states are easier to understand.",
      "userFacingTitle": "Clearer Admin Analytics source status",
      "surfaceCategory": "App experience",
      "bullets": [
        "Clarified when analytics history is recovered from first-party sources.",
        "Kept GA4 and legacy analytics labeled as evidence instead of product truth.",
        "Improved Admin Analytics source labels so missing data is not shown as zero."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "app"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/state/admin-surface-modal-replacement.generated.json",
        "docs/agent-truth/admin-surface-modal-replacement.md",
        "src/app/admin/analytics/page.tsx",
        "tests/unit/admin-analytics-page.spec.tsx"
      ],
      "sourceCommit": "29341a2449f0d25faf3caa2ed8173e33bb86415f"
    },
    {
      "version": "1.5.82",
      "previousVersion": "1.5.81",
      "betaReleaseCounter": 582,
      "previousBetaReleaseCounter": 581,
      "commitSha": "ed52d56375c448742f08808d67668a04cf8d577a",
      "commitTitle": "analytics: classify launch source agreement gaps",
      "commitCount": 1,
      "commitShas": [
        "ed52d56375c448742f08808d67668a04cf8d577a"
      ],
      "committedAt": "2026-06-18T00:10:16.000Z",
      "generatedAt": "2026-06-18T00:10:42.876Z",
      "committedAtUtc": "2026-06-18T00:10:16.000Z",
      "generatedAtUtc": "2026-06-18T00:10:42.876Z",
      "updatedAtUtc": "2026-06-18T00:10:42.876Z",
      "category": "Fixed",
      "title": "Clearer Admin Analytics source status",
      "summary": "Improved Admin Analytics so source agreement, launch history recovery, and missing evidence states are easier to understand.",
      "userFacingTitle": "Clearer Admin Analytics source status",
      "surfaceCategory": "App experience",
      "bullets": [
        "Clarified when analytics history is recovered from first-party sources.",
        "Kept GA4 and legacy analytics labeled as evidence instead of product truth.",
        "Improved Admin Analytics source labels so missing data is not shown as zero."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "app"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/state/analytics-panel-hydration.generated.json",
        "agent/state/event-translation-bridge.generated.json",
        "agent/state/launch-analytics-recovery.generated.json",
        "agent/state/person-metrics-hydration.generated.json",
        "docs/agent-truth/analytics-panel-hydration.md",
        "docs/agent-truth/event-translation-bridge.md",
        "docs/agent-truth/launch-analytics-recovery.md",
        "docs/agent-truth/person-metrics-hydration.md",
        "scripts/agent/validate-analytics-panel-hydration.ts",
        "src/lib/server/admin-analytics-historical-validation.ts",
        "src/types/admin-analytics.ts",
        "tests/unit/admin-data-validation.spec.ts"
      ],
      "sourceCommit": "ed52d56375c448742f08808d67668a04cf8d577a"
    },
    {
      "version": "1.5.81",
      "previousVersion": "1.5.80",
      "betaReleaseCounter": 581,
      "previousBetaReleaseCounter": 580,
      "commitSha": "baad3fda8c2c3daee290eaaf1fea4206df5ad84f",
      "commitTitle": "fix(admin): simplify surface actions",
      "commitCount": 2,
      "commitShas": [
        "df13950384a448a1868c1f295b4811fcae9f57da",
        "baad3fda8c2c3daee290eaaf1fea4206df5ad84f"
      ],
      "committedAt": "2026-06-17T23:52:49.000Z",
      "generatedAt": "2026-06-17T23:53:31.573Z",
      "committedAtUtc": "2026-06-17T23:52:49.000Z",
      "generatedAtUtc": "2026-06-17T23:53:31.573Z",
      "updatedAtUtc": "2026-06-17T23:53:31.573Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and reliability improvements for chat, Beta readiness, and behind-the-scenes analytics.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved chat media sizing and message-thread scrolling.",
        "Improved guest analytics and admin truth checks behind the scenes.",
        "Updated Beta readiness evidence so stale or missing launch evidence stays visible."
      ],
      "audience": "all",
      "technicalDetails": [
        "Grouped 2 commits into one accepted patch batch."
      ],
      "affectedSurfaces": [
        "admin",
        "drops-viewer",
        "navigation"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/admin-surface-modal-replacement.generated.json",
        "agent/state/current-beta-exit-status.generated.json",
        "agent/state/public-beta-score.generated.json",
        "docs/agent-truth/admin-surface-modal-replacement.md",
        "public/kandydrops-release-notes.json",
        "src/app/admin/analytics/page.tsx",
        "src/app/admin/drops/page.tsx",
        "src/components/Admin/AdminDropsAtGlancePanel.tsx",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/admin-analytics-page.spec.tsx"
      ],
      "sourceCommit": "baad3fda8c2c3daee290eaaf1fea4206df5ad84f"
    },
    {
      "version": "1.5.80",
      "previousVersion": "1.5.79",
      "betaReleaseCounter": 580,
      "previousBetaReleaseCounter": 579,
      "commitSha": "b4a9133d19e95e6dd8f3594c2ee4486493ce20db",
      "commitTitle": "fix(admin): simplify surface actions",
      "commitCount": 2,
      "commitShas": [
        "9d3de6c712134dd3245e5d35e53c834b0767c82c",
        "b4a9133d19e95e6dd8f3594c2ee4486493ce20db"
      ],
      "committedAt": "2026-06-17T23:35:25.000Z",
      "generatedAt": "2026-06-17T23:36:15.796Z",
      "committedAtUtc": "2026-06-17T23:35:25.000Z",
      "generatedAtUtc": "2026-06-17T23:36:15.796Z",
      "updatedAtUtc": "2026-06-17T23:36:15.796Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and reliability improvements for chat, Beta readiness, and behind-the-scenes analytics.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved chat media sizing and message-thread scrolling.",
        "Improved guest analytics and admin truth checks behind the scenes.",
        "Updated Beta readiness evidence so stale or missing launch evidence stays visible."
      ],
      "audience": "all",
      "technicalDetails": [
        "Grouped 2 commits into one accepted patch batch."
      ],
      "affectedSurfaces": [
        "admin",
        "navigation"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/admin-surface-modal-replacement.generated.json",
        "agent/state/analytics-panel-hydration.generated.json",
        "agent/state/current-beta-exit-status.generated.json",
        "agent/state/event-translation-bridge.generated.json",
        "agent/state/launch-analytics-recovery.generated.json",
        "agent/state/person-metrics-hydration.generated.json",
        "agent/state/public-beta-score.generated.json",
        "docs/agent-truth/admin-surface-modal-replacement.md",
        "docs/agent-truth/analytics-panel-hydration.md",
        "docs/agent-truth/event-translation-bridge.md",
        "docs/agent-truth/launch-analytics-recovery.md",
        "docs/agent-truth/person-metrics-hydration.md",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-analytics-panel-hydration.ts",
        "scripts/release/update-public-changelog.ts",
        "src/app/admin/analytics/hooks/useAdminAnalyticsState.tsx",
        "src/app/admin/analytics/page.tsx",
        "src/lib/analytics/event-translation-bridge.ts",
        "src/lib/analytics/person-metrics-hydration.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "src/lib/server/admin-analytics-historical-validation.ts",
        "src/types/admin-analytics.ts",
        "tests/unit/admin-analytics-page.spec.tsx",
        "tests/unit/admin-data-validation.spec.ts"
      ],
      "sourceCommit": "b4a9133d19e95e6dd8f3594c2ee4486493ce20db"
    },
    {
      "version": "1.5.79",
      "previousVersion": "1.5.78",
      "betaReleaseCounter": 579,
      "previousBetaReleaseCounter": 578,
      "commitSha": "66b3ec000ad4eb3ca531292e2d4079a065fe973c",
      "commitTitle": "analytics: normalize launch recovery sources",
      "commitCount": 1,
      "commitShas": [
        "66b3ec000ad4eb3ca531292e2d4079a065fe973c"
      ],
      "committedAt": "2026-06-17T23:11:39.000Z",
      "generatedAt": "2026-06-17T23:13:47.476Z",
      "committedAtUtc": "2026-06-17T23:11:39.000Z",
      "generatedAtUtc": "2026-06-17T23:13:47.476Z",
      "updatedAtUtc": "2026-06-17T23:13:47.476Z",
      "category": "Fixed",
      "title": "Clearer Admin Analytics source status",
      "summary": "Improved Admin Analytics so source agreement, launch history recovery, and missing evidence states are easier to understand.",
      "userFacingTitle": "Clearer Admin Analytics source status",
      "surfaceCategory": "App experience",
      "bullets": [
        "Clarified when analytics history is recovered from first-party sources.",
        "Kept GA4 and legacy analytics labeled as evidence instead of product truth.",
        "Improved Admin Analytics source labels so missing data is not shown as zero."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "app"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/state/analytics-panel-hydration.generated.json",
        "agent/state/event-translation-bridge.generated.json",
        "agent/state/launch-analytics-recovery.generated.json",
        "agent/state/person-metrics-hydration.generated.json",
        "docs/agent-truth/analytics-panel-hydration.md",
        "docs/agent-truth/event-translation-bridge.md",
        "docs/agent-truth/launch-analytics-recovery.md",
        "docs/agent-truth/person-metrics-hydration.md",
        "scripts/agent/validate-analytics-panel-hydration.ts",
        "src/app/admin/analytics/hooks/useAdminAnalyticsState.tsx",
        "src/app/admin/analytics/page.tsx",
        "src/lib/analytics/event-translation-bridge.ts",
        "src/lib/analytics/person-metrics-hydration.ts",
        "src/lib/server/admin-analytics-historical-validation.ts",
        "src/types/admin-analytics.ts",
        "tests/unit/admin-data-validation.spec.ts"
      ],
      "sourceCommit": "66b3ec000ad4eb3ca531292e2d4079a065fe973c"
    },
    {
      "version": "1.5.78",
      "previousVersion": "1.5.77",
      "betaReleaseCounter": 578,
      "previousBetaReleaseCounter": 577,
      "commitSha": "75952c946f9288778857f3dec0c77216cc4af36e",
      "commitTitle": "fix(admin): simplify surface actions",
      "commitCount": 1,
      "commitShas": [
        "75952c946f9288778857f3dec0c77216cc4af36e"
      ],
      "committedAt": "2026-06-17T22:43:02.000Z",
      "generatedAt": "2026-06-17T22:43:35.448Z",
      "committedAtUtc": "2026-06-17T22:43:02.000Z",
      "generatedAtUtc": "2026-06-17T22:43:35.448Z",
      "updatedAtUtc": "2026-06-17T22:43:35.448Z",
      "category": "Fixed",
      "title": "Improved drops and viewer reliability",
      "summary": "Bug fixes and quality-of-life improvements for drops, previews, and viewer behavior.",
      "userFacingTitle": "Improved drops and viewer reliability",
      "surfaceCategory": "Drops & viewer",
      "bullets": [
        "Improved drop and viewer reliability so usage states stay easier to understand.",
        "Reduced confusing stale or delayed states across previews and viewer surfaces."
      ],
      "audience": "users",
      "affectedSurfaces": [
        "admin",
        "drops-viewer"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/state/admin-surface-modal-replacement.generated.json",
        "docs/agent-truth/admin-surface-modal-replacement.md",
        "scripts/agent/validate-product-surface-integrity.ts",
        "scripts/agent/validate-support-recovery-flows.ts",
        "src/app/admin/drops/page.tsx",
        "src/app/admin/users/page.tsx",
        "src/components/Admin/BalanceAdjustmentModal.tsx",
        "src/components/Admin/BalanceAdjustmentPanel.tsx",
        "src/components/Admin/TransactionHistoryModal.tsx",
        "src/components/Admin/TransactionHistoryPanel.tsx",
        "tests/unit/accessibility-tap-targets.spec.ts",
        "tests/unit/admin-transaction-history-error-language.spec.ts"
      ],
      "sourceCommit": "75952c946f9288778857f3dec0c77216cc4af36e"
    },
    {
      "version": "1.5.77",
      "previousVersion": "1.5.76",
      "betaReleaseCounter": 577,
      "previousBetaReleaseCounter": 576,
      "commitSha": "3dd0a51b62ee8e07b843cd67e80b96b7347e3ee6",
      "commitTitle": "refactor(core): reduce client sprawl",
      "commitCount": 2,
      "commitShas": [
        "3c2d9ce0bccc68535242b77a466c3d077802161f",
        "3dd0a51b62ee8e07b843cd67e80b96b7347e3ee6"
      ],
      "committedAt": "2026-06-17T20:58:25.000Z",
      "generatedAt": "2026-06-17T20:59:10.208Z",
      "committedAtUtc": "2026-06-17T20:58:25.000Z",
      "generatedAtUtc": "2026-06-17T20:59:10.208Z",
      "updatedAtUtc": "2026-06-17T20:59:10.208Z",
      "category": "Improved",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and reliability improvements for chat, Beta readiness, and behind-the-scenes analytics.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved chat media sizing and message-thread scrolling.",
        "Improved guest analytics and admin truth checks behind the scenes.",
        "Updated Beta readiness evidence so stale or missing launch evidence stays visible."
      ],
      "audience": "all",
      "technicalDetails": [
        "Grouped 2 commits into one accepted patch batch."
      ],
      "affectedSurfaces": [
        "account-onboarding",
        "admin",
        "chat-support",
        "creator",
        "drops-viewer",
        "navigation",
        "notifications"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/admin-users-latency-repair.generated.json",
        "agent/state/ai-description-feedback-firestore-cleanup.generated.json",
        "agent/state/cron-route-stale-failure-classification.generated.json",
        "agent/state/debug-cockpit-batch14-cleanup.generated.json",
        "agent/state/debug-cockpit-batch21-no-sample-routes.generated.json",
        "agent/state/debug-cockpit-batch23-queue-continuity.generated.json",
        "agent/state/diagnostics-writer-status-cleanup.generated.json",
        "agent/state/dispatch-outcome-lane-cleanup.generated.json",
        "agent/state/generated-report-authority.generated.json",
        "agent/state/high-risk-no-sample-route-smoke-plan.generated.json",
        "agent/state/legacy-queue-adapter-policy.generated.json",
        "agent/state/no-sample-route-cohort-cleanup.generated.json",
        "agent/state/no-sample-route-display-cleanup.generated.json",
        "agent/state/optional-manual-legacy-route-policy.generated.json",
        "agent/state/panel-log-status-cleanup.generated.json",
        "agent/state/queue-heartbeat-evidence.generated.json",
        "agent/state/queue-runtime-continuity.generated.json",
        "agent/state/stale-route-grouping-cleanup.generated.json",
        "agent/state/tasks-rotate-runtime-repair.generated.json",
        "agent/state/user-checkin-route-error-mapping.generated.json",
        "agent/state/viewer-watch-session-error-cleanup.generated.json",
        "docs/agent-truth/admin-users-latency-repair.md",
        "docs/agent-truth/ai-description-feedback-firestore-cleanup.md",
        "docs/agent-truth/cron-route-stale-failure-classification.md",
        "docs/agent-truth/debug-cockpit-batch14-cleanup.md",
        "docs/agent-truth/debug-cockpit-batch21-no-sample-routes.md",
        "docs/agent-truth/debug-cockpit-batch23-queue-continuity.md",
        "docs/agent-truth/diagnostics-writer-status-cleanup.md",
        "docs/agent-truth/dispatch-outcome-lane-cleanup.md",
        "docs/agent-truth/high-risk-no-sample-route-smoke-plan.md",
        "docs/agent-truth/legacy-queue-adapter-policy.md",
        "docs/agent-truth/no-sample-route-cohort-cleanup.md",
        "docs/agent-truth/no-sample-route-display-cleanup.md",
        "docs/agent-truth/optional-manual-legacy-route-policy.md",
        "docs/agent-truth/panel-log-status-cleanup.md",
        "docs/agent-truth/queue-heartbeat-evidence.md",
        "docs/agent-truth/queue-runtime-continuity.md",
        "docs/agent-truth/stale-route-grouping-cleanup.md",
        "docs/agent-truth/tasks-rotate-runtime-repair.md",
        "docs/agent-truth/user-checkin-route-error-mapping.md",
        "docs/agent-truth/viewer-watch-session-error-cleanup.md",
        "public/kandydrops-release-notes.json",
        "scripts/agent/build-agent-indexes.ts",
        "scripts/agent/build-telemetry-event-manifest.ts",
        "scripts/agent/collect-signal-source-graph.ts",
        "scripts/agent/collect-signal-telemetry-graph.ts",
        "scripts/agent/optimize-doctrine-context.ts",
        "scripts/agent/plan-cloud-auth-bootstrap.ts",
        "scripts/agent/rank-signal-problems.ts",
        "scripts/agent/score-billing-spike-radar.ts",
        "scripts/agent/score-public-beta-readiness.ts",
        "scripts/agent/score-validator-authority.ts",
        "scripts/agent/tracking-runtime-surface-status-cleanup-shared.ts",
        "scripts/agent/validate-actor-target-telemetry.ts",
        "scripts/agent/validate-admin-analytics-finalization.ts",
        "scripts/agent/validate-admin-projection-analytics-exclusion.ts",
        "scripts/agent/validate-analytics-event-contract.ts",
        "scripts/agent/validate-behavioral-experiments.ts",
        "scripts/agent/validate-codex-auth-readiness.ts",
        "scripts/agent/validate-creator-broadcast-timeline-prep.ts",
        "scripts/agent/validate-creator-discovery-relationship-funnel.ts",
        "scripts/agent/validate-creator-drop-approval-shared.ts",
        "scripts/agent/validate-creator-identity-markers.ts",
        "scripts/agent/validate-creator-profile-mobile-timeline.ts",
        "scripts/agent/validate-debug-cockpit-batch35-behavior-stack.ts",
        "scripts/agent/validate-debug-control-tower-cutover.ts",
        "scripts/agent/validate-discovery-tracking-truth.ts",
        "scripts/agent/validate-doctrine-retrieval-optimizer.ts",
        "scripts/agent/validate-drop-watch-time-accuracy.ts",
        "scripts/agent/validate-event-envelope-normalization.ts",
        "scripts/agent/validate-evidence-freshness-index.ts",
        "scripts/agent/validate-existing-algorithm-refinement.ts",
        "scripts/agent/validate-experiment-rollout-registry-reconstruction.ts",
        "scripts/agent/validate-final-parity-telemetry-lock.ts",
        "scripts/agent/validate-generated-artifact-size-policy.ts",
        "scripts/agent/validate-generated-report-authority.ts",
        "scripts/agent/validate-generated-report-schema-contract.ts",
        "scripts/agent/validate-global-speed-hydration-cache.ts",
        "scripts/agent/validate-human-readable-admin-copy.ts",
        "scripts/agent/validate-identity-handoff-spine.ts",
        "scripts/agent/validate-materializers-cutover.ts",
        "scripts/agent/validate-mobile-hardcoded-css-cleanup.ts",
        "scripts/agent/validate-mobile-loading-hydration-stability.ts",
        "scripts/agent/validate-mobile-ui-scaling-doctrine.ts",
        "scripts/agent/validate-notification-pwa-score-lock.ts",
        "scripts/agent/validate-overnight-wiring-integrity.ts",
        "scripts/agent/validate-phase-one-lock.ts",
        "scripts/agent/validate-pwa-service-worker-safety.ts",
        "scripts/agent/validate-refresh-based-hot-cache.ts",
        "scripts/agent/validate-session-bounce-calculation.ts",
        "scripts/agent/validate-settings-creator-dashboard-split.ts",
        "scripts/agent/validate-sql-database-parity-cost-lock.ts",
        "scripts/agent/validate-surface-telemetry-parity.ts",
        "scripts/agent/validate-synthetic-creators-view-as.ts",
        "scripts/agent/validate-tracking-surface-coverage.ts",
        "scripts/agent/validate-user-critical-path-lock.ts",
        "scripts/agent/validate-user-journey-behavioral-intelligence.ts",
        "scripts/agent/validate-user-loading-wallet-mobile-refinement.ts",
        "scripts/agent/validate-viewer-file-tracking.ts",
        "scripts/agent/verify-codex-native-auth.ts",
        "shared/runtime/telemetry-event-manifest.js",
        "shared/runtime/telemetry-event-manifest.ts",
        "src/app/admin/analytics/components/AdminAnalyticsAudienceTab.tsx",
        "src/app/admin/analytics/components/AdminAnalyticsAudienceTab.utils.ts",
        "src/app/admin/analytics/components/AdminAnalyticsCommerceTab.tsx",
        "src/app/admin/analytics/components/AdminAnalyticsCommerceTab.utils.ts",
        "src/app/admin/analytics/components/AdminAnalyticsOperationsTab.tsx",
        "src/app/admin/analytics/components/AdminAnalyticsOperationsTab.utils.ts",
        "src/app/admin/analytics/hooks/useAdminAnalyticsState.tsx",
        "src/app/admin/analytics/loading.tsx",
        "src/app/admin/analytics/page.tsx",
        "src/app/admin/debug/components/DebugControlTower.tsx",
        "src/app/admin/debug/components/DebugTabNow.tsx",
        "src/app/admin/queue/page.tsx",
        "src/app/api/admin/creator-account-controls/route.ts",
        "src/app/api/admin/creator-agreements/route.ts",
        "src/app/api/admin/creator-fan-experience-settings/route.ts",
        "src/app/api/admin/debug/route.ts",
        "src/app/api/admin/drops/route.ts",
        "src/app/api/admin/roster/route.ts",
        "src/app/api/admin/users/route.ts",
        "src/app/api/admin/view-as-creator/route.ts",
        "src/app/api/creator/bookings/route.ts",
        "src/app/api/creator/broadcasts/route.ts",
        "src/app/api/creator/drops/route.ts",
        "src/app/api/creator/onboarding/application/route.ts",
        "src/app/api/creator/onboarding/contract-signature/route.ts",
        "src/app/api/creator/onboarding/id-submission/route.ts",
        "src/app/api/creator/onboarding/intro/route.ts",
        "src/app/api/creator/requests/route.ts",
        "src/app/api/creator/settings/route.ts",
        "src/app/api/creator/subscriptions/route.ts",
        "src/app/api/creators/[username]/route.ts",
        "src/app/api/user/register/route.ts",
        "src/app/creators/[username]/CreatorProfileClient.tsx",
        "src/app/dashboard/DashboardClient.tsx",
        "src/app/dashboard/library/LibraryClient.tsx",
        "src/components/Admin/AdminModuleVerificationCard.tsx",
        "src/components/Admin/AdminStatusBadge.tsx",
        "src/components/Creators/CreatorDashboardSettingsHub.tsx",
        "src/components/Creators/CreatorDropManager.tsx",
        "src/components/Creators/CreatorProfileTimelineFeed.tsx",
        "src/components/PurchaseModal.tsx",
        "src/components/PwaRuntimeBridge.tsx",
        "src/lib/admin-copy/admin-copy-registry.ts",
        "src/lib/admin-copy/admin-truth-copy.ts",
        "src/lib/admin-debug-summary-cards.ts",
        "src/lib/admin-debug/control-tower-truth.ts",
        "src/lib/admin/copy/admin-copy-registry.ts",
        "src/lib/admin/copy/admin-truth-copy.ts",
        "src/lib/admin/debug/control-tower-truth.ts",
        "src/lib/agent-governance/doctrine/doctrine-conflict-score.ts",
        "src/lib/agent-governance/doctrine/doctrine-context-cost.ts",
        "src/lib/agent-governance/doctrine/doctrine-coverage-score.ts",
        "src/lib/agent-governance/doctrine/doctrine-retrieval-optimizer.ts",
        "src/lib/agent-governance/generated-reports/generated-report-contract.ts",
        "src/lib/analytics/admin-analytics-loading-state.ts",
        "src/lib/analytics/admin-metric-snapshot.ts",
        "src/lib/analytics/event-envelope-builder.ts",
        "src/lib/analytics/event-translation-bridge.ts",
        "src/lib/analytics/materializers/materializer-contract.ts",
        "src/lib/analytics/materializers/materializer-source-policy.ts",
        "src/lib/analytics/person-metrics-hydration.ts",
        "src/lib/analytics/telemetry/surface-telemetry-catalog-events.ts",
        "src/lib/analytics/telemetry/surface-telemetry-contract.ts",
        "src/lib/analytics/telemetry/surface-telemetry-registry.ts",
        "src/lib/cache/refresh-cache-contract.ts",
        "src/lib/config-hardening/devops/auth-surface-contract.ts",
        "src/lib/cost/billing-spike-contract.ts",
        "src/lib/creator-broadcasts/broadcast-contract.ts",
        "src/lib/creator-dashboard/creator-settings-contract.ts",
        "src/lib/creator-dashboard/creator-settings-legacy-registry.ts",
        "src/lib/creator-drops/creator-drop-4xx-policy.ts",
        "src/lib/creator-drops/creator-drop-workflow-contract.ts",
        "src/lib/creator-features/creator-feature-parity-map.ts",
        "src/lib/creator-onboarding.ts",
        "src/lib/creator-profile-routing.ts",
        "src/lib/creator-profile/timeline-contract.ts",
        "src/lib/creator/broadcasts/broadcast-contract.ts",
        "src/lib/creator/dashboard/creator-settings-contract.ts",
        "src/lib/creator/dashboard/creator-settings-legacy-registry.ts",
        "src/lib/creator/drops/creator-drop-4xx-policy.ts",
        "src/lib/creator/drops/creator-drop-workflow-contract.ts",
        "src/lib/creator/features/creator-feature-parity-map.ts",
        "src/lib/creator/profile/timeline-contract.ts",
        "src/lib/debug/debug-panel-tracking-summary.ts",
        "src/lib/debug/recovery-playbooks.ts",
        "src/lib/devops/auth-surface-contract.ts",
        "src/lib/doctrine/doctrine-conflict-score.ts",
        "src/lib/doctrine/doctrine-context-cost.ts",
        "src/lib/doctrine/doctrine-coverage-score.ts",
        "src/lib/doctrine/doctrine-retrieval-optimizer.ts",
        "src/lib/evidence/ui-visual-smoke-contract.ts",
        "src/lib/experiments/behavioral-experiment-contract.ts",
        "src/lib/experiments/experiment-assignment.ts",
        "src/lib/experiments/experiment-rollout-registry-contract.ts",
        "src/lib/experiments/experiment-rollout-registry-status.ts",
        "src/lib/features/experiments/behavioral-experiment-contract.ts",
        "src/lib/features/experiments/experiment-assignment.ts",
        "src/lib/features/experiments/experiment-rollout-registry-contract.ts",
        "src/lib/features/experiments/experiment-rollout-registry-status.ts",
        "src/lib/features/pwa/pwa-service-worker-contract.ts",
        "src/lib/features/pwa/pwa-update-telemetry.ts",
        "src/lib/frontend-hardening/ui/loading-state-contract.ts",
        "src/lib/frontend-hardening/ui/mobile-scale-contract.ts",
        "src/lib/generated-reports/generated-report-contract.ts",
        "src/lib/identity-truth/identity/actor-markers.ts",
        "src/lib/identity/actor-markers.ts",
        "src/lib/legacy/legacy-registry.ts",
        "src/lib/materializers/materializer-contract.ts",
        "src/lib/materializers/materializer-source-policy.ts",
        "src/lib/notifications/creator-broadcast-notifications.ts",
        "src/lib/parity/role-permission-resolver.ts",
        "src/lib/parity/surface-state-resolver.ts",
        "src/lib/pwa/pwa-service-worker-contract.ts",
        "src/lib/pwa/pwa-update-telemetry.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "src/lib/release-readiness/automated-truth-reconciliation.ts",
        "src/lib/runtime/cache/refresh-cache-contract.ts",
        "src/lib/server/admin-analytics-materializers.ts",
        "src/lib/server/admin-debug-control-tower-loader.ts",
        "src/lib/server/chat.ts",
        "src/lib/server/creator-admin-actions.ts",
        "src/lib/server/creator-experiences.ts",
        "src/lib/server/creator-onboarding.ts",
        "src/lib/settings/settings-surface-policy.ts",
        "src/lib/telemetry-catalog.ts",
        "src/lib/telemetry/surface-telemetry-catalog-events.ts",
        "src/lib/telemetry/surface-telemetry-contract.ts",
        "src/lib/telemetry/surface-telemetry-registry.ts",
        "src/lib/test-hardening/generated-artifact-size-policy.ts",
        "src/lib/type-hardening/canonical-type-owner-map.ts",
        "src/lib/type-hardening/generated-report-schema-contract.ts",
        "src/lib/ui/loading-state-contract.ts",
        "src/lib/ui/mobile-scale-contract.ts",
        "tests/unit/actor-markers.spec.ts",
        "tests/unit/admin-truth-copy.spec.ts",
        "tests/unit/creator-broadcast-timeline-prep.spec.ts",
        "tests/unit/creator-drop-4xx-policy.spec.ts",
        "tests/unit/creator-drop-workflow-contract.spec.ts",
        "tests/unit/creator-feature-parity-map.spec.ts",
        "tests/unit/creator-profile-mobile-timeline.spec.ts",
        "tests/unit/creator-settings-route.spec.ts",
        "tests/unit/debug-cockpit-batch35-behavior-stack.spec.ts",
        "tests/unit/existing-algorithm-refinement.spec.ts",
        "tests/unit/experiment-rollout-registry-reconstruction.spec.ts",
        "tests/unit/final-parity-telemetry-lock.spec.ts",
        "tests/unit/functions-callable-telemetry-catalog-guard.spec.ts",
        "tests/unit/generated-report-contract.spec.ts",
        "tests/unit/mobile-loading-hydration-stability.spec.ts",
        "tests/unit/mobile-ui-scaling-doctrine.spec.ts",
        "tests/unit/pwa-service-worker-safety.spec.ts",
        "tests/unit/pwa-service-worker-status-cleanup.spec.ts",
        "tests/unit/refresh-cache-contract.spec.ts",
        "tests/unit/signal-telemetry-graph.spec.ts",
        "tests/unit/surface-state-parity.spec.ts",
        "tests/unit/surface-telemetry-parity.spec.ts"
      ],
      "sourceCommit": "3dd0a51b62ee8e07b843cd67e80b96b7347e3ee6"
    },
    {
      "version": "1.5.76",
      "previousVersion": "1.5.75",
      "betaReleaseCounter": 576,
      "previousBetaReleaseCounter": 575,
      "commitSha": "081b3ad329ff835f8aeb54d68ce26c646aa7f723",
      "commitTitle": "fix(analytics): gut admin truth sprawl",
      "commitCount": 1,
      "commitShas": [
        "081b3ad329ff835f8aeb54d68ce26c646aa7f723"
      ],
      "committedAt": "2026-06-17T20:11:27.000Z",
      "generatedAt": "2026-06-17T20:24:07.252Z",
      "committedAtUtc": "2026-06-17T20:11:27.000Z",
      "generatedAtUtc": "2026-06-17T20:24:07.252Z",
      "updatedAtUtc": "2026-06-17T20:24:07.252Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and reliability improvements for chat, Beta readiness, and behind-the-scenes analytics.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved chat media sizing and message-thread scrolling.",
        "Improved guest analytics and admin truth checks behind the scenes.",
        "Updated Beta readiness evidence so stale or missing launch evidence stays visible."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "admin",
        "navigation"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/admin-analytics-realtime-hot-cache.generated.json",
        "agent/state/analytics-admin-reorg.generated.json",
        "agent/state/analytics-hydration-consolidation-audit.generated.json",
        "agent/state/analytics-hydration-consolidation.generated.json",
        "agent/state/analytics-panel-hydration.generated.json",
        "agent/state/current-beta-exit-status.generated.json",
        "agent/state/generated-report-authority.generated.json",
        "agent/state/public-beta-score.generated.json",
        "docs/agent-truth/admin-analytics-realtime-hot-cache.md",
        "docs/agent-truth/analytics-admin-reorg.md",
        "docs/agent-truth/analytics-hydration-consolidation-audit.md",
        "docs/agent-truth/analytics-hydration-consolidation.md",
        "docs/agent-truth/analytics-panel-hydration.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-analytics-hydration-consolidation.ts",
        "scripts/agent/validate-analytics-panel-hydration.ts",
        "src/app/admin/analytics/hooks/useAdminAnalyticsState.tsx",
        "src/app/admin/analytics/page.tsx",
        "src/lib/analytics/person-metrics-hydration.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "src/lib/release-readiness/automated-truth-reconciliation.ts",
        "tests/unit/admin-analytics-page.spec.tsx",
        "tests/unit/analytics-hydration-consolidation.spec.ts",
        "tests/unit/analytics-panel-hydration.spec.ts"
      ],
      "sourceCommit": "081b3ad329ff835f8aeb54d68ce26c646aa7f723"
    },
    {
      "version": "1.5.75",
      "previousVersion": "1.5.74",
      "betaReleaseCounter": 575,
      "previousBetaReleaseCounter": 574,
      "commitSha": "414701925c6d602830f751305f47c775b11dd387",
      "commitTitle": "gumdrops: enforce paid-source creator spend truth",
      "commitCount": 78,
      "commitShas": [
        "a8313045e3eaa6885beb5e27cff5e18135a94ae7",
        "6325fdc9175233b014b14fdde70f1f8d3586c022",
        "4036da68d6023d0b662071eaeb3007fdc920d313",
        "d1c5bbea0b3c3bb0cb3783060fab27bac60a94d8",
        "b455a73a20639f0dda0297b97155e723e944368a",
        "8d9e29d49eefc07b9ef3e0a264078f75a2a1ae4c",
        "7f6e18edf43e1488053139b8a4a130706b6d6313",
        "e259bb5ae690bdbf0d199c63f99ba83ae109788a",
        "06f65fcf728ebbea1930d257fb34bfef6faab107",
        "df390a6f081263766d05c2da9666f71479172092",
        "dd0a29816509729b1fa66adb5a212c82b39673c0",
        "76184ee921592203df97fabe45c0d8289b9a8fbc",
        "bc4c7f9946bfdc9329d1ad92483f99c96489cb59",
        "6b53dbd66b959ba6f8c302a431e736c54dda5f8a",
        "9889565af36f59845a7c5d289fc328ce6ed6f939",
        "acc769c88834fc78d848519fe431aded700590f2",
        "4ed6370a209b25a64df6b178d2a996b93623056e",
        "6d4dedbaae129afb278bb3071db7bb879aaef639",
        "2c4ffdba3800dff806e63fc5b1d61bc2bb302527",
        "a0100b8ae3a07460dd4855c990cf200541fb9ab8",
        "675b50f177e59885214865d1f549a8f89c55f760",
        "630145e048ab43b2670ece27527660de70291701",
        "86882767b93d84894b0bb95c5104dab39cce64bc",
        "e58aef4bcd97ba8a1f84260b7bf4657f9aa56ee1",
        "79c8791c4308e4d53cf0d26c3326674422fdbd51",
        "3bdda2679b3cf84089c5493b07f27ea9f8c9b8dc",
        "3000d435c5dfde8da1d8101012ae51257fb6aee2",
        "7d4a216b24df8371cc9d2aeb8bd89fa3ba3e63df",
        "4e3b1fa018d7099dcd87ef9bdee9389d8cfa3189",
        "fd9b56c6193c5627436aba6a2b9399898e9542f2",
        "d5cfea0ee8fb49fae113082941ffd1d95ef78f5d",
        "c664db8d36c70b08c06b80d17ec86ee8227fe67a",
        "a4e4a031d47c95ce96ceb5d05055c6b3b5995467",
        "4625e11a355879686d31f9e27a3df030259b43ac",
        "d6c3cfc98ca37e09f36f1ced17fe854bbe72f304",
        "85cbaa3982f68bd0ee884327c8c6567385c63409",
        "ada4b8721fe3ecf49d1ec898fe5666061c4093d1",
        "972c6d2a56cda9ebbd11e068e6480abf943f858b",
        "d85c2861f4b48d21a2ef4f9360cbffbb792126da",
        "b5b44ccfd588cba254c46a029459fa4850b01f66",
        "dee54d1ab1d5ed481f20e9645dba37241e886740",
        "e842aeb59c42369cdc46ff36e01cb47179b8825b",
        "b45ef670b9aeaf25284b787793fb2a3517d4a0a2",
        "a431f9c6235f0ff94614ad91ab2b168c72852afd",
        "98b7500c823b9c0f3ab06b0d46980f37decc30c1",
        "c6107dae768cccd12030712f4e7dc04fc506440f",
        "ce9bf41fb6b4ca81080c03925e7e3469671f9ffb",
        "5886e28476f6ac77daef4a88f7bd7e738f9b19ac",
        "427a02b8aca57a99d932f78f3d969f9a799fc8c0",
        "f1c1d06e77dfa9534956498989e8acc304c9197f",
        "c093671ed9202ac43fd34c835a5fd40174a1e51e",
        "b2fc6ddebc2021afa0eddf560f08d33361c491a8",
        "d8ec1f646de908a6d78d2d4f5177e7055ace1961",
        "a5811e25e53c3b5c8beafa1dcb13853f21a587c9",
        "4eb970a07518e3c242ad6d718cfe196a070b479d",
        "8ecac65f7d4d3b2d55cf75198e7724572153c479",
        "270798bf4c4672b42f49ccdd89fce9a64e2cfe22",
        "618fcdd50063b2d9eb27bafa7bffbbb5eefe3ead",
        "aaf71b0057e96afac225054984ef0baa72d7718e",
        "986e6353aed80d5ec4eb0a8a7cb90043c1a49d39",
        "7935335384f627ac23214fea2d2baa4b4ecd71d7",
        "df59d378b3ee89db20b4a4c3ac94137c9c60464f",
        "0a7026e9fd98fa7ae3dc4d53365204e9faae4e7a",
        "a4818d83e8f93f46c86abf45ae029627054c2265",
        "67db4e33c84189a452bf6d19f57639cd7c43f28e",
        "fd4b61bec0cdfa7845c477ed32ae5da3967d796d",
        "3167ef8b4eba074269e2b09108a50c39f7e3eeff",
        "1dc086f56482ca575d4062b40aa0406faab24b16",
        "43866a6e6b68aa0805ee6d3e98d6540372fa7094",
        "a42e1e930cdf4bfb4b34252c7ee404ec46a68d1a",
        "614ad31b621abc95d4fe5aa94687792e2e388a3c",
        "7ea9311c54112f8d811e86906141aacb28b4525e",
        "547021a1aa5df424ae41a721a178e53aa6632c17",
        "9c74e255254033fb72ba965d2a769bf718550c8a",
        "4536d8817e8ca2fc5f831c7b0b9e37aae1ab7bdc",
        "d6467b058100facddbf73195080fccc863730118",
        "60f4c304abbda91c42f1bb1923771134338a2a81",
        "414701925c6d602830f751305f47c775b11dd387"
      ],
      "committedAt": "2026-06-17T19:34:03.000Z",
      "generatedAt": "2026-06-17T20:02:25.089Z",
      "committedAtUtc": "2026-06-17T19:34:03.000Z",
      "generatedAtUtc": "2026-06-17T20:02:25.089Z",
      "updatedAtUtc": "2026-06-17T20:02:25.089Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and reliability improvements for chat, Beta readiness, and behind-the-scenes analytics.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved chat media sizing and message-thread scrolling.",
        "Improved guest analytics and admin truth checks behind the scenes.",
        "Updated Beta readiness evidence so stale or missing launch evidence stays visible."
      ],
      "audience": "all",
      "technicalDetails": [
        "Grouped 78 commits into one accepted patch batch."
      ],
      "affectedSurfaces": [
        "account-onboarding",
        "admin",
        "chat-support",
        "creator",
        "drops-viewer",
        "navigation"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/evidence/admin-browser-surface-smoke/evidence.json",
        "agent/state/admin-analytics-finalization.generated.json",
        "agent/state/admin-analytics-realtime-hot-cache.generated.json",
        "agent/state/admin-analytics-source-hierarchy.generated.json",
        "agent/state/admin-browser-surface-smoke.generated.json",
        "agent/state/admin-truth-replacement.generated.json",
        "agent/state/current-beta-exit-status.generated.json",
        "agent/state/debug-cockpit-batch29-analytics-source-hierarchy.generated.json",
        "agent/state/debug-operator-cockpit.generated.json",
        "agent/state/debug-runtime-evidence.generated.json",
        "agent/state/debug-tracking-simplification.generated.json",
        "agent/state/gumdrop-ledger-math.generated.json",
        "agent/state/platform-pulse-compact.generated.json",
        "agent/state/public-beta-score.generated.json",
        "agent/state/same-commit-release-head-discipline.generated.json",
        "agent/state/support-policy-surface-cleanup.generated.json",
        "docs/agent-truth/admin-analytics-launch-final.md",
        "docs/agent-truth/admin-analytics-realtime-hot-cache.md",
        "docs/agent-truth/admin-analytics-source-hierarchy.md",
        "docs/agent-truth/admin-browser-surface-smoke.md",
        "docs/agent-truth/admin-copy-style-guide.md",
        "docs/agent-truth/debug-cockpit-batch29-analytics-source-hierarchy.md",
        "docs/agent-truth/debug-operator-cockpit.md",
        "docs/agent-truth/debug-runtime-evidence.md",
        "docs/agent-truth/debug-tracking-simplification.md",
        "docs/agent-truth/gumdrop-ledger-math.md",
        "docs/agent-truth/human-readable-admin-truth.md",
        "docs/agent-truth/same-commit-release-head-discipline.md",
        "docs/agent-truth/support-policy-surface-cleanup.md",
        "docs/agent-truth/watch-time-truth.md",
        "docs/doctrine/surfaces/wallet.md",
        "functions/src/behavioral-intelligence-runtime.ts",
        "public/kandydrops-release-notes.json",
        "scripts/agent/debug-cockpit-batch14-shared.ts",
        "scripts/agent/debug-cockpit-batch29-analytics-source-hierarchy-shared.ts",
        "scripts/agent/validate-admin-ai-control-tower.ts",
        "scripts/agent/validate-admin-analytics-finalization.ts",
        "scripts/agent/validate-admin-debug-control-tower.ts",
        "scripts/agent/validate-admin-pages-cutover.ts",
        "scripts/agent/validate-admin-projection-analytics-exclusion.ts",
        "scripts/agent/validate-admin-realtime-cutover.ts",
        "scripts/agent/validate-admin-truth-replacement.ts",
        "scripts/agent/validate-admin-user-behavior-truth.ts",
        "scripts/agent/validate-admin-user-metrics-snapshot.ts",
        "scripts/agent/validate-admin-users-loading-lanes.ts",
        "scripts/agent/validate-admin-users-stats-grid.ts",
        "scripts/agent/validate-behavioral-truth-source.ts",
        "scripts/agent/validate-cost-risk-exit-pass.ts",
        "scripts/agent/validate-debug-operator-cockpit.ts",
        "scripts/agent/validate-debug-runtime-evidence.ts",
        "scripts/agent/validate-debug-tracking-simplification.ts",
        "scripts/agent/validate-global-loading-performance.ts",
        "scripts/agent/validate-gumdrop-ledger-math.ts",
        "scripts/agent/validate-gumdrop-source-of-funds-truth.ts",
        "scripts/agent/validate-human-readable-admin-copy.ts",
        "scripts/agent/validate-platform-pulse-compact.ts",
        "scripts/agent/validate-refresh-based-hot-cache.ts",
        "scripts/check-admin-analytics-overview.ts",
        "scripts/check-admin-data-validation-relocation.ts",
        "src/app/admin/AdminPrivacyPreflight.tsx",
        "src/app/admin/ai/AiHelpers.tsx",
        "src/app/admin/ai/components/AdminAiOptimizerhealthSection.tsx",
        "src/app/admin/ai/components/AdminAiRecentgenerationsSection.tsx",
        "src/app/admin/ai/components/AdminAiReferencelibrarySection.tsx",
        "src/app/admin/ai/components/AdminAiRuntimestripSection.tsx",
        "src/app/admin/ai/hooks/useAdminAiState.tsx",
        "src/app/admin/ai/page.tsx",
        "src/app/admin/analytics/components/AdminAnalyticsAudienceTab.tsx",
        "src/app/admin/analytics/components/AdminAnalyticsCommerceTab.tsx",
        "src/app/admin/analytics/components/AdminAnalyticsOperationsTab.tsx",
        "src/app/admin/analytics/hooks/useAdminAnalyticsState.tsx",
        "src/app/admin/analytics/page.tsx",
        "src/app/admin/content/page.tsx",
        "src/app/admin/debug/components/DebugAdvancedBehavior.tsx",
        "src/app/admin/debug/components/DebugTabMonitoring.tsx",
        "src/app/admin/debug/components/DebugTelemetryHealthSummary.tsx",
        "src/app/admin/debug/components/DebugTrackingSummaryPanel.tsx",
        "src/app/admin/debug/page.tsx",
        "src/app/admin/drops/page.tsx",
        "src/app/admin/economy/components/PlatformEconomyConsole.tsx",
        "src/app/admin/economy/components/PlatformEconomyStrip.tsx",
        "src/app/admin/page.tsx",
        "src/app/admin/queue/page.tsx",
        "src/app/admin/roster/page.tsx",
        "src/app/admin/user/[userId]/page.tsx",
        "src/app/admin/users/page.tsx",
        "src/app/api/admin/analytics/historical/route.ts",
        "src/app/api/admin/overview/route.ts",
        "src/app/api/admin/users/route.ts",
        "src/app/api/creator/bookings/route.ts",
        "src/app/api/creator/requests/route.ts",
        "src/app/api/creator/subscriptions/route.ts",
        "src/app/api/cron/process-creator-subscriptions/route.ts",
        "src/components/Admin/AdminAiDescriptionOperations.tsx",
        "src/components/Admin/AdminMetricCard.tsx",
        "src/components/Admin/AdminModerationConsole.tsx",
        "src/components/Admin/AdminModerationSecurityAlerts.tsx",
        "src/components/Admin/AdminReviewBadge.tsx",
        "src/components/Admin/AdminStatsBar.tsx",
        "src/components/Admin/AdminSupportQueue.tsx",
        "src/components/Admin/AdminTruthBadge.tsx",
        "src/components/Admin/Analytics/AdminAnalyticsPrimitives.tsx",
        "src/components/Admin/Analytics/AdminDailyTaskPipelineModule.tsx",
        "src/components/Admin/Analytics/AdminOnboardingAnalyticsModules.tsx",
        "src/components/Admin/Analytics/AdminTaskAndNotificationModules.tsx",
        "src/components/Admin/RecentTransactionsPanel.tsx",
        "src/components/UIDebug.tsx",
        "src/hooks/useAdminOverviewRealtime.ts",
        "src/lib/admin-analytics-audience-snapshot.ts",
        "src/lib/admin-analytics-auth-outcome-split.ts",
        "src/lib/admin-analytics-commerce-snapshot.ts",
        "src/lib/admin-analytics-event-mix.ts",
        "src/lib/admin-analytics-guest-bounce-quality.ts",
        "src/lib/admin-analytics-journey-funnel.ts",
        "src/lib/admin-analytics-live-interaction-stream.ts",
        "src/lib/admin-analytics-preferences.ts",
        "src/lib/admin-analytics/realtime-hot-cache-contract.ts",
        "src/lib/admin-copy/admin-copy-registry.ts",
        "src/lib/admin-copy/admin-truth-copy.ts",
        "src/lib/admin-parity.ts",
        "src/lib/admin-truth-state.ts",
        "src/lib/admin/admin-realtime-policy.ts",
        "src/lib/analytics/admin-analytics-display-state.ts",
        "src/lib/analytics/admin-analytics-source-hierarchy.ts",
        "src/lib/gumdrop-ledger.ts",
        "src/lib/problem-state-copy.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "src/lib/server/admin-analytics-data.ts",
        "src/lib/server/admin-analytics-historical-traffic.ts",
        "src/lib/server/admin-analytics-historical-validation.ts",
        "src/lib/server/chat.ts",
        "src/lib/server/creator-experiences.ts",
        "src/types/admin-analytics.ts",
        "tests/unit/accessibility-tap-targets.spec.ts",
        "tests/unit/admin-ai-fixture-boundary.spec.ts",
        "tests/unit/admin-ai-snapshot-refresh.spec.ts",
        "tests/unit/admin-analytics-audience-mobile.spec.ts",
        "tests/unit/admin-analytics-audience-snapshot.spec.ts",
        "tests/unit/admin-analytics-auth-outcome-split.spec.ts",
        "tests/unit/admin-analytics-data.spec.ts",
        "tests/unit/admin-analytics-display-state.spec.ts",
        "tests/unit/admin-analytics-event-mix.spec.ts",
        "tests/unit/admin-analytics-fixture-boundary.spec.ts",
        "tests/unit/admin-analytics-guest-bounce-quality.spec.ts",
        "tests/unit/admin-analytics-historical-traffic.spec.ts",
        "tests/unit/admin-analytics-journey-funnel.spec.ts",
        "tests/unit/admin-analytics-live-interaction-stream.spec.ts",
        "tests/unit/admin-analytics-live-pulse.spec.ts",
        "tests/unit/admin-analytics-operations-mobile.spec.ts",
        "tests/unit/admin-analytics-page.spec.tsx",
        "tests/unit/admin-analytics-realtime-hot-cache.spec.ts",
        "tests/unit/admin-analytics-source-hierarchy.spec.ts",
        "tests/unit/admin-content-page.spec.tsx",
        "tests/unit/admin-daily-task-pipeline-mobile.spec.ts",
        "tests/unit/admin-data-validation.spec.ts",
        "tests/unit/admin-debug-compact-layout.spec.ts",
        "tests/unit/admin-debug-fixture-boundary.spec.ts",
        "tests/unit/admin-drops-fixture-boundary.spec.ts",
        "tests/unit/admin-economy-fixture-boundary.spec.ts",
        "tests/unit/admin-moderation-console-ui.spec.ts",
        "tests/unit/admin-moderation-fixture-boundary.spec.ts",
        "tests/unit/admin-notification-funnel-mobile.spec.ts",
        "tests/unit/admin-onboarding-analytics-mobile.spec.ts",
        "tests/unit/admin-overview-fixture-boundary.spec.ts",
        "tests/unit/admin-privacy-fixture-boundary.spec.ts",
        "tests/unit/admin-queue-page.spec.tsx",
        "tests/unit/admin-review-badge.spec.tsx",
        "tests/unit/admin-roster-fixture-boundary.spec.ts",
        "tests/unit/admin-stats-bar-compact.spec.ts",
        "tests/unit/admin-support-fixture-boundary.spec.ts",
        "tests/unit/admin-truth-badge.spec.tsx",
        "tests/unit/admin-truth-copy.spec.ts",
        "tests/unit/admin-truth-state.spec.ts",
        "tests/unit/admin-user-detail-fixture-boundary.spec.ts",
        "tests/unit/admin-users-fixture-boundary.spec.ts",
        "tests/unit/behavior-task-telemetry-ui-cleanup.spec.ts",
        "tests/unit/creator-bookings-route.spec.ts",
        "tests/unit/creator-bookings-transaction-route.spec.ts",
        "tests/unit/creator-requests-route.spec.ts",
        "tests/unit/creator-subscriptions-route.spec.ts",
        "tests/unit/debug-cockpit-batch14-cleanup.spec.ts",
        "tests/unit/debug-operator-cockpit.spec.ts",
        "tests/unit/debug-runtime-evidence.spec.ts",
        "tests/unit/debug-tracking-simplification.spec.ts",
        "tests/unit/gumdrop-ledger.spec.ts",
        "tests/unit/recent-transactions-panel-realtime-contract.spec.ts",
        "tests/unit/server-chat-send.spec.ts",
        "tests/unit/ui-debug-opt-in.spec.ts"
      ],
      "sourceCommit": "414701925c6d602830f751305f47c775b11dd387"
    },
    {
      "version": "1.5.74",
      "previousVersion": "1.5.73",
      "betaReleaseCounter": 574,
      "previousBetaReleaseCounter": 573,
      "commitSha": "59ed9c52c096664fe493f1b8f41d7db3897b5cdf",
      "commitTitle": "fix(deploy): restore deployment readiness",
      "commitCount": 2,
      "commitShas": [
        "e8b7cef206389e34a660d047f967bbb768607a89",
        "59ed9c52c096664fe493f1b8f41d7db3897b5cdf"
      ],
      "committedAt": "2026-06-17T00:53:13.000Z",
      "generatedAt": "2026-06-17T00:55:03.318Z",
      "committedAtUtc": "2026-06-17T00:53:13.000Z",
      "generatedAtUtc": "2026-06-17T00:55:03.318Z",
      "updatedAtUtc": "2026-06-17T00:55:03.318Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and reliability improvements for chat, Beta readiness, and behind-the-scenes analytics.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved chat media sizing and message-thread scrolling.",
        "Improved guest analytics and admin truth checks behind the scenes.",
        "Updated Beta readiness evidence so stale or missing launch evidence stays visible."
      ],
      "audience": "all",
      "technicalDetails": [
        "Grouped 2 commits into one accepted patch batch."
      ],
      "affectedSurfaces": [
        "navigation"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/current-beta-exit-status.generated.json",
        "agent/state/public-beta-score.generated.json",
        "agent/state/same-commit-release-head-discipline.generated.json",
        "docs/agent-truth/same-commit-release-head-discipline.md",
        "public/kandydrops-release-notes.json",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts"
      ],
      "sourceCommit": "59ed9c52c096664fe493f1b8f41d7db3897b5cdf"
    },
    {
      "version": "1.5.73",
      "previousVersion": "1.5.72",
      "betaReleaseCounter": 573,
      "previousBetaReleaseCounter": 572,
      "commitSha": "422fc7f96fcc7087120ea5a3d4af68b71e55fe89",
      "commitTitle": "fix(deploy): restore deployment readiness",
      "commitCount": 4,
      "commitShas": [
        "3736d072dfdd1f28d6fef673f083c25e12f827d1",
        "d68e940eca0f9c778e3de811d03a5d4b3c79807d",
        "85ad19f1ed7339fd3584504f0330b96d5330f607",
        "422fc7f96fcc7087120ea5a3d4af68b71e55fe89"
      ],
      "committedAt": "2026-06-17T00:30:15.000Z",
      "generatedAt": "2026-06-17T00:30:57.646Z",
      "committedAtUtc": "2026-06-17T00:30:15.000Z",
      "generatedAtUtc": "2026-06-17T00:30:57.646Z",
      "updatedAtUtc": "2026-06-17T00:30:57.646Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and reliability improvements for chat, Beta readiness, and behind-the-scenes analytics.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved chat media sizing and message-thread scrolling.",
        "Improved guest analytics and admin truth checks behind the scenes.",
        "Updated Beta readiness evidence so stale or missing launch evidence stays visible."
      ],
      "audience": "all",
      "technicalDetails": [
        "Grouped 4 commits into one accepted patch batch."
      ],
      "affectedSurfaces": [
        "navigation"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/current-beta-exit-status.generated.json",
        "agent/state/public-beta-score.generated.json",
        "public/kandydrops-release-notes.json",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts"
      ],
      "sourceCommit": "422fc7f96fcc7087120ea5a3d4af68b71e55fe89"
    },
    {
      "version": "1.5.72",
      "previousVersion": "1.5.71",
      "betaReleaseCounter": 572,
      "previousBetaReleaseCounter": 571,
      "commitSha": "18439dd00b6083b28aa877d210349ea7cdc1d6c6",
      "commitTitle": "fix(deploy): restore deployment readiness",
      "commitCount": 2,
      "commitShas": [
        "97f4b15f36721986f5c3f2492fd49d42164172f7",
        "18439dd00b6083b28aa877d210349ea7cdc1d6c6"
      ],
      "committedAt": "2026-06-16T19:33:59.000Z",
      "generatedAt": "2026-06-16T19:34:46.186Z",
      "committedAtUtc": "2026-06-16T19:33:59.000Z",
      "generatedAtUtc": "2026-06-16T19:34:46.186Z",
      "updatedAtUtc": "2026-06-16T19:34:46.186Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and reliability improvements for chat, Beta readiness, and behind-the-scenes analytics.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved chat media sizing and message-thread scrolling.",
        "Improved guest analytics and admin truth checks behind the scenes.",
        "Updated Beta readiness evidence so stale or missing launch evidence stays visible."
      ],
      "audience": "all",
      "technicalDetails": [
        "Grouped 2 commits into one accepted patch batch."
      ],
      "affectedSurfaces": [
        "navigation"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/current-beta-exit-status.generated.json",
        "agent/state/public-beta-score.generated.json",
        "public/kandydrops-release-notes.json",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts"
      ],
      "sourceCommit": "18439dd00b6083b28aa877d210349ea7cdc1d6c6"
    },
    {
      "version": "1.5.71",
      "previousVersion": "1.5.70",
      "betaReleaseCounter": 571,
      "previousBetaReleaseCounter": 570,
      "commitSha": "5f0bd1e264dc0081bbb49f8d536585f975e2dd78",
      "commitTitle": "fix(deploy): classify deployment health evidence",
      "commitCount": 1,
      "commitShas": [
        "5f0bd1e264dc0081bbb49f8d536585f975e2dd78"
      ],
      "committedAt": "2026-06-16T18:56:25.000Z",
      "generatedAt": "2026-06-16T18:57:09.852Z",
      "committedAtUtc": "2026-06-16T18:56:25.000Z",
      "generatedAtUtc": "2026-06-16T18:57:09.852Z",
      "updatedAtUtc": "2026-06-16T18:57:09.852Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and general improvements.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved internal beta reliability.",
        "Updated the latest Beta build with behind-the-scenes fixes."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "app"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/state/deployment-health.generated.json",
        "agent/state/generated-report-authority.generated.json",
        "scripts/verify-deployment.ts",
        "tests/unit/verify-deployment.spec.ts"
      ],
      "sourceCommit": "5f0bd1e264dc0081bbb49f8d536585f975e2dd78"
    },
    {
      "version": "1.5.70",
      "previousVersion": "1.5.69",
      "betaReleaseCounter": 570,
      "previousBetaReleaseCounter": 569,
      "commitSha": "0980f1fde1a51ffe53a3c1540e558bf342d2d365",
      "commitTitle": "fix(admin): simplify truth copy labels",
      "commitCount": 1,
      "commitShas": [
        "0980f1fde1a51ffe53a3c1540e558bf342d2d365"
      ],
      "committedAt": "2026-06-16T18:11:03.000Z",
      "generatedAt": "2026-06-16T18:11:11.420Z",
      "committedAtUtc": "2026-06-16T18:11:03.000Z",
      "generatedAtUtc": "2026-06-16T18:11:11.420Z",
      "updatedAtUtc": "2026-06-16T18:11:11.420Z",
      "category": "Fixed",
      "title": "Clearer admin analytics status copy",
      "summary": "Admin analytics now uses shorter status language and clearer delayed-state labels, with safer checkout fallback copy.",
      "userFacingTitle": "Clearer admin analytics status copy",
      "surfaceCategory": "App experience",
      "bullets": [
        "Made admin analytics cards easier to scan on mobile and desktop.",
        "Changed delayed analytics snapshots to say delayed instead of stale.",
        "Kept wallet checkout fallback errors clear and safe without changing payments."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "admin analytics",
        "wallet checkout"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "src/app/admin/analytics/components/AdminAnalyticsAudienceTab.tsx",
        "src/app/admin/analytics/components/AdminAnalyticsCommerceTab.tsx",
        "src/app/admin/analytics/components/AdminAnalyticsOperationsTab.tsx",
        "src/app/admin/analytics/page.tsx",
        "src/components/PurchaseModal.tsx"
      ],
      "sourceCommit": "0980f1fde1a51ffe53a3c1540e558bf342d2d365"
    },
    {
      "version": "1.5.69",
      "previousVersion": "1.5.68",
      "betaReleaseCounter": 569,
      "previousBetaReleaseCounter": 568,
      "commitSha": "a4755cf0679e28656439e7fcdd5e500d81157196",
      "commitTitle": "fix(admin): connect analytics overview truth",
      "commitCount": 6,
      "commitShas": [
        "2d9ce76cf4e403178cebc6ce8a4f11b63c249c0c",
        "d49461edcd839d6ccf12ddb65d4a8ecf06fb83d5",
        "b22b5e497b300f932bf2214998324e45646c0b0a",
        "fd280583fa4fdf80853c449530900feb8e346d9b",
        "096cab329c009d4440dc3dc65f4118497ce521b1",
        "a4755cf0679e28656439e7fcdd5e500d81157196"
      ],
      "committedAt": "2026-06-16T17:41:39.000Z",
      "generatedAt": "2026-06-16T17:45:31.717Z",
      "committedAtUtc": "2026-06-16T17:41:39.000Z",
      "generatedAtUtc": "2026-06-16T17:45:31.717Z",
      "updatedAtUtc": "2026-06-16T17:45:31.717Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and reliability improvements for chat, Beta readiness, and behind-the-scenes analytics.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved chat media sizing and message-thread scrolling.",
        "Improved guest analytics and admin truth checks behind the scenes.",
        "Updated Beta readiness evidence so stale or missing launch evidence stays visible."
      ],
      "audience": "all",
      "technicalDetails": [
        "Grouped 6 commits into one accepted patch batch."
      ],
      "affectedSurfaces": [
        "admin",
        "navigation"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/current-beta-exit-status.generated.json",
        "agent/state/public-beta-score.generated.json",
        "agent/state/telemetry-identified-parity.generated.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-current-beta-exit-status.ts",
        "scripts/agent/validate-runtime-watch-time-v2.ts",
        "scripts/agent/validate-source-backed-runtime-confidence.ts",
        "src/app/admin/analytics/hooks/useAdminAnalyticsState.tsx",
        "src/app/admin/analytics/page.tsx",
        "src/app/api/admin/debug/route.ts",
        "src/app/api/admin/overview/route.ts",
        "src/app/api/analytics/ingest-identified/route.ts",
        "src/components/Admin/AdminStatsBar.tsx",
        "src/components/Admin/Analytics/AdminAnalyticsPrimitives.tsx",
        "src/lib/admin-debug-control-tower.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "src/lib/telemetry.ts",
        "tests/unit/admin-analytics-page.spec.tsx",
        "tests/unit/admin-overview-route.spec.ts",
        "tests/unit/admin-stats-bar-compact.spec.ts",
        "tests/unit/source-backed-runtime-confidence.spec.ts"
      ],
      "sourceCommit": "a4755cf0679e28656439e7fcdd5e500d81157196"
    }
  ]
} satisfies PublicReleaseNotesDocument;

export const PUBLIC_RELEASE_NOTES_VERSION_CONTEXT = {
  betaReleaseCounter: PUBLIC_RELEASE_NOTES_FALLBACK.betaReleaseCounter,
  appVersion: PUBLIC_RELEASE_NOTES_FALLBACK.currentVersion,
  releaseChannel: PUBLIC_RELEASE_NOTES_FALLBACK.channel,
} as const;

export const PUBLIC_APP_VERSION = PUBLIC_RELEASE_NOTES_VERSION_CONTEXT.appVersion;
