import type { PublicReleaseNotesDocument } from "./release-version-contract";

export const PUBLIC_RELEASE_NOTES_FALLBACK = {
  "currentVersion": "1.2.27",
  "betaReleaseCounter": 227,
  "channel": "beta",
  "generatedAt": "2026-05-13T21:10:13.286Z",
  "generatedAtUtc": "2026-05-13T21:10:13.286Z",
  "lastCommitSha": "e5c7da278b19e5e7a48285ea1aebffe7ac562934",
  "notes": [
    {
      "version": "1.2.27",
      "previousVersion": "1.2.26",
      "betaReleaseCounter": 227,
      "previousBetaReleaseCounter": 226,
      "commitSha": "e5c7da278b19e5e7a48285ea1aebffe7ac562934",
      "commitTitle": "fix(analytics): collapse historical snapshot fallback authority",
      "commitCount": 1,
      "commitShas": [
        "e5c7da278b19e5e7a48285ea1aebffe7ac562934"
      ],
      "committedAt": "2026-05-13T21:08:52.000Z",
      "generatedAt": "2026-05-13T21:10:13.280Z",
      "committedAtUtc": "2026-05-13T21:08:52.000Z",
      "generatedAtUtc": "2026-05-13T21:10:13.280Z",
      "updatedAtUtc": "2026-05-13T21:10:13.280Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Improved historical Admin Analytics source handling behind the scenes.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved historical Admin Analytics source handling behind the scenes.",
        "Reduced raw analytics fallback behavior when verified snapshots are unavailable.",
        "Kept source, fallback, and vendor evidence labels clearer for debugging."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "app"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/state/analytics-rewire-phase-one.generated.json",
        "agent/state/identity-privacy-raw-ledger-rewire.generated.json",
        "agent/state/lost-data-recovery-dry-run.generated.json",
        "agent/state/snapshot-admin-vendor-cost-rewire.generated.json",
        "docs/agent-truth/snapshot-admin-vendor-cost-rewire.md",
        "scripts/agent/snapshot-admin-vendor-cost-rewire.ts",
        "scripts/agent/validate-admin-analytics-hot-cache.ts",
        "src/app/api/admin/analytics/historical/route.ts",
        "src/app/api/admin/debug/route.ts",
        "tests/unit/admin-analytics-historical-traffic.spec.ts"
      ],
      "sourceCommit": "e5c7da278b19e5e7a48285ea1aebffe7ac562934"
    },
    {
      "version": "1.2.26",
      "previousVersion": "1.2.25",
      "betaReleaseCounter": 226,
      "previousBetaReleaseCounter": 225,
      "commitSha": "e84b0c602becea2704f2acf5149f52a5a99a3e22",
      "commitTitle": "fix(analytics): collapse admin snapshot display authority",
      "commitCount": 1,
      "commitShas": [
        "e84b0c602becea2704f2acf5149f52a5a99a3e22"
      ],
      "committedAt": "2026-05-13T19:54:18.000Z",
      "generatedAt": "2026-05-13T19:55:34.179Z",
      "committedAtUtc": "2026-05-13T19:54:18.000Z",
      "generatedAtUtc": "2026-05-13T19:55:34.179Z",
      "updatedAtUtc": "2026-05-13T19:55:34.179Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Improved Admin Analytics snapshot authority and source labeling behind the scenes.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved how Admin Analytics chooses verified snapshot data behind the scenes.",
        "Reduced reliance on raw analytics logs as display truth.",
        "Kept vendor analytics labeled as supporting evidence instead of product truth."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "app"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/state/analytics-rewire-phase-one.generated.json",
        "agent/state/identity-privacy-raw-ledger-rewire.generated.json",
        "agent/state/lost-data-recovery-dry-run.generated.json",
        "agent/state/snapshot-admin-vendor-cost-rewire.generated.json",
        "docs/agent-truth/snapshot-admin-vendor-cost-rewire.md",
        "scripts/agent/validate-admin-analytics-hot-cache.ts",
        "src/app/api/admin/analytics/realtime/route.ts",
        "tests/unit/admin-analytics-realtime-route.spec.ts"
      ],
      "sourceCommit": "e84b0c602becea2704f2acf5149f52a5a99a3e22"
    },
    {
      "version": "1.2.25",
      "previousVersion": "1.2.24",
      "betaReleaseCounter": 225,
      "previousBetaReleaseCounter": 224,
      "commitSha": "4f730c3a001440d4f50075be1204b124ae63353e",
      "commitTitle": "chore(analytics): add snapshot admin vendor cost contract",
      "commitCount": 1,
      "commitShas": [
        "4f730c3a001440d4f50075be1204b124ae63353e"
      ],
      "committedAt": "2026-05-13T18:51:35.000Z",
      "generatedAt": "2026-05-13T18:52:48.910Z",
      "committedAtUtc": "2026-05-13T18:51:35.000Z",
      "generatedAtUtc": "2026-05-13T18:52:48.910Z",
      "updatedAtUtc": "2026-05-13T18:52:48.910Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and general improvements.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Added clearer rules for which analytics snapshots should power Admin Analytics.",
        "Prepared safer Debug-first handling for recovered analytics data.",
        "Improved internal checks that keep vendor analytics and raw logs from being treated as product truth."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "app"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/state/analytics-rewire-phase-one.generated.json",
        "agent/state/identity-privacy-raw-ledger-rewire.generated.json",
        "agent/state/lost-data-recovery-dry-run.generated.json",
        "agent/state/snapshot-admin-vendor-cost-rewire.generated.json",
        "docs/agent-truth/analytics-truth-layer-v2.md",
        "docs/agent-truth/lost-data-recovery-dry-run.md",
        "docs/agent-truth/snapshot-admin-vendor-cost-rewire.md",
        "package.json",
        "scripts/agent/snapshot-admin-vendor-cost-rewire.ts",
        "scripts/agent/validate-snapshot-admin-vendor-cost-rewire.ts",
        "tests/unit/snapshot-admin-vendor-cost-rewire.spec.ts"
      ],
      "sourceCommit": "4f730c3a001440d4f50075be1204b124ae63353e"
    },
    {
      "version": "1.2.24",
      "previousVersion": "1.2.23",
      "betaReleaseCounter": 224,
      "previousBetaReleaseCounter": 223,
      "commitSha": "17aad2136900861a00072446be7a0ff12e890888",
      "commitTitle": "chore(analytics): add lost data recovery dry run",
      "commitCount": 1,
      "commitShas": [
        "17aad2136900861a00072446be7a0ff12e890888"
      ],
      "committedAt": "2026-05-13T03:15:13.000Z",
      "generatedAt": "2026-05-13T03:16:49.956Z",
      "committedAtUtc": "2026-05-13T03:15:13.000Z",
      "generatedAtUtc": "2026-05-13T03:16:49.956Z",
      "updatedAtUtc": "2026-05-13T03:16:49.956Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and general improvements.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Prepared a dry-run recovery map for analytics data that may exist but has not surfaced yet.",
        "Added safer rules for which recovered data can appear in Admin Debug or Admin Analytics.",
        "Kept recovery planning local-only, with no production reads or backfills."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "app"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/state/analytics-rewire-phase-one.generated.json",
        "agent/state/identity-privacy-raw-ledger-rewire.generated.json",
        "agent/state/lost-data-recovery-dry-run.generated.json",
        "docs/agent-truth/identity-privacy-raw-ledger-rewire.md",
        "docs/agent-truth/lost-data-recovery-dry-run.md",
        "package.json",
        "scripts/agent/lost-data-recovery-dry-run.ts",
        "scripts/agent/validate-lost-data-recovery-dry-run.ts",
        "tests/unit/lost-data-recovery-dry-run.spec.ts"
      ],
      "sourceCommit": "17aad2136900861a00072446be7a0ff12e890888"
    },
    {
      "version": "1.2.23",
      "previousVersion": "1.2.22",
      "betaReleaseCounter": 223,
      "previousBetaReleaseCounter": 222,
      "commitSha": "5dfefd62b0c1f282015745cf0dd7ec08c0040c79",
      "commitTitle": "chore(analytics): add identity privacy raw ledger contract",
      "commitCount": 1,
      "commitShas": [
        "5dfefd62b0c1f282015745cf0dd7ec08c0040c79"
      ],
      "committedAt": "2026-05-13T01:25:52.000Z",
      "generatedAt": "2026-05-13T01:26:38.338Z",
      "committedAtUtc": "2026-05-13T01:25:52.000Z",
      "generatedAtUtc": "2026-05-13T01:26:38.338Z",
      "updatedAtUtc": "2026-05-13T01:26:38.338Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and general improvements.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved internal analytics reliability and privacy-aware data handling behind the scenes.",
        "Added clearer rules for what telemetry can be used when privacy settings are off.",
        "Prepared recovery rules for data that exists but has not surfaced in the app yet."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "app"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/state/analytics-rewire-phase-one.generated.json",
        "agent/state/identity-privacy-raw-ledger-rewire.generated.json",
        "docs/agent-truth/analytics-rewire-phase-one.md",
        "docs/agent-truth/analytics-truth-layer-v2.md",
        "docs/agent-truth/identity-privacy-raw-ledger-rewire.md",
        "package.json",
        "scripts/agent/identity-privacy-raw-ledger-rewire.ts",
        "scripts/agent/validate-identity-privacy-raw-ledger-rewire.ts",
        "tests/unit/identity-privacy-raw-ledger-rewire.spec.ts"
      ],
      "sourceCommit": "5dfefd62b0c1f282015745cf0dd7ec08c0040c79"
    },
    {
      "version": "1.2.22",
      "previousVersion": "1.2.21",
      "betaReleaseCounter": 222,
      "previousBetaReleaseCounter": 221,
      "commitSha": "a3618a39794e4fa3e98a4a5020980a9ac323171b",
      "commitTitle": "chore(analytics): add truth lane rewire inventory",
      "commitCount": 2,
      "commitShas": [
        "cd63341797090ac4934d190a4694af7e2f2441c7",
        "a3618a39794e4fa3e98a4a5020980a9ac323171b"
      ],
      "committedAt": "2026-05-13T00:42:13.000Z",
      "generatedAt": "2026-05-13T00:43:40.627Z",
      "committedAtUtc": "2026-05-13T00:42:13.000Z",
      "generatedAtUtc": "2026-05-13T00:43:40.627Z",
      "updatedAtUtc": "2026-05-13T00:43:40.627Z",
      "category": "Fixed",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and reliability improvements for chat, Beta readiness, and behind-the-scenes analytics.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved chat media sizing and message-thread scrolling.",
        "Improved guest analytics and admin truth checks behind the scenes.",
        "Updated Beta readiness evidence so stale or missing launch evidence stays visible."
      ],
      "audience": "all",
      "technicalDetails": [
        "Grouped 2 commits into one accepted patch batch."
      ],
      "affectedSurfaces": [
        "navigation"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/analytics-rewire-phase-one.generated.json",
        "docs/agent-truth/analytics-rewire-phase-one.md",
        "docs/agent-truth/analytics-truth-layer-v2.md",
        "docs/agent-truth/public-beta-release-notes.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/analytics-rewire-phase-one.ts",
        "scripts/agent/validate-analytics-rewire-phase-one.ts",
        "scripts/agent/validate-public-beta-changelog.ts",
        "scripts/agent/validate-release-notes-cutover.ts",
        "scripts/release/update-public-changelog.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/analytics-rewire-phase-one.spec.ts"
      ],
      "sourceCommit": "a3618a39794e4fa3e98a4a5020980a9ac323171b"
    },
    {
      "version": "1.2.21",
      "previousVersion": "1.2.20",
      "betaReleaseCounter": 221,
      "previousBetaReleaseCounter": 220,
      "commitSha": "c2a5d322b8f3bb8bef95ed355ec701d3e36f90f3",
      "commitTitle": "fix(launch): keep pr triage fresh after evidence commits",
      "commitCount": 14,
      "commitShas": [
        "99e24e1ca85498cbaa15ac5d11e51aaf73932e56",
        "430c42ebcf066cde2f686d2bad519ce60b50bde9",
        "265d0957539d90c180bd9b68a83313012ff00bf1",
        "30a146f5d388da6e71ae1269a0db24e6e9120198",
        "537e5c7dd3913718ba6632fd48c62c12e6bcc1ff",
        "66405da6d69ecdfaeae4c9dd98f69b09e0db3a93",
        "c3d7cd6cddee3818d54a09aca221a0fdd0ac7e62",
        "260725259c806ab9fabb84d1674a28ac5e7b0d58",
        "4fbe03dc0191aa2594cbc2c3fff514c760fe0377",
        "7529d0064377c9489725139e9f04817de3e1d633",
        "e2b270f7b25c3516666471ad0f74ce1d3d0e9a13",
        "6955246c6baabf0e8dcaee696dc73a37ff11301d",
        "b2908c980a53e6503e0d20f6f5df93b84b2a6e44",
        "c2a5d322b8f3bb8bef95ed355ec701d3e36f90f3"
      ],
      "committedAt": "2026-05-12T20:17:51.000Z",
      "generatedAt": "2026-05-12T22:41:08.926Z",
      "committedAtUtc": "2026-05-12T20:17:51.000Z",
      "generatedAtUtc": "2026-05-12T22:41:08.926Z",
      "updatedAtUtc": "2026-05-12T22:41:08.926Z",
      "category": "New",
      "title": "Bug fixes and general improvements",
      "summary": "Bug fixes and reliability improvements for chat, Beta readiness, and behind-the-scenes analytics.",
      "userFacingTitle": "Bug fixes and general improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved chat media sizing and message-thread scrolling.",
        "Improved guest analytics and admin truth checks behind the scenes.",
        "Updated Beta readiness evidence so stale or missing launch evidence stays visible."
      ],
      "audience": "all",
      "technicalDetails": [
        "Grouped 14 commits into one accepted patch batch."
      ],
      "affectedSurfaces": [
        "admin",
        "chat-support",
        "creator",
        "drops-viewer",
        "navigation",
        "wallet"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        ".github/workflows/public-release-notes.yml",
        "AGENTS.md",
        "CHANGELOG.md",
        "README.md",
        "REPO_MEMORY_LEDGER.md",
        "agent/context/code-organization.index.json",
        "agent/context/optimized-task-context.generated.json",
        "agent/state/4xx-cost-guardrails.generated.json",
        "agent/state/ai-cover-learning-cutover.generated.json",
        "agent/state/billing-spike-radar.generated.json",
        "agent/state/client-loading-speed.generated.json",
        "agent/state/code-organization-score.generated.json",
        "agent/state/codebase-hardening.generated.json",
        "agent/state/codebase-junk-cleanup.generated.json",
        "agent/state/event-timeline-management.generated.json",
        "agent/state/final-launch-readiness-report.generated.json",
        "agent/state/generated-report-authority.generated.json",
        "agent/state/global-cost-surfaces.generated.json",
        "agent/state/google-cloud-cost-data-handoff.generated.json",
        "agent/state/google-cost-bleed.generated.json",
        "agent/state/guest-user-analytics-cutover.generated.json",
        "agent/state/launch-pr-triage.generated.json",
        "agent/state/launch-readiness-report.generated.json",
        "agent/state/legacy-phaseout.generated.json",
        "agent/state/orphaned-logic-score.generated.json",
        "agent/state/phase-one-final-cleanup.generated.json",
        "agent/state/public-beta-score.generated.json",
        "agent/state/server-loading-speed.generated.json",
        "agent/state/speed-security-hardening.generated.json",
        "agent/state/user-creator-feature-parity.generated.json",
        "agent/state/user-tracking-index-cutover.generated.json",
        "docs/agent-truth/admin-ai-control-tower.md",
        "docs/agent-truth/ai-cover-learning-cutover.md",
        "docs/agent-truth/ai-cover-prompt-compiler.md",
        "docs/agent-truth/beta-versioning-final.md",
        "docs/agent-truth/final-launch-readiness-report.md",
        "docs/agent-truth/guest-user-analytics-cutover.md",
        "docs/agent-truth/launch-pr-triage.md",
        "docs/agent-truth/launch-readiness-final.md",
        "docs/agent-truth/phase-one-final-cleanup.md",
        "docs/agent-truth/public-beta-score.md",
        "functions/src/analytics-realtime-summary.ts",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/check-infrastructure-truth.ts",
        "scripts/agent/scan-codebase-junk.ts",
        "scripts/agent/score-ai-cover-learning.ts",
        "scripts/agent/score-google-cost-bleed.ts",
        "scripts/agent/score-public-beta-readiness.ts",
        "scripts/agent/validate-admin-analytics-hot-cache.ts",
        "scripts/agent/validate-admin-analytics-no-pure-realtime.ts",
        "scripts/agent/validate-ai-cover-hard-cutover-v2.ts",
        "scripts/agent/validate-ai-cover-learning-cutover.ts",
        "scripts/agent/validate-analytics-event-contract.ts",
        "scripts/agent/validate-beta-versioning-final.ts",
        "scripts/agent/validate-client-loading-speed.ts",
        "scripts/agent/validate-cover-prompt-compiler.ts",
        "scripts/agent/validate-final-launch-readiness-report.ts",
        "scripts/agent/validate-guest-user-analytics-cutover.ts",
        "scripts/agent/validate-launch-pr-triage.ts",
        "scripts/agent/validate-launch-readiness-final.ts",
        "scripts/agent/validate-phase-one-final-cleanup.ts",
        "scripts/agent/validate-public-beta-score.ts",
        "scripts/agent/validate-user-chat-shell-routing.ts",
        "scripts/agent/validate-user-creator-feature-parity.ts",
        "scripts/check-admin-analytics-guest-bounce-quality.ts",
        "scripts/check-admin-analytics-live-pulse.ts",
        "scripts/release/update-public-changelog.ts",
        "src/app/admin/ai/components/AdminAiRecentgenerationsSection.tsx",
        "src/app/admin/ai/page.tsx",
        "src/app/admin/analytics/components/AdminAnalyticsOperationsTab.tsx",
        "src/app/admin/analytics/hooks/useAdminAnalyticsState.tsx",
        "src/app/admin/analytics/page.tsx",
        "src/app/api/admin/ai/drop-covers/feedback/route.ts",
        "src/app/api/admin/ai/drop-covers/generate/route.ts",
        "src/app/api/admin/ai/drop-covers/prompt-policy/route.ts",
        "src/app/api/admin/ai/drop-covers/references/route.ts",
        "src/app/api/admin/ai/drop-covers/review-gallery/route.ts",
        "src/app/api/admin/ai/drop-covers/route.ts",
        "src/app/api/admin/ai/drop-covers/template/route.ts",
        "src/app/api/admin/ai/drop-descriptions/feedback/route.ts",
        "src/app/api/admin/ai/drop-descriptions/generate/route.ts",
        "src/app/api/admin/ai/drop-descriptions/prompt-policy/route.ts",
        "src/app/api/admin/ai/drop-descriptions/route.ts",
        "src/app/api/admin/analytics/realtime/route.ts",
        "src/app/api/admin/debug/route.ts",
        "src/app/api/analytics/ingest/route.ts",
        "src/app/api/chat/attachments/complete/route.ts",
        "src/app/api/chat/attachments/prepare/route.ts",
        "src/app/api/chat/threads/[threadId]/read/route.ts",
        "src/app/api/chat/threads/[threadId]/route.ts",
        "src/app/api/creator/discovery/route.ts",
        "src/app/api/creators/[username]/route.ts",
        "src/app/api/drops/route.ts",
        "src/app/api/settings/landing/route.ts",
        "src/app/api/user/check-username/route.ts",
        "src/app/api/user/data/route.ts",
        "src/app/api/user/delete/route.ts",
        "src/app/api/wallet/packages/route.ts",
        "src/components/Admin/AiDropCoverGeneratorPanel.tsx",
        "src/components/Analytics/DeepTracker.tsx",
        "src/components/Chat/ChatExperience.tsx",
        "src/components/ReleaseNotes/BetaReleaseNotesDrawer.tsx",
        "src/hooks/useChatUnreadStatus.ts",
        "src/lib/admin-analytics-guest-bounce-quality.ts",
        "src/lib/admin-analytics-live-pulse.ts",
        "src/lib/agent-score/core.ts",
        "src/lib/agent-score/public-beta-scanner.ts",
        "src/lib/agent-score/reporting.ts",
        "src/lib/agent-score/weights.ts",
        "src/lib/ai-cover/cover-debug-summary.ts",
        "src/lib/ai-cover/cover-feedback-normalizer.ts",
        "src/lib/ai-cover/cover-generation-preflight.ts",
        "src/lib/ai-cover/cover-improvement-score.ts",
        "src/lib/ai-cover/cover-layout-dna.ts",
        "src/lib/ai-cover/cover-learning-contract.ts",
        "src/lib/ai-cover/cover-learning-ledger.ts",
        "src/lib/ai-cover/cover-learning-utils.ts",
        "src/lib/ai-cover/cover-negative-memory.ts",
        "src/lib/ai-cover/cover-optimizer-guard.ts",
        "src/lib/ai-cover/cover-prompt-compiler.ts",
        "src/lib/ai-cover/cover-prompt-delta-engine.ts",
        "src/lib/ai-cover/cover-reference-eligibility.ts",
        "src/lib/ai-cover/cover-reference-policy.ts",
        "src/lib/ai-cover/cover-reference-selector.ts",
        "src/lib/ai-cover/cover-semantic-brief.ts",
        "src/lib/ai-cover/cover-semantic-ontology.ts",
        "src/lib/ai-cover/cover-title-parser.ts",
        "src/lib/ai-cover/flavor-ontology.ts",
        "src/lib/ai-cover/model-prompt-adapters.ts",
        "src/lib/ai-drop-covers.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-note-classifier.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "src/lib/server/ai-drop-covers.ts",
        "src/lib/server/rate-limit.ts",
        "src/lib/server/request-guard.ts",
        "src/types/admin-analytics.ts",
        "tests/unit/admin-analytics-live-pulse.spec.ts",
        "tests/unit/admin-analytics-realtime-route.spec.ts",
        "tests/unit/ai-cover-learning.spec.ts",
        "tests/unit/analytics-ingest-route.spec.ts",
        "tests/unit/guest-analytics-identity.spec.ts",
        "tests/unit/public-beta-score.spec.ts"
      ],
      "sourceCommit": "c2a5d322b8f3bb8bef95ed355ec701d3e36f90f3"
    },
    {
      "version": "1.18.0",
      "previousVersion": "1.18.0",
      "betaReleaseCounter": 220,
      "previousBetaReleaseCounter": 220,
      "commitSha": "f56b3cdcede051a7a9d3be6a7f878bcdc7f702b8",
      "commitTitle": "chore(phase-one): cleanup speed and cost hardening",
      "commitCount": 1,
      "commitShas": [
        "f56b3cdcede051a7a9d3be6a7f878bcdc7f702b8"
      ],
      "committedAt": "2026-05-08T07:30:49.000Z",
      "generatedAt": "2026-05-08T07:36:22.617Z",
      "committedAtUtc": "2026-05-08T07:30:49.000Z",
      "generatedAtUtc": "2026-05-08T07:36:22.617Z",
      "updatedAtUtc": "2026-05-08T07:36:22.617Z",
      "category": "Internal Reliability",
      "title": "Internal reliability improvements",
      "summary": "Internal reliability updates with no user-facing product changes.",
      "userFacingTitle": "Internal reliability improvements",
      "surfaceCategory": "Internal reliability",
      "bullets": [
        "Improved behind-the-scenes reliability."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "app"
      ],
      "hiddenFromPublic": true,
      "changedFiles": [
        "AGENTS.md",
        "README.md",
        "REPO_MEMORY_LEDGER.md",
        "agent/state/4xx-cost-guardrails.generated.json",
        "agent/state/billing-spike-radar.generated.json",
        "agent/state/client-loading-speed.generated.json",
        "agent/state/codebase-junk-cleanup.generated.json",
        "agent/state/event-timeline-management.generated.json",
        "agent/state/google-cloud-cost-data-handoff.generated.json",
        "agent/state/guest-user-analytics-cutover.generated.json",
        "agent/state/phase-one-final-cleanup.generated.json",
        "agent/state/server-loading-speed.generated.json",
        "agent/state/user-creator-feature-parity.generated.json",
        "agent/state/user-tracking-index-cutover.generated.json",
        "docs/agent-truth/client-loading-speed.md",
        "docs/agent-truth/codebase-junk-cleanup.md",
        "docs/agent-truth/event-timeline-management.md",
        "docs/agent-truth/google-cloud-cost-data-handoff.md",
        "docs/agent-truth/phase-one-final-cleanup.md",
        "docs/agent-truth/server-loading-speed.md",
        "docs/agent-truth/user-creator-feature-parity.md",
        "package.json",
        "scripts/agent/scan-codebase-junk.ts",
        "scripts/agent/validate-client-loading-speed.ts",
        "scripts/agent/validate-codebase-junk-cleanup.ts",
        "scripts/agent/validate-event-timeline-management.ts",
        "scripts/agent/validate-google-cloud-cost-data-handoff.ts",
        "scripts/agent/validate-phase-one-final-cleanup.ts",
        "scripts/agent/validate-server-loading-speed.ts",
        "scripts/agent/validate-user-creator-feature-parity.ts"
      ],
      "effectiveChangeCount": 847,
      "excludedGeneratedChangeCount": 10455,
      "bumpType": "none",
      "sourceCommit": "f56b3cdcede051a7a9d3be6a7f878bcdc7f702b8"
    },
    {
      "version": "1.18.0",
      "previousVersion": "1.17.0",
      "betaReleaseCounter": 220,
      "previousBetaReleaseCounter": 219,
      "commitSha": "cabf2e2d75570710d622b508955f5b92d3881fa8",
      "commitTitle": "fix(home): reduce mobile section sprawl",
      "commitCount": 1,
      "commitShas": [
        "cabf2e2d75570710d622b508955f5b92d3881fa8"
      ],
      "committedAt": "2026-05-08T07:22:06.000Z",
      "generatedAt": "2026-05-08T07:36:22.419Z",
      "committedAtUtc": "2026-05-08T07:22:06.000Z",
      "generatedAtUtc": "2026-05-08T07:36:22.419Z",
      "updatedAtUtc": "2026-05-08T07:36:22.419Z",
      "category": "Fixed",
      "title": "Bug fixes and quality-of-life improvements",
      "summary": "Bug fixes and quality-of-life improvements.",
      "userFacingTitle": "Bug fixes and quality-of-life improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Fixed beta issues to make KandyDrops smoother to use.",
        "Improved reliability for the latest Beta build."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "app"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "docs/agent-truth/homepage-mobile-density.md",
        "docs/agent-truth/user-critical-path-lock.md",
        "package.json",
        "scripts/agent/validate-homepage-mobile-density.ts",
        "src/app/page.tsx",
        "src/components/CreatorDiscoveryRail.tsx",
        "src/components/Landing/HowItWorks.tsx"
      ],
      "effectiveChangeCount": 182,
      "excludedGeneratedChangeCount": 0,
      "bumpType": "minor",
      "sourceCommit": "cabf2e2d75570710d622b508955f5b92d3881fa8"
    },
    {
      "version": "1.17.0",
      "previousVersion": "1.16.0",
      "betaReleaseCounter": 219,
      "previousBetaReleaseCounter": 218,
      "commitSha": "7dc85c6fef07f8e373215ff3437721e35deb596e",
      "commitTitle": "fix(chat): refine ios pwa shell and media limits",
      "commitCount": 1,
      "commitShas": [
        "7dc85c6fef07f8e373215ff3437721e35deb596e"
      ],
      "committedAt": "2026-05-08T07:18:44.000Z",
      "generatedAt": "2026-05-08T07:36:22.243Z",
      "committedAtUtc": "2026-05-08T07:18:44.000Z",
      "generatedAtUtc": "2026-05-08T07:36:22.243Z",
      "updatedAtUtc": "2026-05-08T07:36:22.243Z",
      "category": "Fixed",
      "title": "Improved navigation reliability",
      "summary": "Bug fixes and quality-of-life improvements for top-level navigation and Beta update access.",
      "userFacingTitle": "Improved navigation reliability",
      "surfaceCategory": "Navigation",
      "bullets": [
        "Improved how key app navigation surfaces stay in sync with the latest Beta build.",
        "Reduced confusing status changes when opening update notes and top-level navigation lanes."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "chat-support",
        "navigation"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "docs/agent-truth/chat-media-limits.md",
        "docs/agent-truth/chat-shell-stability.md",
        "docs/agent-truth/creator-fan-experience-settings.md",
        "docs/agent-truth/user-creator-mobile-lock.md",
        "package.json",
        "scripts/agent/validate-ios-pwa-chat-refinements.ts",
        "src/app/api/chat/attachments/complete/route.ts",
        "src/app/api/chat/attachments/prepare/route.ts",
        "src/components/Chat/ChatExperience.tsx",
        "src/components/Chat/ChatRouteShell.tsx",
        "src/components/CoreLayoutWrapper.tsx",
        "src/components/Navigation/MobileBottomBar.tsx",
        "src/lib/chat-send-feedback.ts",
        "src/lib/chat.ts",
        "src/lib/chat/chat-media-limits.ts",
        "src/lib/device-layout-contract.ts",
        "src/lib/server/chat-media-limit-policy.ts",
        "src/lib/server/chat.ts",
        "src/lib/telemetry-catalog.ts",
        "src/lib/user-mobile-shell.ts",
        "tests/unit/chat-ios-pwa-detection.spec.ts",
        "tests/unit/chat-media-limits.spec.ts"
      ],
      "effectiveChangeCount": 830,
      "excludedGeneratedChangeCount": 0,
      "bumpType": "minor",
      "sourceCommit": "7dc85c6fef07f8e373215ff3437721e35deb596e"
    },
    {
      "version": "1.16.0",
      "previousVersion": "1.15.0",
      "betaReleaseCounter": 218,
      "previousBetaReleaseCounter": 217,
      "commitSha": "5fe5dcb9a006b7a3b2603142acd03d5153146842",
      "commitTitle": "fix(pwa): stabilize android chat sizing and silence stale build banner",
      "commitCount": 1,
      "commitShas": [
        "5fe5dcb9a006b7a3b2603142acd03d5153146842"
      ],
      "committedAt": "2026-05-08T07:02:53.000Z",
      "generatedAt": "2026-05-08T07:36:22.051Z",
      "committedAtUtc": "2026-05-08T07:02:53.000Z",
      "generatedAtUtc": "2026-05-08T07:36:22.051Z",
      "updatedAtUtc": "2026-05-08T07:36:22.051Z",
      "category": "Fixed",
      "title": "Bug fixes and quality-of-life improvements",
      "summary": "Bug fixes and quality-of-life improvements.",
      "userFacingTitle": "Bug fixes and quality-of-life improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Fixed beta issues to make KandyDrops smoother to use.",
        "Improved reliability for the latest Beta build."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "app"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/context/optimized-task-context.generated.json",
        "docs/agent-truth/chat-shell-stability.md",
        "docs/agent-truth/pwa-build-freshness.md",
        "docs/agent-truth/user-creator-mobile-lock.md",
        "package.json",
        "scripts/agent/validate-android-pwa-chat-and-build-banner.ts",
        "src/components/Chat/ChatExperience.tsx",
        "src/components/Chat/ChatRouteShell.tsx",
        "src/components/PwaRuntimeBridge.tsx",
        "src/lib/device-layout-contract.ts",
        "src/lib/user-mobile-shell.ts"
      ],
      "effectiveChangeCount": 314,
      "excludedGeneratedChangeCount": 2,
      "bumpType": "minor",
      "sourceCommit": "5fe5dcb9a006b7a3b2603142acd03d5153146842"
    },
    {
      "version": "1.15.0",
      "previousVersion": "1.14.0",
      "betaReleaseCounter": 217,
      "previousBetaReleaseCounter": 216,
      "commitSha": "13297da6e291942128d4157c8d8f4bf8501c0e5e",
      "commitTitle": "refactor(ai): compact drop creation and deterministic compilers",
      "commitCount": 1,
      "commitShas": [
        "13297da6e291942128d4157c8d8f4bf8501c0e5e"
      ],
      "committedAt": "2026-05-08T06:55:36.000Z",
      "generatedAt": "2026-05-08T07:36:21.871Z",
      "committedAtUtc": "2026-05-08T06:55:36.000Z",
      "generatedAtUtc": "2026-05-08T07:36:21.871Z",
      "updatedAtUtc": "2026-05-08T07:36:21.871Z",
      "category": "Improved",
      "title": "Improved drops and viewer reliability",
      "summary": "Bug fixes and quality-of-life improvements for drops, previews, and viewer behavior.",
      "userFacingTitle": "Improved drops and viewer reliability",
      "surfaceCategory": "Drops & viewer",
      "bullets": [
        "Improved drop and viewer reliability so usage states stay easier to understand.",
        "Reduced confusing stale or delayed states across previews and viewer surfaces."
      ],
      "audience": "users",
      "affectedSurfaces": [
        "admin",
        "creator",
        "drops-viewer"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "docs/agent-truth/admin-ai-control-tower.md",
        "docs/agent-truth/ai-cover-prompt-compiler.md",
        "docs/agent-truth/content-media-pipeline.md",
        "docs/agent-truth/creator-fan-experience-settings.md",
        "docs/agent-truth/drop-description-compiler.md",
        "docs/agent-truth/payment-unlock-entitlement.md",
        "package.json",
        "scripts/agent/validate-ai-drop-creation-compact-cutover.ts",
        "scripts/agent/validate-cover-prompt-compiler.ts",
        "scripts/agent/validate-drop-description-compiler.ts",
        "scripts/agent/validate-fan-pass-unlock-entitlement.ts",
        "src/app/admin/ai/page.tsx",
        "src/app/api/admin/ai/drop-covers/prompt-policy/route.ts",
        "src/app/api/admin/ai/drop-descriptions/generate/route.ts",
        "src/app/api/drops/unlock/route.ts",
        "src/components/Admin/AiDropCoverGeneratorPanel.tsx",
        "src/components/Admin/AiDropDescriptionGeneratorPanel.tsx",
        "src/components/Admin/AssetUploader.tsx",
        "src/components/Admin/CollapsibleDropSection.tsx",
        "src/components/Admin/CompactAiActionButton.tsx",
        "src/components/Admin/CompactAiModuleCard.tsx",
        "src/components/Admin/CompactAiStatusChip.tsx",
        "src/lib/ai-cover/cover-feedback-weights.ts",
        "src/lib/ai-cover/cover-layout-dna.ts",
        "src/lib/ai-cover/cover-prompt-compiler.ts",
        "src/lib/ai-cover/cover-title-parser.ts",
        "src/lib/ai-cover/creator-brand-resolver.ts",
        "src/lib/ai-cover/flavor-ontology.ts",
        "src/lib/ai-cover/model-prompt-adapters.ts",
        "src/lib/ai-drop-covers.ts",
        "src/lib/drop-descriptions/drop-description-compiler.ts",
        "src/lib/drop-descriptions/drop-description-feedback.ts",
        "src/lib/drop-descriptions/drop-description-memory.ts",
        "src/lib/drop-descriptions/drop-description-patterns.ts"
      ],
      "effectiveChangeCount": 961,
      "excludedGeneratedChangeCount": 0,
      "bumpType": "minor",
      "sourceCommit": "13297da6e291942128d4157c8d8f4bf8501c0e5e"
    },
    {
      "version": "1.14.0",
      "previousVersion": "1.13.0",
      "betaReleaseCounter": 216,
      "previousBetaReleaseCounter": 215,
      "commitSha": "ecdc8c1737d6d6bb810da5fd218cc54fcbfa35b4",
      "commitTitle": "feat(cost): add billing spike radar",
      "commitCount": 1,
      "commitShas": [
        "ecdc8c1737d6d6bb810da5fd218cc54fcbfa35b4"
      ],
      "committedAt": "2026-05-08T06:42:22.000Z",
      "generatedAt": "2026-05-08T07:36:21.680Z",
      "committedAtUtc": "2026-05-08T06:42:22.000Z",
      "generatedAtUtc": "2026-05-08T07:36:21.680Z",
      "updatedAtUtc": "2026-05-08T07:36:21.680Z",
      "category": "New",
      "title": "Bug fixes and quality-of-life improvements",
      "summary": "Bug fixes and quality-of-life improvements.",
      "userFacingTitle": "Bug fixes and quality-of-life improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Fixed beta issues to make KandyDrops smoother to use.",
        "Improved reliability for the latest Beta build."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "app"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/state/billing-spike-radar.generated.json",
        "docs/agent-truth/billing-spike-radar.md",
        "package.json",
        "scripts/agent/score-billing-spike-radar.ts",
        "scripts/agent/validate-billing-spike-radar.ts",
        "src/lib/cost/billing-spike-contract.ts",
        "src/lib/cost/billing-spike-risk-score.ts"
      ],
      "effectiveChangeCount": 989,
      "excludedGeneratedChangeCount": 1943,
      "bumpType": "minor",
      "sourceCommit": "ecdc8c1737d6d6bb810da5fd218cc54fcbfa35b4"
    },
    {
      "version": "1.13.0",
      "previousVersion": "1.12.0",
      "betaReleaseCounter": 215,
      "previousBetaReleaseCounter": 214,
      "commitSha": "a8b4970a94030a87372763b8ea4292c7c79d8820",
      "commitTitle": "feat(cost): normalize 4xx guardrails",
      "commitCount": 1,
      "commitShas": [
        "a8b4970a94030a87372763b8ea4292c7c79d8820"
      ],
      "committedAt": "2026-05-08T06:35:35.000Z",
      "generatedAt": "2026-05-08T07:36:21.504Z",
      "committedAtUtc": "2026-05-08T06:35:35.000Z",
      "generatedAtUtc": "2026-05-08T07:36:21.504Z",
      "updatedAtUtc": "2026-05-08T07:36:21.504Z",
      "category": "New",
      "title": "Bug fixes and quality-of-life improvements",
      "summary": "Bug fixes and quality-of-life improvements.",
      "userFacingTitle": "Bug fixes and quality-of-life improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Fixed beta issues to make KandyDrops smoother to use.",
        "Improved reliability for the latest Beta build."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "app"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/state/4xx-cost-guardrails.generated.json",
        "docs/agent-truth/4xx-cost-guardrails.md",
        "docs/agent-truth/cloudrun-sql-bigquery-guardrails.md",
        "docs/agent-truth/content-protection-score.md",
        "docs/agent-truth/global-cost-surfaces.md",
        "docs/agent-truth/speed-security-hardening.md",
        "middleware.ts",
        "package.json",
        "scripts/agent/score-4xx-cost-guardrails.ts",
        "scripts/agent/validate-4xx-cost-guardrails.ts",
        "src/app/api/analytics/ingest-identified/route.ts",
        "src/app/api/analytics/ingest/route.ts",
        "src/lib/server/cheap-4xx-response.ts",
        "src/lib/server/http-error-cost-contract.ts",
        "src/lib/server/request-guard.ts",
        "src/lib/server/route-4xx-classifier.ts",
        "src/lib/server/route-4xx-dedupe.ts",
        "tests/unit/4xx-cost-guardrails.spec.ts"
      ],
      "effectiveChangeCount": 623,
      "excludedGeneratedChangeCount": 84,
      "bumpType": "minor",
      "sourceCommit": "a8b4970a94030a87372763b8ea4292c7c79d8820"
    },
    {
      "version": "1.12.0",
      "previousVersion": "1.11.0",
      "betaReleaseCounter": 214,
      "previousBetaReleaseCounter": 213,
      "commitSha": "806753aee0f5fb8e62824be5acb0cf8609c3d0a8",
      "commitTitle": "refactor(analytics): cut over user tracking indexes",
      "commitCount": 1,
      "commitShas": [
        "806753aee0f5fb8e62824be5acb0cf8609c3d0a8"
      ],
      "committedAt": "2026-05-08T06:28:31.000Z",
      "generatedAt": "2026-05-08T07:36:21.323Z",
      "committedAtUtc": "2026-05-08T06:28:31.000Z",
      "generatedAtUtc": "2026-05-08T07:36:21.323Z",
      "updatedAtUtc": "2026-05-08T07:36:21.323Z",
      "category": "Improved",
      "title": "Bug fixes and quality-of-life improvements",
      "summary": "Bug fixes and quality-of-life improvements.",
      "userFacingTitle": "Bug fixes and quality-of-life improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Fixed beta issues to make KandyDrops smoother to use.",
        "Improved reliability for the latest Beta build."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "app"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/state/user-tracking-index-cutover.generated.json",
        "docs/agent-truth/analytics-truth-layer-v2.md",
        "docs/agent-truth/behavioral-math-calibration.md",
        "docs/agent-truth/guest-user-analytics-cutover.md",
        "docs/agent-truth/user-tracking-indexes.md",
        "package.json",
        "scripts/agent/score-user-tracking-indexes.ts",
        "scripts/agent/validate-user-tracking-index-cutover.ts",
        "src/app/api/analytics/ingest-identified/route.ts",
        "src/app/api/analytics/ingest/route.ts",
        "src/lib/server/analytics-governance.ts",
        "src/lib/server/analytics-identity-linking.ts",
        "src/lib/server/user-index-materializer.ts",
        "src/lib/server/user-index-reader.ts",
        "src/lib/server/user-index-writer.ts",
        "src/lib/user-indexes/user-index-legacy-registry.ts",
        "src/lib/user-indexes/user-index-normalizer.ts",
        "src/lib/user-indexes/user-tracking-index-contract.ts",
        "tests/unit/analytics-ingest-identified-route.spec.ts",
        "tests/unit/user-index-normalizer.spec.ts"
      ],
      "effectiveChangeCount": 988,
      "excludedGeneratedChangeCount": 84,
      "bumpType": "minor",
      "sourceCommit": "806753aee0f5fb8e62824be5acb0cf8609c3d0a8"
    },
    {
      "version": "1.11.0",
      "previousVersion": "1.10.0",
      "betaReleaseCounter": 213,
      "previousBetaReleaseCounter": 212,
      "commitSha": "91a9ccbafc5c595a02b1f2b50fe4450fd2eeb030",
      "commitTitle": "refactor(analytics): consolidate guest user tracking",
      "commitCount": 1,
      "commitShas": [
        "91a9ccbafc5c595a02b1f2b50fe4450fd2eeb030"
      ],
      "committedAt": "2026-05-08T06:18:01.000Z",
      "generatedAt": "2026-05-08T07:36:21.139Z",
      "committedAtUtc": "2026-05-08T06:18:01.000Z",
      "generatedAtUtc": "2026-05-08T07:36:21.139Z",
      "updatedAtUtc": "2026-05-08T07:36:21.139Z",
      "category": "Improved",
      "title": "Bug fixes and quality-of-life improvements",
      "summary": "Bug fixes and quality-of-life improvements.",
      "userFacingTitle": "Bug fixes and quality-of-life improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Fixed beta issues to make KandyDrops smoother to use.",
        "Improved reliability for the latest Beta build."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "app"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/context/optimized-task-context.generated.json",
        "agent/state/guest-user-analytics-cutover.generated.json",
        "docs/agent-truth/analytics-truth-layer-v2.md",
        "docs/agent-truth/behavioral-math-calibration.md",
        "docs/agent-truth/global-cost-surfaces.md",
        "docs/agent-truth/guest-user-analytics-cutover.md",
        "docs/doctrine/kandydrops-google-analytics-cloud-doctrine.md",
        "package.json",
        "scripts/agent/score-guest-user-analytics-cutover.ts",
        "scripts/agent/validate-guest-user-analytics-cutover.ts",
        "src/app/api/analytics/ingest-identified/route.ts",
        "src/app/api/analytics/ingest/route.ts",
        "src/components/Analytics/DeepTracker.tsx",
        "src/lib/analytics/google-analytics-source-policy.ts",
        "src/lib/analytics/identity-link-contract.ts",
        "src/lib/behavioral/behavioral-confidence-v2.ts",
        "src/lib/behavioral/behavioral-timeline-contract.ts",
        "src/lib/behavioral/guest-user-behavior-contract.ts",
        "src/lib/runtime-facts/normalize-runtime-fact.ts",
        "src/lib/runtime-facts/runtime-fact-contract.ts",
        "src/lib/server/analytics-governance.ts",
        "src/lib/server/analytics-identity-linking.ts",
        "src/lib/server/behavioral-timeline-mapper.ts",
        "src/lib/server/behavioral-timeline-reader.ts",
        "src/lib/server/behavioral-timeline-writer.ts",
        "src/lib/server/guest-user-behavior-rollup.ts",
        "tests/unit/analytics-ingest-identified-route.spec.ts",
        "tests/unit/analytics-ingest-route.spec.ts",
        "tests/unit/behavioral-confidence-v2.spec.ts"
      ],
      "effectiveChangeCount": 1076,
      "excludedGeneratedChangeCount": 69,
      "bumpType": "minor",
      "sourceCommit": "91a9ccbafc5c595a02b1f2b50fe4450fd2eeb030"
    },
    {
      "version": "1.10.0",
      "previousVersion": "1.9.0",
      "betaReleaseCounter": 212,
      "previousBetaReleaseCounter": 211,
      "commitSha": "ba9015d2c2c589e1fb9420e1ae316ed9ad1c28e8",
      "commitTitle": "refactor(settings): split creator dashboard settings",
      "commitCount": 1,
      "commitShas": [
        "ba9015d2c2c589e1fb9420e1ae316ed9ad1c28e8"
      ],
      "committedAt": "2026-05-08T06:00:52.000Z",
      "generatedAt": "2026-05-08T07:36:20.948Z",
      "committedAtUtc": "2026-05-08T06:00:52.000Z",
      "generatedAtUtc": "2026-05-08T07:36:20.948Z",
      "updatedAtUtc": "2026-05-08T07:36:20.948Z",
      "category": "Improved",
      "title": "Improved navigation reliability",
      "summary": "Bug fixes and quality-of-life improvements for top-level navigation and Beta update access.",
      "userFacingTitle": "Improved navigation reliability",
      "surfaceCategory": "Navigation",
      "bullets": [
        "Improved how key app navigation surfaces stay in sync with the latest Beta build.",
        "Reduced confusing status changes when opening update notes and top-level navigation lanes."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "account-onboarding",
        "creator",
        "navigation"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/context/optimized-task-context.generated.json",
        "agent/state/settings-creator-dashboard-split.generated.json",
        "docs/agent-truth/creator-broadcasts.md",
        "docs/agent-truth/creator-dashboard-settings.md",
        "docs/agent-truth/creator-dashboard.md",
        "docs/agent-truth/creator-fan-experience-settings.md",
        "docs/agent-truth/creator-lane-old-logic-cleanup.md",
        "docs/agent-truth/user-settings-surface.md",
        "docs/doctrine/surfaces/creator-ui-doctrine.md",
        "docs/doctrine/surfaces/user-ui-doctrine.md",
        "package.json",
        "scripts/agent/validate-settings-creator-dashboard-split.ts",
        "src/app/account/page.tsx",
        "src/app/api/creator/broadcasts/route.ts",
        "src/app/creator/page.tsx",
        "src/app/creators/dashboard/page.tsx",
        "src/app/dashboard/creator/page.tsx",
        "src/app/dashboard/profile/creator/page.tsx",
        "src/app/dashboard/profile/hooks/useProfileState.tsx",
        "src/app/dashboard/profile/page.tsx",
        "src/app/dashboard/settings/page.tsx",
        "src/app/profile/settings/page.tsx",
        "src/app/settings/page.tsx",
        "src/components/Creators/CreatorBroadcastManager.tsx",
        "src/components/Creators/CreatorDashboardSettingsHub.tsx",
        "src/components/Navigation/ProfileDropdown.tsx",
        "src/components/Navigation/ProfileSidebar.tsx",
        "src/components/Settings/UserSettingsPage.tsx",
        "src/lib/creator-dashboard/creator-settings-contract.ts",
        "src/lib/creator-dashboard/creator-settings-legacy-registry.ts",
        "src/lib/settings/settings-surface-policy.ts",
        "src/lib/settings/user-settings-contract.ts",
        "src/lib/telemetry-catalog.ts",
        "tests/unit/creator-broadcast-manager.spec.tsx",
        "tests/unit/creator-broadcasts-route.spec.ts",
        "tests/unit/creator-dashboard-settings.spec.tsx",
        "tests/unit/creator-settings-migration-page.spec.tsx",
        "tests/unit/creator-settings-route.spec.ts",
        "tests/unit/user-settings-split.spec.tsx"
      ],
      "effectiveChangeCount": 2629,
      "excludedGeneratedChangeCount": 146,
      "bumpType": "minor",
      "sourceCommit": "ba9015d2c2c589e1fb9420e1ae316ed9ad1c28e8"
    },
    {
      "version": "1.9.0",
      "previousVersion": "1.8.0",
      "betaReleaseCounter": 211,
      "previousBetaReleaseCounter": 210,
      "commitSha": "4c66907a1bacb3e1c65e1e9b862fe8674b7c0f6d",
      "commitTitle": "refactor(tasks): replace daily task engine",
      "commitCount": 1,
      "commitShas": [
        "4c66907a1bacb3e1c65e1e9b862fe8674b7c0f6d"
      ],
      "committedAt": "2026-05-08T05:34:18.000Z",
      "generatedAt": "2026-05-08T07:36:20.763Z",
      "committedAtUtc": "2026-05-08T05:34:18.000Z",
      "generatedAtUtc": "2026-05-08T07:36:20.763Z",
      "updatedAtUtc": "2026-05-08T07:36:20.763Z",
      "category": "Improved",
      "title": "Improved daily task reliability",
      "summary": "Bug fixes and quality-of-life improvements for daily tasks and check-ins.",
      "userFacingTitle": "Improved daily task reliability",
      "surfaceCategory": "Daily tasks",
      "bullets": [
        "Improved daily task reliability so check-ins and task progress stay clearer.",
        "Reduced confusing refresh states around daily rewards and task completion."
      ],
      "audience": "users",
      "affectedSurfaces": [
        "account-onboarding",
        "daily-tasks"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/context/optimized-task-context.generated.json",
        "docs/agent-truth/daily-task-engine.md",
        "docs/agent-truth/daily-task-pipeline.md",
        "docs/agent-truth/gumdrop-source-of-funds-truth.md",
        "docs/agent-truth/user-critical-path-lock.md",
        "package.json",
        "scripts/agent/validate-daily-task-engine-rewrite.ts",
        "src/app/api/tasks/rotate/route.ts",
        "src/components/Dashboard/DailyTasksModule.tsx",
        "src/lib/server/daily-task-runtime.ts",
        "src/lib/server/daily-tasks.ts",
        "src/lib/tasks/daily-task-assignment-engine.ts",
        "src/lib/tasks/daily-task-legacy-registry.ts",
        "src/lib/tasks/daily-task-reward-contract.ts",
        "src/lib/tasks/daily-task-window-contract.ts",
        "src/lib/tasks/task-catalog.ts",
        "src/lib/tasks/task-observability.ts",
        "src/lib/telemetry-catalog.ts",
        "tests/unit/daily-task-engine.spec.ts",
        "tests/unit/daily-tasks-idempotency.spec.ts"
      ],
      "effectiveChangeCount": 1923,
      "excludedGeneratedChangeCount": 2,
      "bumpType": "minor",
      "sourceCommit": "4c66907a1bacb3e1c65e1e9b862fe8674b7c0f6d"
    },
    {
      "version": "1.8.0",
      "previousVersion": "1.8.0",
      "betaReleaseCounter": 210,
      "previousBetaReleaseCounter": 210,
      "commitSha": "62d7e69a60420dd25175123378fc51aca5f905c3",
      "commitTitle": "fix(admin): stabilize batch drop uploads",
      "commitCount": 1,
      "commitShas": [
        "62d7e69a60420dd25175123378fc51aca5f905c3"
      ],
      "committedAt": "2026-05-08T05:04:04.000Z",
      "generatedAt": "2026-05-08T07:36:20.567Z",
      "committedAtUtc": "2026-05-08T05:04:04.000Z",
      "generatedAtUtc": "2026-05-08T07:36:20.567Z",
      "updatedAtUtc": "2026-05-08T07:36:20.567Z",
      "category": "Internal Reliability",
      "title": "Internal reliability improvements",
      "summary": "Internal reliability updates with no user-facing product changes.",
      "userFacingTitle": "Internal reliability improvements",
      "surfaceCategory": "Internal reliability",
      "bullets": [
        "Improved behind-the-scenes reliability."
      ],
      "audience": "admins",
      "affectedSurfaces": [
        "app"
      ],
      "hiddenFromPublic": true,
      "changedFiles": [
        "agent/context/optimized-task-context.generated.json",
        "docs/agent-truth/admin-cms-drop-workflow.md",
        "docs/agent-truth/content-media-pipeline.md",
        "package.json",
        "scripts/agent/validate-batch-upload-stability.ts",
        "src/components/Admin/AssetUploader.tsx",
        "src/components/Admin/CreateDropModal.tsx",
        "src/lib/telemetry-catalog.ts",
        "src/lib/uploads/asset-upload-draft-contract.ts",
        "src/lib/uploads/asset-upload-queue.ts",
        "src/lib/uploads/upload-error-copy.ts",
        "tests/unit/asset-upload-queue.spec.ts",
        "tests/unit/asset-uploader.spec.tsx",
        "tests/unit/create-drop-modal-upload-block.spec.tsx"
      ],
      "effectiveChangeCount": 942,
      "excludedGeneratedChangeCount": 2,
      "bumpType": "none",
      "sourceCommit": "62d7e69a60420dd25175123378fc51aca5f905c3"
    },
    {
      "version": "1.8.0",
      "previousVersion": "1.7.0",
      "betaReleaseCounter": 210,
      "previousBetaReleaseCounter": 209,
      "commitSha": "d98c3265883d906f60ad8218b1863184935ca438",
      "commitTitle": "chore(phase-one): gate user creator readiness",
      "commitCount": 1,
      "commitShas": [
        "d98c3265883d906f60ad8218b1863184935ca438"
      ],
      "committedAt": "2026-05-08T04:44:40.000Z",
      "generatedAt": "2026-05-08T07:36:20.376Z",
      "committedAtUtc": "2026-05-08T04:44:40.000Z",
      "generatedAtUtc": "2026-05-08T07:36:20.376Z",
      "updatedAtUtc": "2026-05-08T07:36:20.376Z",
      "category": "Fixed",
      "title": "Bug fixes and quality-of-life improvements",
      "summary": "Bug fixes and quality-of-life improvements.",
      "userFacingTitle": "Bug fixes and quality-of-life improvements",
      "surfaceCategory": "App experience",
      "bullets": [
        "Fixed beta issues to make KandyDrops smoother to use.",
        "Improved reliability for the latest Beta build."
      ],
      "audience": "creators",
      "affectedSurfaces": [
        "app"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/state/creator-dashboard-projection-lock.generated.json",
        "agent/state/creator-monetization-gates-lock.generated.json",
        "agent/state/creator-public-profile-lock.generated.json",
        "agent/state/user-creator-phase-one.generated.json",
        "agent/state/user-critical-path-lock.generated.json",
        "docs/agent-truth/user-creator-phase-one.md",
        "package.json",
        "scripts/agent/validate-creator-public-profile-lock.ts",
        "scripts/agent/validate-user-creator-phase-one.ts",
        "src/components/Chat/ChatRouteShell.tsx"
      ],
      "effectiveChangeCount": 341,
      "excludedGeneratedChangeCount": 351,
      "bumpType": "minor",
      "sourceCommit": "d98c3265883d906f60ad8218b1863184935ca438"
    },
    {
      "version": "1.7.0",
      "previousVersion": "1.6.0",
      "betaReleaseCounter": 209,
      "previousBetaReleaseCounter": 208,
      "commitSha": "01fae23380ae2345f672983f680dadb1b88fd6b8",
      "commitTitle": "fix(creator): guide monetization access",
      "commitCount": 1,
      "commitShas": [
        "01fae23380ae2345f672983f680dadb1b88fd6b8"
      ],
      "committedAt": "2026-05-08T04:34:46.000Z",
      "generatedAt": "2026-05-08T07:36:20.196Z",
      "committedAtUtc": "2026-05-08T04:34:46.000Z",
      "generatedAtUtc": "2026-05-08T07:36:20.196Z",
      "updatedAtUtc": "2026-05-08T07:36:20.196Z",
      "category": "Fixed",
      "title": "Improved chat and support reliability",
      "summary": "Bug fixes and quality-of-life improvements for chat and support.",
      "userFacingTitle": "Improved chat and support reliability",
      "surfaceCategory": "Chat & support",
      "bullets": [
        "Improved chat and support reliability so common actions feel more stable.",
        "Reduced stuck or confusing states in active support and messaging flows."
      ],
      "audience": "users",
      "affectedSurfaces": [
        "chat-support",
        "creator"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/state/creator-monetization-gates-lock.generated.json",
        "docs/agent-truth/creator-monetization-gates-lock.md",
        "package.json",
        "scripts/agent/validate-creator-monetization-gates-lock.ts",
        "src/app/creators/[username]/CreatorProfileClient.tsx",
        "src/components/Creators/CreatorExperiencesPanel.tsx",
        "src/components/Creators/CreatorPaidGdGuidanceCard.tsx",
        "src/lib/chat-send-feedback.ts",
        "src/lib/problem-state-copy.ts"
      ],
      "effectiveChangeCount": 613,
      "excludedGeneratedChangeCount": 107,
      "bumpType": "minor",
      "sourceCommit": "01fae23380ae2345f672983f680dadb1b88fd6b8"
    },
    {
      "version": "1.6.0",
      "previousVersion": "1.5.0",
      "betaReleaseCounter": 208,
      "previousBetaReleaseCounter": 207,
      "commitSha": "e06a455b8856ec1e6656857736803f6b55fd1680",
      "commitTitle": "fix(creator): lock dashboard projection",
      "commitCount": 1,
      "commitShas": [
        "e06a455b8856ec1e6656857736803f6b55fd1680"
      ],
      "committedAt": "2026-05-08T04:24:27.000Z",
      "generatedAt": "2026-05-08T07:36:20.004Z",
      "committedAtUtc": "2026-05-08T04:24:27.000Z",
      "generatedAtUtc": "2026-05-08T07:36:20.004Z",
      "updatedAtUtc": "2026-05-08T07:36:20.004Z",
      "category": "Fixed",
      "title": "Improved chat and support reliability",
      "summary": "Bug fixes and quality-of-life improvements for chat and support.",
      "userFacingTitle": "Improved chat and support reliability",
      "surfaceCategory": "Chat & support",
      "bullets": [
        "Improved chat and support reliability so common actions feel more stable.",
        "Reduced stuck or confusing states in active support and messaging flows."
      ],
      "audience": "users",
      "affectedSurfaces": [
        "account-onboarding",
        "admin",
        "chat-support",
        "creator"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/context/doctrine.index.json",
        "agent/context/file-size-budget.json",
        "agent/context/legacy-registry.json",
        "agent/context/task-pack.generated.json",
        "agent/context/validator-map.json",
        "agent/index/blast-radius.json",
        "agent/index/canonical-helpers.json",
        "agent/index/dependency-graph.summary.json",
        "agent/index/governance-truth.json",
        "agent/index/known-pitfalls.json",
        "agent/index/package-manager-truth.json",
        "agent/index/recent-passes.json",
        "agent/index/repo-inventory.json",
        "agent/index/retrieval-index.json",
        "agent/index/runtime-observability.json",
        "agent/index/surface-map.json",
        "agent/index/ui-surface-coverage.json",
        "agent/index/verification-commands.json",
        "agent/index/workflow-guidance.json",
        "agent/prompts/task-issue-spec.generated.md",
        "agent/prompts/task-prompt.deep.md",
        "agent/prompts/task-prompt.short.md",
        "agent/prompts/task-prompt.standard.md",
        "agent/prompts/verification-plan.generated.md",
        "agent/state/creator-dashboard-projection-lock.generated.json",
        "agent/state/fast-start.generated.json",
        "agent/state/task-context.generated.json",
        "agent/state/verification-plan.generated.json",
        "docs/agent-truth/creator-dashboard-projection-lock.md",
        "package.json",
        "scripts/agent/validate-creator-dashboard-projection-lock.ts",
        "src/app/api/admin/view-as-creator/route.ts",
        "src/app/api/chat/threads/route.ts",
        "src/app/api/creator/bookings/route.ts",
        "src/app/api/creator/broadcasts/route.ts",
        "src/app/api/creator/requests/route.ts",
        "src/app/api/creator/settings/route.ts",
        "src/app/api/creator/subscriptions/route.ts",
        "src/app/dashboard/DashboardClient.tsx",
        "src/app/dashboard/profile/components/ProfileAccountSection.tsx",
        "src/app/dashboard/profile/components/ProfileCreatorEarningsSection.tsx",
        "src/app/dashboard/profile/components/ProfileCreatorToolsSection.tsx",
        "src/app/dashboard/profile/components/ProfileNotificationsSection.tsx",
        "src/app/dashboard/profile/components/ProfilePrivacyDataSection.tsx",
        "src/app/dashboard/profile/components/ProfileProfileSection.tsx",
        "src/app/dashboard/profile/hooks/useProfileState.tsx",
        "src/app/dashboard/profile/page.tsx",
        "src/components/Dashboard/CreatorWorkspacePanel.tsx",
        "src/context/AdminViewAsContext.tsx",
        "src/lib/server/admin-creator-projection.ts"
      ],
      "effectiveChangeCount": 1496,
      "excludedGeneratedChangeCount": 829,
      "bumpType": "minor",
      "sourceCommit": "e06a455b8856ec1e6656857736803f6b55fd1680"
    },
    {
      "version": "1.5.0",
      "previousVersion": "1.4.0",
      "betaReleaseCounter": 207,
      "previousBetaReleaseCounter": 206,
      "commitSha": "73aa7213efd05290a0504106a15eaa290a7cc654",
      "commitTitle": "fix(creator): lock public creator profile",
      "commitCount": 1,
      "commitShas": [
        "73aa7213efd05290a0504106a15eaa290a7cc654"
      ],
      "committedAt": "2026-05-08T03:54:17.000Z",
      "generatedAt": "2026-05-08T07:36:19.703Z",
      "committedAtUtc": "2026-05-08T03:54:17.000Z",
      "generatedAtUtc": "2026-05-08T07:36:19.703Z",
      "updatedAtUtc": "2026-05-08T07:36:19.703Z",
      "category": "Fixed",
      "title": "Improved creator messaging and support tools",
      "summary": "Bug fixes and quality-of-life improvements for creator-facing experiences.",
      "userFacingTitle": "Improved creator messaging and support tools",
      "surfaceCategory": "Creator tools",
      "bullets": [
        "Improved creator-facing communication and support flows.",
        "Reduced confusing states around creator experience updates."
      ],
      "audience": "creators",
      "affectedSurfaces": [
        "creator"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/context/doctrine.cards.jsonl",
        "agent/context/doctrine.index.json",
        "agent/context/file-size-budget.json",
        "agent/context/legacy-registry.json",
        "agent/context/surface-contracts.jsonl",
        "agent/context/task-pack.generated.json",
        "agent/context/validator-map.json",
        "agent/index/blast-radius.json",
        "agent/index/canonical-helpers.json",
        "agent/index/dependency-graph.summary.json",
        "agent/index/governance-truth.json",
        "agent/index/known-pitfalls.json",
        "agent/index/package-manager-truth.json",
        "agent/index/recent-passes.json",
        "agent/index/repo-inventory.json",
        "agent/index/retrieval-index.json",
        "agent/index/runtime-observability.json",
        "agent/index/surface-map.json",
        "agent/index/ui-surface-coverage.json",
        "agent/index/verification-commands.json",
        "agent/index/workflow-guidance.json",
        "agent/prompts/task-issue-spec.generated.md",
        "agent/prompts/task-prompt.deep.md",
        "agent/prompts/task-prompt.short.md",
        "agent/prompts/task-prompt.standard.md",
        "agent/prompts/verification-plan.generated.md",
        "agent/state/creator-public-profile-lock.generated.json",
        "agent/state/fast-start.generated.json",
        "agent/state/task-context.generated.json",
        "agent/state/verification-plan.generated.json",
        "docs/agent-truth/creator-public-profile-lock.md",
        "package.json",
        "scripts/agent/validate-creator-public-profile-lock.ts",
        "src/app/api/creator/requests/route.ts",
        "src/app/creators/[username]/CreatorProfileClient.tsx",
        "src/components/Creators/CreatorExperiencesPanel.tsx",
        "src/components/Creators/CreatorProfileHeader.tsx",
        "src/lib/problem-state-copy.ts"
      ],
      "effectiveChangeCount": 3598,
      "excludedGeneratedChangeCount": 1115,
      "bumpType": "minor",
      "sourceCommit": "73aa7213efd05290a0504106a15eaa290a7cc654"
    },
    {
      "version": "1.4.0",
      "previousVersion": "1.3.0",
      "betaReleaseCounter": 206,
      "previousBetaReleaseCounter": 205,
      "commitSha": "75fd7d6e5b2d6cdcdd03a035aa8945311752b4f3",
      "commitTitle": "fix(user): lock public critical path",
      "commitCount": 1,
      "commitShas": [
        "75fd7d6e5b2d6cdcdd03a035aa8945311752b4f3"
      ],
      "committedAt": "2026-05-08T03:35:22.000Z",
      "generatedAt": "2026-05-08T07:36:19.290Z",
      "committedAtUtc": "2026-05-08T03:35:22.000Z",
      "generatedAtUtc": "2026-05-08T07:36:19.290Z",
      "updatedAtUtc": "2026-05-08T07:36:19.290Z",
      "category": "Fixed",
      "title": "Improved chat and support reliability",
      "summary": "Bug fixes and quality-of-life improvements for chat and support.",
      "userFacingTitle": "Improved chat and support reliability",
      "surfaceCategory": "Chat & support",
      "bullets": [
        "Improved chat and support reliability so common actions feel more stable.",
        "Reduced stuck or confusing states in active support and messaging flows."
      ],
      "audience": "users",
      "affectedSurfaces": [
        "chat-support"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "agent/state/user-critical-path-lock.generated.json",
        "docs/agent-truth/user-critical-path-lock.md",
        "package.json",
        "scripts/agent/validate-user-critical-path-lock.ts",
        "src/app/HomeClient.tsx",
        "src/components/Chat/ChatExperience.tsx",
        "src/components/Support/SupportInbox.tsx",
        "src/lib/chat-send-feedback.ts",
        "tests/unit/chat-send-feedback.spec.ts"
      ],
      "effectiveChangeCount": 481,
      "excludedGeneratedChangeCount": 103,
      "bumpType": "minor",
      "sourceCommit": "75fd7d6e5b2d6cdcdd03a035aa8945311752b4f3"
    },
    {
      "version": "1.3.0",
      "previousVersion": "1.3.0",
      "betaReleaseCounter": 205,
      "previousBetaReleaseCounter": 205,
      "commitSha": "479c9466093e85346f67914e4bcbdff395ef5126",
      "commitTitle": "chore(phase-one): add lock gate",
      "commitCount": 1,
      "commitShas": [
        "479c9466093e85346f67914e4bcbdff395ef5126"
      ],
      "committedAt": "2026-05-08T03:20:58.000Z",
      "generatedAt": "2026-05-08T07:36:19.061Z",
      "committedAtUtc": "2026-05-08T03:20:58.000Z",
      "generatedAtUtc": "2026-05-08T07:36:19.061Z",
      "updatedAtUtc": "2026-05-08T07:36:19.061Z",
      "category": "Internal Reliability",
      "title": "Internal reliability improvements",
      "summary": "Internal reliability updates with no user-facing product changes.",
      "userFacingTitle": "Internal reliability improvements",
      "surfaceCategory": "Internal reliability",
      "bullets": [
        "Improved behind-the-scenes reliability."
      ],
      "audience": "all",
      "affectedSurfaces": [
        "app"
      ],
      "hiddenFromPublic": true,
      "changedFiles": [
        "agent/context/optimized-task-context.generated.json",
        "agent/state/phase-one-lock.generated.json",
        "docs/agent-truth/phase-one-lock.md",
        "scripts/agent/validate-phase-one-lock.ts"
      ],
      "effectiveChangeCount": 993,
      "excludedGeneratedChangeCount": 153,
      "bumpType": "none",
      "sourceCommit": "479c9466093e85346f67914e4bcbdff395ef5126"
    }
  ]
} satisfies PublicReleaseNotesDocument;

export const PUBLIC_RELEASE_NOTES_VERSION_CONTEXT = {
  betaReleaseCounter: PUBLIC_RELEASE_NOTES_FALLBACK.betaReleaseCounter,
  appVersion: PUBLIC_RELEASE_NOTES_FALLBACK.currentVersion,
  releaseChannel: PUBLIC_RELEASE_NOTES_FALLBACK.channel,
} as const;

export const PUBLIC_APP_VERSION = PUBLIC_RELEASE_NOTES_VERSION_CONTEXT.appVersion;
