import type { PublicReleaseNotesDocument } from "./release-version-contract";

export const PUBLIC_RELEASE_NOTES_FALLBACK = {
  "currentVersion": "1.5.11",
  "betaReleaseCounter": 511,
  "channel": "beta",
  "generatedAt": "2026-05-27T00:30:00.000Z",
  "generatedAtUtc": "2026-05-27T00:30:00.000Z",
  "lastCommitSha": "pending-same-commit",
  "notes": [
    {
      "version": "1.5.11",
      "previousVersion": "1.5.10",
      "betaReleaseCounter": 511,
      "previousBetaReleaseCounter": 510,
      "commitSha": "pending-same-commit",
      "commitTitle": "fix(beta): close final exit blockers",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-27T00:30:00.000Z",
      "generatedAt": "2026-05-27T00:30:00.000Z",
      "committedAtUtc": "2026-05-27T00:30:00.000Z",
      "generatedAtUtc": "2026-05-27T00:30:00.000Z",
      "category": "Improved",
      "title": "Final beta-exit closure",
      "updatedAtUtc": "2026-05-27T00:30:00.000Z",
      "summary": "Resolved final source-side security PR blockers, classified remaining PRs, and refreshed beta-exit evidence without claiming missing formal proof.",
      "userFacingTitle": "Final beta-exit closure",
      "surfaceCategory": "App experience",
      "bullets": [
        "Resolved final security PR blockers and refreshed beta-exit evidence.",
        "Classified or deferred remaining PRs for beta-exit hygiene.",
        "Refreshed current-head score and final operator evidence packet.",
        "Kept runtime/provider/admin formal gates honest."
      ],
      "audience": "all",
      "technicalDetails": [
        "Ported source-equivalent security, performance, and accessibility PR fixes without scratch files.",
        "Closed or deferred open PRs with explicit beta-exit classifications.",
        "Kept provider/runtime/admin/operator evidence gates formal-required until human artifacts are attached."
      ],
      "affectedSurfaces": [
        "Security PR closure",
        "Open PR closure",
        "Final operator evidence packet",
        "Current-head score refresh",
        "Release readiness packet"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/final-open-pr-closure.generated.json",
        "agent/state/final-operator-evidence-needed.generated.json",
        "agent/state/security-prng-redirect-closure.generated.json",
        "scripts/agent/validate-security-prng-redirect-closure.ts",
        "src/lib/release-readiness/final-beta-exit-closure.ts"
      ],
      "effectiveChangeCount": 6,
      "excludedGeneratedChangeCount": 8,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.5.10",
      "previousVersion": "1.5.9",
      "betaReleaseCounter": 510,
      "previousBetaReleaseCounter": 509,
      "commitSha": "pending-same-commit",
      "commitTitle": "docs(release): add truth reconciliation",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T21:30:00.000Z",
      "generatedAt": "2026-05-26T21:30:00.000Z",
      "committedAtUtc": "2026-05-26T21:30:00.000Z",
      "generatedAtUtc": "2026-05-26T21:30:00.000Z",
      "category": "Improved",
      "title": "Automated truth reconciliation",
      "updatedAtUtc": "2026-05-26T21:30:00.000Z",
      "summary": "Added automated readiness audits that verify claimed release evidence against source, validators, wiring, score freshness, cost risk, and manual-QA gates.",
      "userFacingTitle": "Automated truth reconciliation",
      "surfaceCategory": "App experience",
      "bullets": [
        "Added automated truth reconciliation to audit claimed readiness, validator authority, wiring completeness, score freshness, cost risk, and manual-QA readiness.",
        "Blocked manual QA recommendation until release-critical automated gaps and PR/security hygiene are resolved.",
        "Kept formal provider/runtime/admin evidence gates honest."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added source-only claim, validator authority, wiring, score, half-implementation, cost, and manual-QA readiness reports.",
        "Classified formal runtime/provider/admin and operator visual QA gates without clearing them.",
        "Kept security PRs visible as blockers before manual QA can start."
      ],
      "affectedSurfaces": [
        "Automated truth reconciliation",
        "Validator authority audit",
        "Wiring truth audit",
        "Manual QA readiness gate",
        "Cost risk evidence"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/automated-truth-reconciliation.generated.json",
        "docs/agent-truth/automated-truth-reconciliation.md",
        "scripts/agent/validate-automated-truth-reconciliation.ts",
        "src/lib/release-readiness/automated-truth-reconciliation.ts"
      ],
      "effectiveChangeCount": 5,
      "excludedGeneratedChangeCount": 14,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.5.9",
      "previousVersion": "1.5.8",
      "betaReleaseCounter": 509,
      "previousBetaReleaseCounter": 508,
      "commitSha": "pending-same-commit",
      "commitTitle": "docs(release): finalize exit evidence",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T17:20:00.000Z",
      "generatedAt": "2026-05-26T17:20:00.000Z",
      "committedAtUtc": "2026-05-26T17:20:00.000Z",
      "generatedAtUtc": "2026-05-26T17:20:00.000Z",
      "category": "Improved",
      "title": "Release evidence finalization",
      "updatedAtUtc": "2026-05-26T17:20:00.000Z",
      "summary": "Prepared final release evidence, rollback readiness, operator QA, and beta-exit review packets without claiming missing formal proof.",
      "userFacingTitle": "Release evidence finalization",
      "surfaceCategory": "App experience",
      "bullets": [
        "Added final release evidence, runtime smoke harness, PR hygiene, rollback, operator QA, and beta exit readiness packet.",
        "Classified formal provider/runtime/admin evidence without faking proof.",
        "Prepared release notes and rollback readiness for operator-final beta exit review."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added source-safe release-readiness reports for current-head reconciliation, formal evidence status, PR/dependency hygiene, runtime harness, admin truth redaction, operator QA, rollback, release notes integrity, and final exit readiness.",
        "Kept runtime/provider/admin formal gates blocked until redacted formal artifacts exist.",
        "Classified open security, performance, accessibility, governance, and dependency PRs without blind merges."
      ],
      "affectedSurfaces": [
        "Release readiness evidence",
        "Runtime smoke harness",
        "Admin truth redaction packet",
        "Open PR dependency hygiene",
        "Rollback and incident readiness",
        "Operator final QA packet"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/final-release-exit-readiness-packet.generated.json",
        "docs/agent-truth/final-release-exit-readiness-packet.md",
        "scripts/agent/validate-final-release-exit-readiness-packet.ts",
        "src/lib/release-readiness/final-release-readiness.ts"
      ],
      "effectiveChangeCount": 5,
      "excludedGeneratedChangeCount": 18,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.5.8",
      "previousVersion": "1.5.7",
      "betaReleaseCounter": 508,
      "previousBetaReleaseCounter": 507,
      "commitSha": "pending-same-commit",
      "commitTitle": "fix(hardening): reinforce legacy pipelines",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T12:30:00.000Z",
      "generatedAt": "2026-05-26T12:30:00.000Z",
      "committedAtUtc": "2026-05-26T12:30:00.000Z",
      "generatedAtUtc": "2026-05-26T12:30:00.000Z",
      "category": "Improved",
      "title": "Legacy pipeline hardening",
      "updatedAtUtc": "2026-05-26T12:30:00.000Z",
      "summary": "Reinforced legacy cleanup, pipeline ownership, math normalization, cost hardening, and self-revealing debug evidence.",
      "userFacingTitle": "Legacy pipeline hardening",
      "surfaceCategory": "App experience",
      "bullets": [
        "Reinforced legacy, math, cost, debug, and pipeline ownership checks.",
        "Mapped stale logic into removal, canonical pipeline, legacy alias, dry-run recovery, or unsafe-unknown lanes.",
        "Kept production data, provider calls, payment runtime, and GumDrop pricing math unchanged."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added source-only hardening contracts for legacy inventory, pipeline ownership, global formula audits, legacy recovery dry-runs, cost accuracy, organization guardrails, and self-revealing findings.",
        "Generated debug-visible state and docs for the mega legacy pipeline hardening lock.",
        "Classified open PRs for external/current-source review without merging stale branches."
      ],
      "affectedSurfaces": [
        "Legacy pipeline inventory",
        "Pipeline ownership audit",
        "Global formula audit",
        "Cost accuracy hardening",
        "Self-revealing codebase evidence",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/codebase-organization-hardening.generated.json",
        "agent/state/codex-execution-guardrails.generated.json",
        "agent/state/cost-accuracy-hardening.generated.json",
        "agent/state/global-formula-audit.generated.json",
        "agent/state/legacy-canonical-recovery-plan.generated.json",
        "agent/state/legacy-pipeline-inventory.generated.json",
        "agent/state/mega-legacy-pipeline-hardening.generated.json",
        "agent/state/pipeline-ownership-audit.generated.json",
        "agent/state/self-revealing-codebase.generated.json",
        "docs/agent-truth/codebase-organization-hardening.md",
        "docs/agent-truth/codex-execution-guardrails.md",
        "docs/agent-truth/cost-accuracy-hardening.md",
        "docs/agent-truth/global-formula-audit.md",
        "docs/agent-truth/legacy-canonical-recovery-plan.md",
        "docs/agent-truth/legacy-pipeline-inventory.md",
        "docs/agent-truth/mega-legacy-pipeline-hardening.md",
        "docs/agent-truth/pipeline-ownership-audit.md",
        "docs/agent-truth/self-revealing-codebase.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-codebase-organization-hardening.ts",
        "scripts/agent/validate-mega-legacy-pipeline-hardening.ts",
        "src/lib/codebase-hardening/codebase-organization-hardening.ts",
        "src/lib/codebase-hardening/cost-accuracy-hardening.ts",
        "src/lib/codebase-hardening/legacy-canonical-recovery-plan.ts",
        "src/lib/codebase-hardening/legacy-pipeline-inventory.ts",
        "src/lib/codebase-hardening/pipeline-ownership-auditor.ts",
        "src/lib/codebase-hardening/pipeline-ownership-contract.ts",
        "src/lib/codebase-hardening/self-revealing-codebase-contract.ts",
        "src/lib/codebase-hardening/self-revealing-codebase-engine.ts",
        "src/lib/math/global-formula-audit.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/codebase-organization-hardening.spec.ts",
        "tests/unit/mega-legacy-pipeline-hardening.spec.ts"
      ],
      "effectiveChangeCount": 36,
      "excludedGeneratedChangeCount": 9,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.5.7",
      "previousVersion": "1.5.6",
      "betaReleaseCounter": 507,
      "previousBetaReleaseCounter": 506,
      "commitSha": "pending-same-commit",
      "commitTitle": "docs(math): lock normalization accuracy",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T12:00:00.000Z",
      "generatedAt": "2026-05-26T12:00:00.000Z",
      "committedAtUtc": "2026-05-26T12:00:00.000Z",
      "generatedAtUtc": "2026-05-26T12:00:00.000Z",
      "category": "Improved",
      "title": "Final math normalization lock",
      "updatedAtUtc": "2026-05-26T12:00:00.000Z",
      "summary": "Locked math normalization evidence across legacy recovery, source-of-funds, watch/session, cost/export, creator revenue, and metric display accuracy.",
      "userFacingTitle": "Final math normalization lock",
      "surfaceCategory": "App experience",
      "bullets": [
        "Locked global math normalization, legacy recovery, source-of-funds, watch/session, and display accuracy.",
        "Documented formula refinements and accuracy improvements.",
        "Kept production data, payment runtime, and GumDrop pricing math unchanged."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added a final math normalization lock report covering beta score, confidence, legacy recovery, global user counting, watch time, session bounce, GumDrop ledger, creator revenue, cost/export, and metric display formulas.",
        "Recorded dry-run-only legacy recovery status, unknown legacy handling, remaining formal gates, cost reviews, and exact next steps.",
        "Refreshed current beta exit status evidence without clearing runtime, provider, admin, or visual formal gates."
      ],
      "affectedSurfaces": [
        "Math normalization evidence",
        "Legacy recovery evidence",
        "Metric display accuracy evidence",
        "Beta score evidence",
        "Current beta exit status",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/current-beta-exit-status.generated.json",
        "agent/state/final-math-normalization-lock.generated.json",
        "agent/state/overnight-beta-readiness-lock.generated.json",
        "agent/state/public-beta-score.generated.json",
        "docs/agent-truth/current-beta-exit-status.md",
        "docs/agent-truth/final-math-normalization-lock.md",
        "docs/agent-truth/overnight-beta-readiness-lock.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-final-math-normalization-lock.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/final-math-normalization-lock.spec.ts"
      ],
      "effectiveChangeCount": 14,
      "excludedGeneratedChangeCount": 4,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.5.6",
      "previousVersion": "1.5.5",
      "betaReleaseCounter": 506,
      "previousBetaReleaseCounter": 505,
      "commitSha": "pending-same-commit",
      "commitTitle": "fix(math): improve metric display accuracy",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T11:40:00.000Z",
      "generatedAt": "2026-05-26T11:40:00.000Z",
      "committedAtUtc": "2026-05-26T11:40:00.000Z",
      "generatedAtUtc": "2026-05-26T11:40:00.000Z",
      "category": "Improved",
      "title": "Metric display accuracy",
      "updatedAtUtc": "2026-05-26T11:40:00.000Z",
      "summary": "Standardized metric display states so missing, stale, weak, and source-disconnected data no longer looks like exact zero.",
      "userFacingTitle": "Metric display accuracy",
      "surfaceCategory": "App experience",
      "bullets": [
        "Standardized metric display states across user, creator, and admin surfaces.",
        "Prevented missing or weak data from showing as exact zero.",
        "Added confidence and freshness-aware display rules."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added canonical metric display accuracy rules for exact, linked, estimated, collecting, proven zero, stale, not connected, unavailable, and hidden-by-permission states.",
        "Validated creator fans/drops/views, wallet source buckets, admin freshness/confidence labels, and user-safe copy.",
        "Kept production reads, deployment, payment runtime, and GumDrop math unchanged."
      ],
      "affectedSurfaces": [
        "Metric display accuracy math",
        "Creator dashboard metric display",
        "Wallet source bucket display",
        "Admin metric confidence display",
        "Beta score evidence",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/metric-display-accuracy.generated.json",
        "agent/state/public-beta-score.generated.json",
        "docs/agent-truth/metric-display-accuracy.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-metric-display-accuracy.ts",
        "src/lib/math/metric-display-accuracy.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/metric-display-accuracy.spec.ts"
      ],
      "effectiveChangeCount": 11,
      "excludedGeneratedChangeCount": 2,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.5.5",
      "previousVersion": "1.5.4",
      "betaReleaseCounter": 505,
      "previousBetaReleaseCounter": 504,
      "commitSha": "pending-same-commit",
      "commitTitle": "fix(math): finalize cost export parity",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T11:25:00.000Z",
      "generatedAt": "2026-05-26T11:25:00.000Z",
      "committedAtUtc": "2026-05-26T11:25:00.000Z",
      "generatedAtUtc": "2026-05-26T11:25:00.000Z",
      "category": "Improved",
      "title": "Cost export parity math",
      "updatedAtUtc": "2026-05-26T11:25:00.000Z",
      "summary": "Finalized cost, export, SQL parity, batching, and summary math while keeping external billing proof separate.",
      "userFacingTitle": "Cost export parity math",
      "surfaceCategory": "App experience",
      "bullets": [
        "Finalized cost, export, SQL parity, batching, and summary math.",
        "Protected metric accuracy while reducing duplicate reads, writes, and exports.",
        "Separated source cost guards from external billing proof."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added canonical cost/export parity math for daily watermark batch windows, summary freshness floors, admin read risk, hot-path risk, and source-vs-external cost readiness.",
        "Validated BigQuery per-event export remains blocked and Cloud SQL mirror sync stays manual/cost-approved only.",
        "Kept provider calls, exports, deployments, payment runtime, and GumDrop math unchanged."
      ],
      "affectedSurfaces": [
        "Cost export parity math",
        "SQL/Data Connect parity evidence",
        "BigQuery export guard evidence",
        "Admin debug cost summaries",
        "Beta score evidence",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/cost-export-sql-parity-math.generated.json",
        "agent/state/public-beta-score.generated.json",
        "docs/agent-truth/cost-export-sql-parity-math.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-cost-export-sql-parity-math.ts",
        "src/lib/math/cost-export-parity-math.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/cost-export-sql-parity-math.spec.ts"
      ],
      "effectiveChangeCount": 11,
      "excludedGeneratedChangeCount": 2,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.5.4",
      "previousVersion": "1.5.3",
      "betaReleaseCounter": 504,
      "previousBetaReleaseCounter": 503,
      "commitSha": "pending-same-commit",
      "commitTitle": "fix(math): finalize creator revenue",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T11:10:00.000Z",
      "generatedAt": "2026-05-26T11:10:00.000Z",
      "committedAtUtc": "2026-05-26T11:10:00.000Z",
      "generatedAtUtc": "2026-05-26T11:10:00.000Z",
      "category": "Improved",
      "title": "Creator revenue math",
      "updatedAtUtc": "2026-05-26T11:10:00.000Z",
      "summary": "Finalized creator revenue, Fan Pass access, paid chat bypass, and entitlement math without changing payment or payout runtime.",
      "userFacingTitle": "Creator revenue math",
      "surfaceCategory": "Creator tools",
      "bullets": [
        "Finalized creator revenue, Fan Pass, paid chat bypass, and entitlement math.",
        "Separated exact, linked, inferred, weak, and unknown revenue confidence.",
        "Prevented expired/refunded entitlements from remaining active."
      ],
      "audience": "creators",
      "technicalDetails": [
        "Added canonical creator revenue entitlement math for exact, linked, inferred, weak, and unknown confidence buckets.",
        "Validated Fan Pass active state against creator enablement, entitlement status, access window, lifetime entitlement, and refund/cancellation state.",
        "Kept payment runtime, payout formulas, PayPal capture, and GumDrop math unchanged."
      ],
      "affectedSurfaces": [
        "Creator revenue math",
        "Fan Pass access math",
        "Paid chat bypass math",
        "Creator dashboard metrics",
        "Beta score evidence",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/creator-revenue-entitlement-math.generated.json",
        "docs/agent-truth/creator-revenue-entitlement-math.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-creator-monetization-settings-truth.ts",
        "scripts/agent/validate-creator-revenue-entitlement-ledger.ts",
        "scripts/agent/validate-creator-revenue-entitlement-math.ts",
        "scripts/agent/validate-fan-pass-lifecycle.ts",
        "src/lib/math/creator-revenue-entitlement-math.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/creator-revenue-entitlement-math.spec.ts"
      ],
      "effectiveChangeCount": 13,
      "excludedGeneratedChangeCount": 1,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.5.3",
      "previousVersion": "1.5.2",
      "betaReleaseCounter": 503,
      "previousBetaReleaseCounter": 502,
      "commitSha": "pending-same-commit",
      "commitTitle": "fix(math): finalize gumdrop ledger",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T10:45:00.000Z",
      "generatedAt": "2026-05-26T10:45:00.000Z",
      "committedAtUtc": "2026-05-26T10:45:00.000Z",
      "generatedAtUtc": "2026-05-26T10:45:00.000Z",
      "category": "Improved",
      "title": "GumDrop ledger math",
      "updatedAtUtc": "2026-05-26T10:45:00.000Z",
      "summary": "Finalized GumDrop source-of-funds math so paid, bonus, reward, task, admin, refund, and legacy sources stay distinct.",
      "userFacingTitle": "GumDrop ledger math",
      "surfaceCategory": "Wallet",
      "bullets": [
        "Finalized GumDrop ledger math across paid, bonus, reward, task, admin, refund, and legacy sources.",
        "Prevented source-of-funds drift from affecting spend eligibility.",
        "Aligned wallet display labels with ledger source truth."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added canonical GumDrop ledger math for paid_gd, paid_bonus_gd, reward_gd, task_reward_gd, admin_grant_gd, adjustment_gd, refund_reversal, and legacy_unknown buckets.",
        "Validated paid-only spend eligibility against paid base and paid bonus sources while blocking reward, admin grant, and legacy unknown sources.",
        "Kept payment runtime, package prices, PayPal capture, and GumDrop package amounts unchanged."
      ],
      "affectedSurfaces": [
        "GumDrop ledger math",
        "Wallet source-of-funds truth",
        "Creator paid-only eligibility",
        "Beta score evidence",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/gumdrop-ledger-math.generated.json",
        "agent/state/public-beta-score.generated.json",
        "docs/agent-truth/gumdrop-ledger-math.md",
        "docs/agent-truth/payment-wallet-unlock-entitlement.md",
        "docs/doctrine/surfaces/wallet.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-gumdrop-ledger-math.ts",
        "scripts/agent/validate-wallet-density.ts",
        "src/components/PurchaseModal.tsx",
        "src/lib/math/canonical-math-ledger.ts",
        "src/lib/math/gumdrop-ledger-math.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/canonical-math-ledger.spec.ts",
        "tests/unit/gumdrop-ledger-math.spec.ts",
        "tests/unit/purchase-modal-density.spec.tsx"
      ],
      "effectiveChangeCount": 18,
      "excludedGeneratedChangeCount": 2,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.5.2",
      "previousVersion": "1.5.1",
      "betaReleaseCounter": 502,
      "previousBetaReleaseCounter": 501,
      "commitSha": "pending-same-commit",
      "commitTitle": "fix(math): finalize session journey math",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T10:30:00.000Z",
      "generatedAt": "2026-05-26T10:30:00.000Z",
      "committedAtUtc": "2026-05-26T10:30:00.000Z",
      "generatedAtUtc": "2026-05-26T10:30:00.000Z",
      "category": "Improved",
      "title": "App session reliability",
      "updatedAtUtc": "2026-05-26T10:30:00.000Z",
      "summary": "Improved session reliability so activity, idle time, and sign-in handoffs are counted consistently.",
      "userFacingTitle": "App session reliability",
      "surfaceCategory": "App experience",
      "bullets": [
        "Improved session activity, idle time, bounce, engagement, and journey duration tracking.",
        "Prevented hidden time and unknown closeouts from corrupting session metrics.",
        "Preserved guest-to-user session continuity."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added canonical session journey math for active, idle, hidden, bounce, engagement, journey duration, closeout, and guest-user handoff rules.",
        "Routed session metrics and journey duration calculations through the canonical math module without adding production reads.",
        "Kept payment, wallet, and GumDrop math unchanged."
      ],
      "affectedSurfaces": [
        "Session metrics",
        "User journey intelligence",
        "Person metrics hydration",
        "Debug session math lane",
        "Beta score evidence",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/public-beta-score.generated.json",
        "agent/state/session-journey-duration-math.generated.json",
        "docs/agent-truth/session-journey-duration-math.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-session-bounce-calculation.ts",
        "scripts/agent/validate-session-journey-duration-math.ts",
        "scripts/agent/validate-user-journey-behavioral-intelligence.ts",
        "src/lib/analytics/session-metrics-engine.ts",
        "src/lib/behavioral/user-journey-builder.ts",
        "src/lib/math/session-journey-math.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/session-journey-duration-math.spec.ts"
      ],
      "effectiveChangeCount": 15,
      "excludedGeneratedChangeCount": 2,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.5.1",
      "previousVersion": "1.5.0",
      "betaReleaseCounter": 501,
      "previousBetaReleaseCounter": 500,
      "commitSha": "pending-same-commit",
      "commitTitle": "fix(math): finalize drop watch math",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T10:15:00.000Z",
      "generatedAt": "2026-05-26T10:15:00.000Z",
      "committedAtUtc": "2026-05-26T10:15:00.000Z",
      "generatedAtUtc": "2026-05-26T10:15:00.000Z",
      "category": "Improved",
      "title": "Drop watch and unlock math",
      "updatedAtUtc": "2026-05-26T10:15:00.000Z",
      "summary": "Finalized drop open, unlock, unwrap, and watch-time math.",
      "userFacingTitle": "Drop watch and unlock math",
      "surfaceCategory": "Drops & viewer",
      "bullets": [
        "Finalized drop open, unlock, unwrap, and watch-time math.",
        "Separated active watch time from page duration.",
        "Added confidence and normalized completion rules for video and static drops."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added canonical drop watch/unlock math for open, unlock, unwrap, watch, completion, confidence, replay, and static review calculations.",
        "Routed the existing drop watch-time engine through canonical math and rejected pageDurationMs in the watch-session route.",
        "Separated server unlock telemetry from payload unwrap telemetry without changing GumDrop unlock price or spend math."
      ],
      "affectedSurfaces": [
        "Drop watch math",
        "Viewer watch-session route",
        "Drop unlock route telemetry",
        "Person metrics hydration",
        "Beta score evidence",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/drop-watch-unlock-math.generated.json",
        "agent/state/public-beta-score.generated.json",
        "docs/agent-truth/drop-watch-unlock-math.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-drop-watch-time-accuracy.ts",
        "scripts/agent/validate-drop-watch-unlock-math.ts",
        "scripts/agent/validate-unlock-telemetry-truth.ts",
        "src/app/api/drops/unlock/route.ts",
        "src/app/api/viewer/watch-session/route.ts",
        "src/lib/analytics/drop-watch-time-engine.ts",
        "src/lib/analytics/person-metrics-contract.ts",
        "src/lib/analytics/person-metrics-hydration.ts",
        "src/lib/behavioral/event-fact-normalizer.ts",
        "src/lib/behavioral/normalize-event-fact.ts",
        "src/lib/commerce/unlock-watch-parity-contract.ts",
        "src/lib/math/drop-watch-unlock-math.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "src/lib/telemetry-catalog.ts",
        "tests/unit/drop-watch-time-accuracy.spec.ts",
        "tests/unit/drop-watch-unlock-math.spec.ts"
      ],
      "effectiveChangeCount": 23,
      "excludedGeneratedChangeCount": 2,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.5.0",
      "previousVersion": "1.4.99",
      "betaReleaseCounter": 500,
      "previousBetaReleaseCounter": 499,
      "commitSha": "pending-same-commit",
      "commitTitle": "fix(math): normalize user global counts",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T10:00:00.000Z",
      "generatedAt": "2026-05-26T10:00:00.000Z",
      "committedAtUtc": "2026-05-26T10:00:00.000Z",
      "generatedAtUtc": "2026-05-26T10:00:00.000Z",
      "category": "Improved",
      "title": "Global user counting math",
      "updatedAtUtc": "2026-05-26T10:00:00.000Z",
      "summary": "Finalized global, guest, signed-in, linked-person, and creator-role counting math.",
      "userFacingTitle": "Global user counting math",
      "surfaceCategory": "App experience",
      "bullets": [
        "Finalized global, guest, signed-in, linked-person, and creator-role counting math.",
        "Added exact dedupe windows and duplicate suppression reasons.",
        "Prevented linked guest/user actions from inflating metrics."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added canonical global-user counting math for global, guest, signed-in, linked-person, and creator-role scopes.",
        "Routed person metrics through scope-aware dedupe decisions with duplicate suppression debug visibility.",
        "Kept payment runtime, GumDrop math, production data, provider calls, deploys, and navigation unchanged."
      ],
      "affectedSurfaces": [
        "Global user counting math",
        "Person metrics hydration",
        "Global user dedupe validator",
        "Beta score evidence",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/global-user-counting-math.generated.json",
        "agent/state/public-beta-score.generated.json",
        "docs/agent-truth/global-user-counting-math.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-global-user-counting-math.ts",
        "scripts/agent/validate-global-user-dedupe-normalization.ts",
        "scripts/agent/validate-person-metrics-hydration.ts",
        "src/lib/analytics/person-metrics-engine.ts",
        "src/lib/analytics/person-metrics-hydration.ts",
        "src/lib/math/global-user-counting-math.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/global-user-counting-math.spec.ts"
      ],
      "effectiveChangeCount": 15,
      "excludedGeneratedChangeCount": 2,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.4.99",
      "previousVersion": "1.4.98",
      "betaReleaseCounter": 499,
      "previousBetaReleaseCounter": 498,
      "commitSha": "pending-same-commit",
      "commitTitle": "fix(math): canonicalize legacy metrics",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T09:15:00.000Z",
      "generatedAt": "2026-05-26T09:15:00.000Z",
      "committedAtUtc": "2026-05-26T09:15:00.000Z",
      "generatedAtUtc": "2026-05-26T09:15:00.000Z",
      "category": "Improved",
      "title": "Legacy metric canonicalization",
      "updatedAtUtc": "2026-05-26T09:15:00.000Z",
      "summary": "Added dry-run canonicalization for legacy event and metric data from March 1.",
      "userFacingTitle": "Legacy metric canonicalization",
      "surfaceCategory": "App experience",
      "bullets": [
        "Added dry-run canonicalization for legacy event and metric data from March 1.",
        "Mapped old event aliases into current metrics with confidence and duplicate risk.",
        "Kept unknown legacy data from becoming exact user truth."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added legacy event and metric alias canonicalization for watch/page duration, drops, wallet/payment, auth, tasks, chat, notifications, creators, search, support, and settings.",
        "Added a dry-run recovery engine that emits candidate actions, confidence weights, duplicate risk, dedupe keys, and accuracy/user-visible impact without production reads or mutations.",
        "Kept payment runtime, GumDrop math, navigation, production data, provider calls, and deploys unchanged."
      ],
      "affectedSurfaces": [
        "Legacy metric canonicalization",
        "Legacy recovery dry-run engine",
        "Metric recovery validator",
        "Beta score evidence",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/metric-canonicalization-legacy-recovery.generated.json",
        "agent/state/public-beta-score.generated.json",
        "docs/agent-truth/metric-canonicalization-legacy-recovery.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-metric-canonicalization-legacy-recovery.ts",
        "src/lib/analytics/person-metrics-hydration.ts",
        "src/lib/math/legacy-metric-canonicalization.ts",
        "src/lib/math/legacy-recovery-dry-run-engine.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/metric-canonicalization-legacy-recovery.spec.ts"
      ],
      "effectiveChangeCount": 13,
      "excludedGeneratedChangeCount": 2,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.4.98",
      "previousVersion": "1.4.97",
      "betaReleaseCounter": 498,
      "previousBetaReleaseCounter": 497,
      "commitSha": "pending-same-commit",
      "commitTitle": "fix(math): create canonical ledger",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T09:00:00.000Z",
      "generatedAt": "2026-05-26T09:00:00.000Z",
      "committedAtUtc": "2026-05-26T09:00:00.000Z",
      "generatedAtUtc": "2026-05-26T09:00:00.000Z",
      "category": "Improved",
      "title": "Canonical math ledger freeze",
      "updatedAtUtc": "2026-05-26T09:00:00.000Z",
      "summary": "Created canonical math ledger for score, confidence, session, watch, dedupe, and legacy recovery formulas.",
      "userFacingTitle": "Canonical math ledger freeze",
      "surfaceCategory": "App experience",
      "bullets": [
        "Created canonical math ledger for score, confidence, session, watch, dedupe, and legacy recovery formulas.",
        "Fixed person-metric hydration gap math to report real gaps.",
        "Documented how formula refinements improve tracking accuracy."
      ],
      "audience": "all",
      "technicalDetails": [
        "Froze public beta score weights and identity confidence weights in a canonical ledger without changing payment, wallet, PayPal, or GumDrop runtime math.",
        "Mapped major formula owners for beta score, metrics, session, bounce, watch time, source-of-funds, entitlements, notifications, SQL parity, and legacy recovery.",
        "Added validator and unit coverage for proven-zero rules, non-event score rules, formula authority, and real person-metrics hydration gaps."
      ],
      "affectedSurfaces": [
        "Canonical math ledger",
        "Math authority map",
        "Person metrics hydration",
        "Beta score evidence",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/canonical-math-ledger.generated.json",
        "agent/state/public-beta-score.generated.json",
        "docs/agent-truth/canonical-math-ledger.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-canonical-math-ledger.ts",
        "src/lib/analytics/person-metrics-hydration.ts",
        "src/lib/math/canonical-math-ledger.ts",
        "src/lib/math/math-authority-map.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/canonical-math-ledger.spec.ts"
      ],
      "effectiveChangeCount": 13,
      "excludedGeneratedChangeCount": 2,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.4.97",
      "previousVersion": "1.4.96",
      "betaReleaseCounter": 497,
      "previousBetaReleaseCounter": 496,
      "commitSha": "pending-same-commit",
      "commitTitle": "fix(math): normalize count dedupe",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T08:45:00.000Z",
      "generatedAt": "2026-05-26T08:45:00.000Z",
      "committedAtUtc": "2026-05-26T08:45:00.000Z",
      "generatedAtUtc": "2026-05-26T08:45:00.000Z",
      "category": "Improved",
      "title": "Count deduplication normalization",
      "updatedAtUtc": "2026-05-26T08:45:00.000Z",
      "summary": "Normalized global, user, creator, and legacy count deduplication.",
      "userFacingTitle": "Count deduplication normalization",
      "surfaceCategory": "App experience",
      "bullets": [
        "Normalized global, user, creator, and legacy count deduplication.",
        "Prevented linked guest/user and retry events from inflating metrics.",
        "Added count formula references and debug explanations."
      ],
      "audience": "all",
      "technicalDetails": [
        "Aligned global/user summary dedupe keys with the canonical count normalizer fallback order: eventId, dedupeKey, then session/event/object/timestamp bucket.",
        "Added validator and unit coverage for linked guest/user suppression, legacy buckets, replay suppression, formula references, and timestamp-bucket fallback keys.",
        "Kept payment runtime, GumDrop math, production data, deploys, provider calls, and navigation unchanged."
      ],
      "affectedSurfaces": [
        "Count deduplication normalizer",
        "Global/user dedupe engine",
        "Behavioral event fact normalization",
        "Count dedupe debug evidence",
        "Beta score evidence",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/count-deduplication-normalization.generated.json",
        "agent/state/public-beta-score.generated.json",
        "docs/agent-truth/count-deduplication-normalization.md",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-count-deduplication-normalization.ts",
        "src/lib/analytics/global-user-dedupe-contract.ts",
        "src/lib/analytics/global-user-dedupe-engine.ts",
        "src/lib/behavioral/normalize-event-fact.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/count-deduplication-normalization.spec.ts"
      ],
      "effectiveChangeCount": 12,
      "excludedGeneratedChangeCount": 2,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.4.96",
      "previousVersion": "1.4.95",
      "betaReleaseCounter": 496,
      "previousBetaReleaseCounter": 495,
      "commitSha": "pending-same-commit",
      "commitTitle": "docs(math): add canonical authority ledger",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T08:30:00.000Z",
      "generatedAt": "2026-05-26T08:30:00.000Z",
      "committedAtUtc": "2026-05-26T08:30:00.000Z",
      "generatedAtUtc": "2026-05-26T08:30:00.000Z",
      "category": "Improved",
      "title": "Canonical math authority ledger",
      "updatedAtUtc": "2026-05-26T08:30:00.000Z",
      "summary": "Added canonical math authority ledger.",
      "userFacingTitle": "Canonical math authority ledger",
      "surfaceCategory": "App experience",
      "bullets": [
        "Added canonical math authority ledger.",
        "Inventoried formulas across score, metrics, sessions, watch time, GumDrops, revenue, and legacy recovery.",
        "Blocked unowned formulas from silently affecting user/admin metrics."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added freshness semantics to the canonical math authority contract so admin-facing formulas declare source freshness alongside source, confidence, and display policy.",
        "Updated the ledger validator, generated evidence, and unit coverage to fail admin-facing formulas that lack freshness rules.",
        "Kept payment runtime, GumDrop math, production data, provider calls, and navigation unchanged."
      ],
      "affectedSurfaces": [
        "Canonical math authority ledger",
        "Math authority validator",
        "Math authority generated evidence",
        "Beta score evidence",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/canonical-math-authority-ledger.generated.json",
        "docs/agent-truth/canonical-math-authority-ledger.md",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-canonical-math-authority-ledger.ts",
        "src/lib/math/canonical-math-authority-contract.ts",
        "src/lib/math/canonical-math-authority-ledger.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/canonical-math-authority-ledger.spec.ts"
      ],
      "effectiveChangeCount": 10,
      "excludedGeneratedChangeCount": 2,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.4.95",
      "previousVersion": "1.4.94",
      "betaReleaseCounter": 495,
      "previousBetaReleaseCounter": 494,
      "commitSha": "pending-same-commit",
      "commitTitle": "docs(integrity): lock product body wiring",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T08:10:00.000Z",
      "generatedAt": "2026-05-26T08:10:00.000Z",
      "committedAtUtc": "2026-05-26T08:10:00.000Z",
      "generatedAtUtc": "2026-05-26T08:10:00.000Z",
      "category": "Improved",
      "title": "Product integrity lock",
      "updatedAtUtc": "2026-05-26T08:10:00.000Z",
      "summary": "Locked product integrity body map, central normalizer, interpretive brain, and wiring repair.",
      "userFacingTitle": "Product integrity lock",
      "surfaceCategory": "App experience",
      "bullets": [
        "Locked product integrity body map, central normalizer, interpretive brain, and wiring repair.",
        "Connected major product limbs to telemetry, metrics, debug, journey, and score.",
        "Classified remaining gaps with owners and next actions."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added a final Product integrity lock lane over the product body map, central normalizer, interpretive brain, and wiring repair artifacts.",
        "Recorded body-system coverage, limb classifications, debug root-cause readiness, score dimensions, launch blockers, and exact next actions.",
        "Kept runtime, provider, payment, GumDrop, navigation, and formal beta-gate evidence unchanged."
      ],
      "affectedSurfaces": [
        "Product body map",
        "Central normalizer",
        "Product brain",
        "Body system wiring repair",
        "Admin Debug tracking summary",
        "Beta score evidence",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/final-product-integrity-lock.generated.json",
        "docs/agent-truth/final-product-integrity-lock.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-final-product-integrity-lock.ts",
        "src/lib/analytics/event-translation-bridge.ts",
        "src/lib/analytics/person-metrics-hydration.ts",
        "src/lib/product-integrity/body-system-wiring-repair.ts",
        "src/lib/product-integrity/central-normalizer.ts",
        "src/lib/product-integrity/final-product-integrity-lock.ts",
        "src/lib/product-integrity/interpretive-brain.ts",
        "src/lib/product-integrity/product-body-map.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/final-product-integrity-lock.spec.ts"
      ],
      "effectiveChangeCount": 16,
      "excludedGeneratedChangeCount": 2,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.4.94",
      "previousVersion": "1.4.93",
      "betaReleaseCounter": 494,
      "previousBetaReleaseCounter": 493,
      "commitSha": "pending-same-commit",
      "commitTitle": "fix(integrity): repair body system wiring",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T07:45:00.000Z",
      "generatedAt": "2026-05-26T07:45:00.000Z",
      "committedAtUtc": "2026-05-26T07:45:00.000Z",
      "generatedAtUtc": "2026-05-26T07:45:00.000Z",
      "category": "Improved",
      "title": "Body system wiring repair",
      "updatedAtUtc": "2026-05-26T07:45:00.000Z",
      "summary": "Repaired highest-impact disconnected product limbs across routes, telemetry, metrics, debug, and score.",
      "userFacingTitle": "Body system wiring repair",
      "surfaceCategory": "App experience",
      "bullets": [
        "Repaired highest-impact disconnected product limbs across routes, telemetry, metrics, debug, and score.",
        "Reduced duplicate truth sources and orphaned telemetry.",
        "Kept product runtime and monetization math unchanged."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added a Body system wiring repair lane that turns the runtime watch-time orphan into an owned deferred evidence gap without claiming fake runtime proof.",
        "Connected the repair lane to Product body map, Central normalizer, Product brain, Admin Debug, event translation, person metrics, and beta score evidence classifiers.",
        "Added source-only validation, generated evidence, documentation, and unit coverage without production reads, provider calls, payment runtime changes, GumDrop math changes, or navigation edits."
      ],
      "affectedSurfaces": [
        "Product body map",
        "Body system wiring repair",
        "Admin Debug tracking summary",
        "Central normalizer",
        "Product brain",
        "Event translation bridge",
        "Person metrics hydration",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/body-system-wiring-repair.generated.json",
        "agent/state/central-normalizer-spine.generated.json",
        "agent/state/event-translation-bridge.generated.json",
        "agent/state/feature-registration-gate.generated.json",
        "agent/state/interpretive-brain-debug-triage.generated.json",
        "agent/state/person-metrics-hydration.generated.json",
        "agent/state/product-body-map.generated.json",
        "docs/agent-truth/body-system-wiring-repair.md",
        "docs/agent-truth/central-normalizer-spine.md",
        "docs/agent-truth/event-translation-bridge.md",
        "docs/agent-truth/interpretive-brain-debug-triage.md",
        "docs/agent-truth/person-metrics-hydration.md",
        "docs/agent-truth/product-body-map.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-body-system-wiring-repair.ts",
        "src/lib/analytics/event-translation-bridge.ts",
        "src/lib/analytics/person-metrics-hydration.ts",
        "src/lib/debug/debug-panel-tracking-summary.ts",
        "src/lib/product-integrity/body-system-wiring-repair.ts",
        "src/lib/product-integrity/central-normalizer.ts",
        "src/lib/product-integrity/interpretive-brain.ts",
        "src/lib/product-integrity/product-body-map.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/body-system-wiring-repair.spec.ts"
      ],
      "effectiveChangeCount": 27,
      "excludedGeneratedChangeCount": 7,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.4.93",
      "previousVersion": "1.4.92",
      "betaReleaseCounter": 493,
      "previousBetaReleaseCounter": 492,
      "commitSha": "pending-same-commit",
      "commitTitle": "fix(debug): unify interpretive brain",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T07:25:00.000Z",
      "generatedAt": "2026-05-26T07:25:00.000Z",
      "committedAtUtc": "2026-05-26T07:25:00.000Z",
      "generatedAtUtc": "2026-05-26T07:25:00.000Z",
      "category": "Improved",
      "title": "Interpretive brain debug triage",
      "updatedAtUtc": "2026-05-26T07:25:00.000Z",
      "summary": "Unified debug triage around normalized product signals, root cause, score impact, and next actions.",
      "userFacingTitle": "Interpretive brain debug triage",
      "surfaceCategory": "App experience",
      "bullets": [
        "Added interpretive brain for normalized product signals.",
        "Unified debug triage around root cause, score impact, and next actions.",
        "Collapsed duplicate debug findings behind product health summary."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added typed interpretive brain contracts and source-only triage over normalized signals, journey facts, score signals, cost signals, formal gates, stale artifacts, and admin truth samples.",
        "Added Product brain as the first Admin Debug tracking summary lane while keeping raw debug lanes drilldown-only.",
        "Added validator evidence and unit coverage without production reads, provider calls, payment runtime changes, GumDrop math changes, or navigation changes."
      ],
      "affectedSurfaces": [
        "Product brain",
        "Admin Debug tracking summary",
        "Central normalizer",
        "Product body map",
        "Beta score evidence",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/interpretive-brain-debug-triage.generated.json",
        "docs/agent-truth/interpretive-brain-debug-triage.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-interpretive-brain-debug-triage.ts",
        "src/lib/debug/debug-panel-tracking-summary.ts",
        "src/lib/product-integrity/central-normalizer.ts",
        "src/lib/product-integrity/interpretive-brain-contract.ts",
        "src/lib/product-integrity/interpretive-brain.ts",
        "src/lib/product-integrity/product-body-map.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/interpretive-brain-debug-triage.spec.ts"
      ],
      "effectiveChangeCount": 14,
      "excludedGeneratedChangeCount": 1,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.4.92",
      "previousVersion": "1.4.91",
      "betaReleaseCounter": 492,
      "previousBetaReleaseCounter": 491,
      "commitSha": "pending-same-commit",
      "commitTitle": "fix(integrity): add central normalizer",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T07:05:00.000Z",
      "generatedAt": "2026-05-26T07:05:00.000Z",
      "committedAtUtc": "2026-05-26T07:05:00.000Z",
      "generatedAtUtc": "2026-05-26T07:05:00.000Z",
      "category": "Improved",
      "title": "Central normalizer spine",
      "updatedAtUtc": "2026-05-26T07:05:00.000Z",
      "summary": "Added a central normalizer spine for product signals.",
      "userFacingTitle": "Central normalizer spine",
      "surfaceCategory": "App experience",
      "bullets": [
        "Added central normalizer spine for product signals.",
        "Routed events, metrics, journeys, debug, score, and export facts through one normalization contract.",
        "Classified legacy direct pathways."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added typed central normalizer contracts and adapters over event envelopes, event facts, person metrics, journey, debug, score, export, and cost paths.",
        "Added source-only validator evidence and unit coverage for the normalizer spine.",
        "Connected central normalizer status to Admin Debug while preserving payment runtime, GumDrop math, navigation, production data, provider calls, and deploy state."
      ],
      "affectedSurfaces": [
        "Central normalizer",
        "Event envelope",
        "Behavioral event facts",
        "Person and global metrics",
        "User journey intelligence",
        "Admin Debug tracking summary",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/central-normalizer-spine.generated.json",
        "docs/agent-truth/central-normalizer-spine.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-central-normalizer-spine.ts",
        "src/lib/debug/debug-panel-tracking-summary.ts",
        "src/lib/product-integrity/central-normalizer-contract.ts",
        "src/lib/product-integrity/central-normalizer.ts",
        "src/lib/product-integrity/product-body-map.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/central-normalizer-spine.spec.ts"
      ],
      "effectiveChangeCount": 13,
      "excludedGeneratedChangeCount": 1,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.4.91",
      "previousVersion": "1.4.90",
      "betaReleaseCounter": 491,
      "previousBetaReleaseCounter": 490,
      "commitSha": "pending-same-commit",
      "commitTitle": "docs(integrity): map product body systems",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T06:45:00.000Z",
      "generatedAt": "2026-05-26T06:45:00.000Z",
      "committedAtUtc": "2026-05-26T06:45:00.000Z",
      "generatedAtUtc": "2026-05-26T06:45:00.000Z",
      "category": "Improved",
      "title": "Product integrity map",
      "updatedAtUtc": "2026-05-26T06:45:00.000Z",
      "summary": "Mapped product features, routes, telemetry, metrics, debug lanes, and score gates into one product integrity map.",
      "userFacingTitle": "Product integrity map",
      "surfaceCategory": "App experience",
      "bullets": [
        "Mapped product features, routes, telemetry, metrics, debug lanes, and score gates into body systems.",
        "Identified orphaned, duplicated, stale, and in-flight limbs.",
        "Added product body map debug visibility."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added canonical product body system and limb contracts for features, surfaces, routes, telemetry events, materializers, metrics, journey steps, debug lanes, score gates, validators, and artifacts.",
        "Generated issue-first product body map evidence while classifying open PRs and current dirty files.",
        "Connected the product body map to Admin Debug without changing payment runtime, GumDrop math, navigation, production reads, provider calls, or deploy state."
      ],
      "affectedSurfaces": [
        "Product body map",
        "Feature registration registry",
        "Surface parity registry",
        "Telemetry catalog",
        "Admin Debug tracking summary",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/product-body-map.generated.json",
        "docs/agent-truth/product-body-map.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-product-body-map.ts",
        "src/lib/debug/debug-panel-tracking-summary.ts",
        "src/lib/product-integrity/product-body-map.ts",
        "src/lib/product-integrity/product-body-system-contract.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/product-body-map.spec.ts"
      ],
      "effectiveChangeCount": 12,
      "excludedGeneratedChangeCount": 1,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.4.90",
      "previousVersion": "1.4.89",
      "betaReleaseCounter": 490,
      "previousBetaReleaseCounter": 489,
      "commitSha": "pending-same-commit",
      "commitTitle": "fix(math): normalize duration math",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T06:30:00.000Z",
      "generatedAt": "2026-05-26T06:30:00.000Z",
      "committedAtUtc": "2026-05-26T06:30:00.000Z",
      "generatedAtUtc": "2026-05-26T06:30:00.000Z",
      "category": "Improved",
      "title": "Duration math normalization",
      "updatedAtUtc": "2026-05-26T06:30:00.000Z",
      "summary": "Normalized duration math across sessions, watch time, tasks, flows, chat, media, auth, and notifications.",
      "userFacingTitle": "Duration math normalization",
      "surfaceCategory": "App experience",
      "bullets": [
        "Normalized duration math across sessions, watch time, tasks, flows, chat, media, auth, and notifications.",
        "Separated active, passive, idle, hidden, and unknown duration buckets.",
        "Blocked page-open and legacy unknown durations from becoming exact watch or active time."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added a canonical duration math normalizer for active, passive, idle, hidden, watch, flow, and legacy unknown duration decisions.",
        "Registered duration formula references in the canonical math authority ledger and Admin Debug duration math lane.",
        "Added source-only validator evidence and unit coverage without changing payment runtime, GumDrop math, or production data."
      ],
      "affectedSurfaces": [
        "Duration math normalizer",
        "Math authority ledger",
        "Admin Debug duration math lane",
        "Analytics duration validators",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/canonical-math-authority-ledger.generated.json",
        "agent/state/drop-watch-time-accuracy.generated.json",
        "agent/state/duration-math-normalization.generated.json",
        "agent/state/public-beta-score.generated.json",
        "agent/state/session-bounce-calculation.generated.json",
        "docs/agent-truth/canonical-math-authority-ledger.md",
        "docs/agent-truth/drop-watch-time-accuracy.md",
        "docs/agent-truth/duration-math-normalization.md",
        "docs/agent-truth/session-bounce-calculation.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-canonical-math-authority-ledger.ts",
        "scripts/agent/validate-drop-watch-time-accuracy.ts",
        "scripts/agent/validate-duration-math-normalization.ts",
        "scripts/agent/validate-session-bounce-calculation.ts",
        "src/lib/debug/debug-panel-tracking-summary.ts",
        "src/lib/math/canonical-math-authority-contract.ts",
        "src/lib/math/canonical-math-authority-ledger.ts",
        "src/lib/math/duration-math-normalizer.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/duration-math-normalization.spec.ts"
      ],
      "effectiveChangeCount": 23,
      "excludedGeneratedChangeCount": 5,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.4.89",
      "previousVersion": "1.4.88",
      "betaReleaseCounter": 489,
      "previousBetaReleaseCounter": 488,
      "commitSha": "pending-same-commit",
      "commitTitle": "docs(math): add canonical authority ledger",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T06:05:00.000Z",
      "generatedAt": "2026-05-26T06:05:00.000Z",
      "committedAtUtc": "2026-05-26T06:05:00.000Z",
      "generatedAtUtc": "2026-05-26T06:05:00.000Z",
      "category": "Improved",
      "title": "Canonical math authority ledger coverage",
      "updatedAtUtc": "2026-05-26T06:05:00.000Z",
      "summary": "Added canonical math authority ledger.",
      "userFacingTitle": "Canonical math authority ledger coverage",
      "surfaceCategory": "App experience",
      "bullets": [
        "Added canonical math authority ledger.",
        "Inventoried formulas across score, metrics, sessions, watch time, GumDrops, revenue, and legacy recovery.",
        "Blocked unowned formulas from silently affecting user/admin metrics."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added source-inventory coverage for formula-bearing score, analytics, behavioral, SQL parity, debug, validator, and generated score artifact paths.",
        "Kept code-organization scoring outside current MathDomain authority as needs_operator_decision instead of silently promoting it.",
        "Refreshed canonical math authority validator evidence and unit coverage without changing runtime payment, wallet, PayPal, GumDrop, or navigation behavior."
      ],
      "affectedSurfaces": [
        "Math authority ledger",
        "Formula source inventory",
        "Public beta score formulas",
        "Analytics and behavior metric formulas",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/canonical-math-authority-ledger.generated.json",
        "docs/agent-truth/canonical-math-authority-ledger.md",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-canonical-math-authority-ledger.ts",
        "src/lib/math/canonical-math-authority-contract.ts",
        "src/lib/math/canonical-math-authority-ledger.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/canonical-math-authority-ledger.spec.ts"
      ],
      "effectiveChangeCount": 10,
      "excludedGeneratedChangeCount": 1,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.4.88",
      "previousVersion": "1.4.87",
      "betaReleaseCounter": 488,
      "previousBetaReleaseCounter": 487,
      "commitSha": "pending-same-commit",
      "commitTitle": "fix(math): normalize count dedupe",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T05:35:00.000Z",
      "generatedAt": "2026-05-26T05:35:00.000Z",
      "committedAtUtc": "2026-05-26T05:35:00.000Z",
      "generatedAtUtc": "2026-05-26T05:35:00.000Z",
      "category": "Improved",
      "title": "Count deduplication normalization",
      "updatedAtUtc": "2026-05-26T05:35:00.000Z",
      "summary": "Normalized global, user, creator, and legacy count deduplication.",
      "userFacingTitle": "Count deduplication normalization",
      "surfaceCategory": "App experience",
      "bullets": [
        "Normalized global, user, creator, and legacy count deduplication.",
        "Prevented linked guest/user and retry events from inflating metrics.",
        "Added count formula references and debug explanations."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added a canonical count deduplication normalizer for eventId, dedupeKey, and timestamp-bucket fallback rules.",
        "Connected existing global/user dedupe decisions to count formula references and debug explanations without changing payment runtime or GumDrop math.",
        "Added source-only validator, generated evidence, documentation, and unit coverage for linked identity, legacy, retry, and replay count behavior."
      ],
      "affectedSurfaces": [
        "Analytics count math",
        "Global and user dedupe summaries",
        "Creator and legacy count buckets",
        "Admin Debug count dedupe lane",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/count-deduplication-normalization.generated.json",
        "docs/agent-truth/count-deduplication-normalization.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-canonical-math-authority-ledger.ts",
        "scripts/agent/validate-count-deduplication-normalization.ts",
        "src/lib/analytics/global-user-dedupe-contract.ts",
        "src/lib/analytics/global-user-dedupe-engine.ts",
        "src/lib/analytics/person-metrics-hydration.ts",
        "src/lib/debug/debug-panel-tracking-summary.ts",
        "src/lib/math/canonical-math-authority-contract.ts",
        "src/lib/math/canonical-math-authority-ledger.ts",
        "src/lib/math/count-deduplication-normalizer.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/count-deduplication-normalization.spec.ts"
      ],
      "effectiveChangeCount": 17,
      "excludedGeneratedChangeCount": 1,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    },
    {
      "version": "1.4.87",
      "previousVersion": "1.4.86",
      "betaReleaseCounter": 487,
      "previousBetaReleaseCounter": 486,
      "commitSha": "pending-same-commit",
      "commitTitle": "docs(math): add canonical authority ledger",
      "commitCount": 1,
      "commitShas": [
        "pending-same-commit"
      ],
      "committedAt": "2026-05-26T05:22:00.000Z",
      "generatedAt": "2026-05-26T05:22:00.000Z",
      "committedAtUtc": "2026-05-26T05:22:00.000Z",
      "generatedAtUtc": "2026-05-26T05:22:00.000Z",
      "category": "Improved",
      "title": "Canonical math authority ledger",
      "updatedAtUtc": "2026-05-26T05:22:00.000Z",
      "summary": "Added canonical math authority ledger.",
      "userFacingTitle": "Canonical math authority ledger",
      "surfaceCategory": "App experience",
      "bullets": [
        "Added canonical math authority ledger.",
        "Inventoried formulas across score, metrics, sessions, watch time, GumDrops, revenue, and legacy recovery.",
        "Blocked unowned formulas from silently affecting user/admin metrics."
      ],
      "audience": "all",
      "technicalDetails": [
        "Added source-only math authority contract and ledger APIs for formula lookup, explanation, metric validation, score validation, and unowned formula classification.",
        "Inventoried current beta score, person metric, session, bounce, watch-time, behavioral dedupe, SQL parity, revenue, GumDrop, creator monetization, Fan Pass, discovery, chat, task, notification, media, and legacy recovery formula authorities.",
        "Added a validator, generated evidence report, agent-truth doc, and unit coverage without changing payment runtime, PayPal, wallet, GumDrop ledger math, nav, or production data."
      ],
      "affectedSurfaces": [
        "Math authority ledger",
        "Public beta score formulas",
        "Analytics and behavior metric formulas",
        "Revenue and GumDrop formula inventory",
        "Release notes"
      ],
      "hiddenFromPublic": false,
      "changedFiles": [
        "CHANGELOG.md",
        "agent/state/canonical-math-authority-ledger.generated.json",
        "docs/agent-truth/canonical-math-authority-ledger.md",
        "package.json",
        "public/kandydrops-release-notes.json",
        "scripts/agent/validate-canonical-math-authority-ledger.ts",
        "src/lib/debug/debug-panel-tracking-summary.ts",
        "src/lib/math/canonical-math-authority-contract.ts",
        "src/lib/math/canonical-math-authority-ledger.ts",
        "src/lib/release-notes/public-release-notes.ts",
        "src/lib/release-notes/release-version-contract.ts",
        "tests/unit/canonical-math-authority-ledger.spec.ts"
      ],
      "effectiveChangeCount": 12,
      "excludedGeneratedChangeCount": 1,
      "bumpType": "patch",
      "sourceCommit": "pending-same-commit"
    }
  ]
} satisfies PublicReleaseNotesDocument;

export const PUBLIC_RELEASE_NOTES_VERSION_CONTEXT = {
  betaReleaseCounter: PUBLIC_RELEASE_NOTES_FALLBACK.betaReleaseCounter,
  appVersion: PUBLIC_RELEASE_NOTES_FALLBACK.currentVersion,
  releaseChannel: PUBLIC_RELEASE_NOTES_FALLBACK.channel,
} as const;

export const PUBLIC_APP_VERSION = PUBLIC_RELEASE_NOTES_VERSION_CONTEXT.appVersion;
