extend type Mutation {
  """
  ✨ Insert a single `AiInteraction` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  aiInteraction_insert(
    """
    Data object to insert into the table.
    """
    data: AiInteraction_Data!
  ): AiInteraction_KeyOutput! @fdc_generated(from: "AiInteraction", purpose: INSERT_SINGLE)
  """
  ✨ Insert `AiInteraction` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  aiInteraction_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [AiInteraction_Data!]!
  ): [AiInteraction_KeyOutput!]! @fdc_generated(from: "AiInteraction", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `AiInteraction` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AiInteraction`.
  """
  aiInteraction_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: AiInteraction_Data!
  ): AiInteraction_KeyOutput! @fdc_generated(from: "AiInteraction", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `AiInteraction` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AiInteraction`.
  """
  aiInteraction_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [AiInteraction_Data!]!
  ): [AiInteraction_KeyOutput!]! @fdc_generated(from: "AiInteraction", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `AiInteraction` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `AiInteraction` or `null` if not found.
  """
  aiInteraction_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AiInteraction_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AiInteraction_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: AiInteraction_Data!
  ): AiInteraction_KeyOutput @fdc_generated(from: "AiInteraction", purpose: UPDATE_SINGLE)
  """
  ✨ Update `AiInteraction` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  aiInteraction_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: AiInteraction_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: AiInteraction_Data!
  ): Int! @fdc_generated(from: "AiInteraction", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `AiInteraction` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  aiInteraction_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AiInteraction_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AiInteraction_FirstRow
  ): AiInteraction_KeyOutput @fdc_generated(from: "AiInteraction", purpose: DELETE_SINGLE)
  """
  ✨ Delete `AiInteraction` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  aiInteraction_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: AiInteraction_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "AiInteraction", purpose: DELETE_MULTIPLE)
}
