import type { MathDomain } from "@/lib/math/canonical-math-authority-contract";

export const REQUIRED_FORMULA_OWNER_IDS = [
  "beta_score",
  "person_metrics",
  "global_metrics",
  "session_time",
  "bounce",
  "watch_time",
  "gumdrop_balances",
  "source_of_funds",
  "revenue_entitlements",
  "task_rewards",
  "chat_gating",
  "notification_liveness",
  "sql_export_parity",
  "legacy_recovery_confidence",
] as const;

export type FormulaOwnerId = typeof REQUIRED_FORMULA_OWNER_IDS[number];

export type FormulaAuthorityEntry = {
  formulaOwnerId: FormulaOwnerId;
  domain: MathDomain;
  primaryOwner: string;
  currentFormula: string;
  canonicalFormula: string;
  sourceFiles: string[];
  formulaStatus: "canonical" | "canonical_documented" | "needs_operator_decision" | "in_flight";
  confidenceRule: string;
  zeroOrMissingRule: string;
  userFacingAllowed: boolean;
  adminFacingAllowed: boolean;
  scoreDimensions: string[];
  nextAction: string;
};

export const FORMULA_AUTHORITY_MAP: FormulaAuthorityEntry[] = [
  {
    formulaOwnerId: "beta_score",
    domain: "beta_score",
    primaryOwner: "agent_score",
    currentFormula: "Weighted score dimensions in src/lib/agent-score/weights.ts.",
    canonicalFormula: "sourceHealth 18 + runtimeHealth 30 + evidenceCompleteness 25 + freshness 10 + costRisk 7 + regressionRisk 10 divided by 100.",
    sourceFiles: ["src/lib/agent-score/core.ts", "src/lib/agent-score/weights.ts", "src/lib/math/canonical-math-ledger.ts"],
    formulaStatus: "canonical",
    confidenceRule: "Score inputs must keep formal/source/runtime evidence confidence separate.",
    zeroOrMissingRule: "Missing required score evidence is missing/stale, not zero, unless a bounded source summary proves zero findings.",
    userFacingAllowed: false,
    adminFacingAllowed: true,
    scoreDimensions: ["sourceHealth", "runtimeHealth", "evidenceCompleteness", "freshness", "costRisk", "regressionRisk"],
    nextAction: "Keep score weight changes centralized in the math ledger and agent-score weights.",
  },
  {
    formulaOwnerId: "person_metrics",
    domain: "user_metrics",
    primaryOwner: "analytics_person_metrics",
    currentFormula: "Hydrates person metric status from canonical envelopes and source event definitions.",
    canonicalFormula: "Hydrated metric count derives from event envelope/source mappings; gap count uses unique metric IDs across missing hydration and blocking user-parity gaps.",
    sourceFiles: ["src/lib/analytics/person-metrics-hydration.ts", "src/lib/math/canonical-math-ledger.ts"],
    formulaStatus: "canonical",
    confidenceRule: "exact/linked/inferred/weak/unknown use canonical confidence weights; weak/unknown legacy cannot become exact.",
    zeroOrMissingRule: "Missing hydration is a gap unless proven-zero evidence exists.",
    userFacingAllowed: false,
    adminFacingAllowed: true,
    scoreDimensions: ["evidenceCompleteness", "sourceHealth"],
    nextAction: "Use real missing hydration gaps in debug and score impact; classify future-only exclusions before excluding.",
  },
  {
    formulaOwnerId: "global_metrics",
    domain: "global_metrics",
    primaryOwner: "analytics_global_metrics",
    currentFormula: "Global summaries use event facts and global/user dedupe normalization.",
    canonicalFormula: "Global count increments once per canonical count key; linked guest/user actions count once globally.",
    sourceFiles: ["src/lib/analytics/global-user-dedupe-engine.ts", "src/lib/math/count-deduplication-normalizer.ts"],
    formulaStatus: "canonical",
    confidenceRule: "Weak/unknown legacy counts in legacy buckets, not exact global/user summaries.",
    zeroOrMissingRule: "No accepted increment is zero only inside a bounded evaluated source window; missing source is unavailable.",
    userFacingAllowed: true,
    adminFacingAllowed: true,
    scoreDimensions: ["sourceHealth", "evidenceCompleteness"],
    nextAction: "Keep global/user divergence explanations on every dedupe decision.",
  },
  {
    formulaOwnerId: "session_time",
    domain: "session_metrics",
    primaryOwner: "analytics_duration_math",
    currentFormula: "Duration normalizer computes active/passive/idle/hidden session buckets.",
    canonicalFormula: "Session time is active + passive + idle buckets, while user-facing active time uses active bucket only and excludes hidden/background time.",
    sourceFiles: ["src/lib/math/duration-math-normalizer.ts", "src/lib/analytics/session-metrics-engine.ts"],
    formulaStatus: "canonical",
    confidenceRule: "Exact requires validated start/end lifecycle truth; abandoned/timeout is estimated; unknown legacy is unavailable.",
    zeroOrMissingRule: "Unknown duration is unavailable, not zero.",
    userFacingAllowed: true,
    adminFacingAllowed: true,
    scoreDimensions: ["sourceHealth", "runtimeHealth"],
    nextAction: "Keep page-open time out of active duration unless source proves active foreground interaction.",
  },
  {
    formulaOwnerId: "bounce",
    domain: "bounce",
    primaryOwner: "analytics_session_metrics",
    currentFormula: "Bounce status is derived from session lifecycle and engagement events.",
    canonicalFormula: "Bounce rate requires numerator, denominator, source window, and unavailable behavior for missing denominator.",
    sourceFiles: ["src/lib/math/duration-math-normalizer.ts", "scripts/agent/validate-session-bounce-calculation.ts"],
    formulaStatus: "canonical_documented",
    confidenceRule: "Exact only when session start and bounce/engaged/closed events are source-linked.",
    zeroOrMissingRule: "Missing denominator returns unavailable, not 0%.",
    userFacingAllowed: false,
    adminFacingAllowed: true,
    scoreDimensions: ["sourceHealth", "evidenceCompleteness"],
    nextAction: "Keep bounce denominator windows explicit in session validators.",
  },
  {
    formulaOwnerId: "watch_time",
    domain: "watch_time",
    primaryOwner: "analytics_watch_time",
    currentFormula: "Watch duration comes from media/content exposure duration decisions.",
    canonicalFormula: "Watch time is media/content exposure only; page time and hidden/background time are excluded.",
    sourceFiles: ["src/lib/math/duration-math-normalizer.ts", "src/lib/analytics/drop-watch-time-engine.ts"],
    formulaStatus: "canonical",
    confidenceRule: "Exact requires media playback or active content exposure timestamps; legacy without start/end remains unavailable.",
    zeroOrMissingRule: "Missing content duration makes normalized watch percent unavailable, not zero.",
    userFacingAllowed: true,
    adminFacingAllowed: true,
    scoreDimensions: ["sourceHealth", "evidenceCompleteness"],
    nextAction: "Keep watch-time validators rejecting page-open fallback.",
  },
  {
    formulaOwnerId: "gumdrop_balances",
    domain: "gumdrop",
    primaryOwner: "wallet_commerce",
    currentFormula: "Wallet and source-of-funds contracts distinguish purchased, bonus, and reward balances.",
    canonicalFormula: "GumDrop balances must preserve paid GD, reward GD, bonus GD, source-of-funds, and confidence.",
    sourceFiles: ["src/lib/math/canonical-math-ledger.ts", "functions/src/gumdrop-economics.ts"],
    formulaStatus: "canonical_documented",
    confidenceRule: "Balance confidence comes from wallet capture/source ledger truth, not UI display totals.",
    zeroOrMissingRule: "Missing balance source is unavailable/source_missing; proven zero requires bounded ledger summary.",
    userFacingAllowed: true,
    adminFacingAllowed: true,
    scoreDimensions: ["sourceHealth", "costRisk"],
    nextAction: "Do not change payment or GumDrop math in this ledger pass.",
  },
  {
    formulaOwnerId: "source_of_funds",
    domain: "gumdrop",
    primaryOwner: "commerce_server_truth",
    currentFormula: "Paid package bonus GumDrops are paid-source; reward GumDrops are non-purchase rewards.",
    canonicalFormula: "Paid GD, reward GD, bonus GD, source-of-funds, and confidence stay explicit for creator monetization and Fan Pass access.",
    sourceFiles: ["src/lib/math/canonical-math-ledger.ts", "functions/src/gumdrop-economics.ts"],
    formulaStatus: "canonical_documented",
    confidenceRule: "Exact only from wallet capture/source ledger truth.",
    zeroOrMissingRule: "Missing source-of-funds is not zero and cannot authorize paid-source requirements.",
    userFacingAllowed: false,
    adminFacingAllowed: true,
    scoreDimensions: ["sourceHealth", "regressionRisk"],
    nextAction: "Keep source-of-funds validators as the runtime authority for economy changes.",
  },
  {
    formulaOwnerId: "revenue_entitlements",
    domain: "revenue",
    primaryOwner: "creator_monetization",
    currentFormula: "Creator entitlements map source feature, user, creator, source transaction/event, funds source, and confidence.",
    canonicalFormula: "Revenue/entitlement metrics require source truth and confidence and must not fake revenue.",
    sourceFiles: ["src/lib/creator-monetization/creator-entitlement-contract.ts", "src/lib/math/canonical-math-ledger.ts"],
    formulaStatus: "canonical_documented",
    confidenceRule: "Revenue confidence is exact only when source transaction truth exists; inferred/legacy remains lower confidence.",
    zeroOrMissingRule: "Missing revenue is unavailable; no dollar claims without billing/export artifact.",
    userFacingAllowed: false,
    adminFacingAllowed: true,
    scoreDimensions: ["sourceHealth", "evidenceCompleteness"],
    nextAction: "Keep payment runtime untouched and use ledger confidence for reporting only.",
  },
  {
    formulaOwnerId: "task_rewards",
    domain: "daily_tasks",
    primaryOwner: "daily_tasks_rewards",
    currentFormula: "Task reward and completion counts hydrate from task lifecycle events.",
    canonicalFormula: "Task rewards distinguish completion count, reward source, source-of-funds, and confidence.",
    sourceFiles: ["src/lib/math/count-deduplication-normalizer.ts", "src/lib/math/duration-math-normalizer.ts"],
    formulaStatus: "canonical",
    confidenceRule: "Exact reward requires task completion/reward source event; weak legacy remains legacy.",
    zeroOrMissingRule: "Missing task activity is unavailable unless bounded task window proves zero.",
    userFacingAllowed: true,
    adminFacingAllowed: true,
    scoreDimensions: ["sourceHealth", "evidenceCompleteness"],
    nextAction: "Keep reward-source GumDrops separate from paid-source monetization formulas.",
  },
  {
    formulaOwnerId: "chat_gating",
    domain: "chat",
    primaryOwner: "chat_messaging",
    currentFormula: "Chat attempts/sends/blocks use count dedupe and monetization/access contracts.",
    canonicalFormula: "Chat gating metrics count attempts/success/blocks once by canonical event key and preserve paid-source access confidence.",
    sourceFiles: ["src/lib/math/count-deduplication-normalizer.ts", "src/lib/chat.ts"],
    formulaStatus: "canonical_documented",
    confidenceRule: "Access confidence follows entitlement/Fan Pass/source-of-funds truth.",
    zeroOrMissingRule: "Missing chat gate evidence is source_missing, not success or zero.",
    userFacingAllowed: false,
    adminFacingAllowed: true,
    scoreDimensions: ["sourceHealth", "runtimeHealth"],
    nextAction: "Do not touch chat internals in this formula freeze beyond classification.",
  },
  {
    formulaOwnerId: "notification_liveness",
    domain: "notifications",
    primaryOwner: "notifications_pwa",
    currentFormula: "Notification prompt/token/targeting events feed liveness and metrics lanes.",
    canonicalFormula: "Notification liveness needs viewed/attempted/succeeded/failed counts, bounded freshness, and explicit missing/future-only handling.",
    sourceFiles: ["src/lib/math/count-deduplication-normalizer.ts", "src/lib/telemetry-catalog.ts"],
    formulaStatus: "canonical_documented",
    confidenceRule: "Exact only from registered notification lifecycle events or validated server materializer snapshots.",
    zeroOrMissingRule: "Future-only notification events do not count as failures; missing liveness is source_missing.",
    userFacingAllowed: false,
    adminFacingAllowed: true,
    scoreDimensions: ["freshness", "evidenceCompleteness"],
    nextAction: "Keep high-traffic no-liveness classified suspicious_idle/source_missing.",
  },
  {
    formulaOwnerId: "sql_export_parity",
    domain: "global_metrics",
    primaryOwner: "telemetry_behavioral_intelligence",
    currentFormula: "SQL/export parity compares source summaries and generated mirror outputs.",
    canonicalFormula: "Export parity formulas require source, destination, bounded window, confidence, and explicit delta.",
    sourceFiles: ["src/lib/analytics/sql-database-parity-engine.ts", "src/lib/math/canonical-math-authority-ledger.ts"],
    formulaStatus: "canonical_documented",
    confidenceRule: "Generated SQL/Data Connect mirror does not outrank verified source truth.",
    zeroOrMissingRule: "Missing export lane is stale/missing, not zero delta.",
    userFacingAllowed: false,
    adminFacingAllowed: true,
    scoreDimensions: ["evidenceCompleteness", "costRisk"],
    nextAction: "Keep SQL/Data Connect mirror as agent context unless explicitly promoted by cost contract.",
  },
  {
    formulaOwnerId: "legacy_recovery_confidence",
    domain: "legacy_recovery",
    primaryOwner: "analytics_legacy_recovery",
    currentFormula: "Legacy events are normalized with lower confidence classifications.",
    canonicalFormula: "Legacy recovered data cannot be promoted above inferred without deterministic userId, sessionId, eventId, and source timestamp; unknown legacy remains archive-only.",
    sourceFiles: ["src/lib/analytics/event-envelope-builder.ts", "src/lib/behavioral/normalize-event-fact.ts", "src/lib/math/canonical-math-ledger.ts"],
    formulaStatus: "canonical",
    confidenceRule: "exact=1, linked=.85, inferred=.6, weak=.35, unknown=0; legacy maxima apply before scoring.",
    zeroOrMissingRule: "Unknown legacy is unavailable/archive-only, not zero or exact.",
    userFacingAllowed: false,
    adminFacingAllowed: true,
    scoreDimensions: ["sourceHealth", "evidenceCompleteness"],
    nextAction: "Keep legacy confidence lower unless deterministic source truth exists.",
  },
];

export function getFormulaAuthority(ownerId: FormulaOwnerId) {
  return FORMULA_AUTHORITY_MAP.find((entry) => entry.formulaOwnerId === ownerId);
}

export function listFormulaAuthorities() {
  return [...FORMULA_AUTHORITY_MAP];
}
