import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import {
  type LegacyRecoverySourceInventoryItem,
  type LegacySourceInventoryReport,
  parseLegacyRecoveryCliArgs,
} from "@/lib/analytics/legacy-recovery-contract";

const outputPath = join(process.cwd(), "agent", "state", "analytics-legacy-source-inventory.generated.json");

const LEGACY_SOURCES: LegacyRecoverySourceInventoryItem[] = [
  {
    sourceName: "analytics_event_facts",
    sourceType: "firestore",
    pathOrTable: "analytics_event_facts",
    earliestTimestamp: null,
    latestTimestamp: null,
    recordCount: null,
    countMode: "not_queried",
    sampleShape: ["eventName", "eventId", "timestamp", "userId", "sessionId", "route", "objectId"],
    timestampFields: ["occurredAt", "eventTimestamp", "timestamp", "createdAt"],
    actorFields: ["userId", "uid", "anonymousVisitorId", "sessionId", "creatorId", "adminId"],
    objectFields: ["objectId", "dropId", "taskId", "notificationId", "transactionId", "assetId", "stepId"],
    eventNameFields: ["eventName", "event_name", "name", "type", "event"],
    recoverability: "backfillable",
    confidence: "high",
    risks: ["May include repeated raw events; dedupeKey must be applied before snapshot inclusion."],
  },
  {
    sourceName: "analytics_guest_batches",
    sourceType: "firestore",
    pathOrTable: "analytics_guest_batches",
    earliestTimestamp: null,
    latestTimestamp: null,
    recordCount: null,
    countMode: "not_queried",
    sampleShape: ["batchId", "anonymousVisitorId", "clientSessionId", "pagePath", "createdAt", "consentState"],
    timestampFields: ["createdAt", "updatedAt", "timestamp"],
    actorFields: ["anonymousVisitorId", "clientSubjectId", "visitorId", "sessionId", "clientSessionId"],
    objectFields: ["surface", "route", "pagePath"],
    eventNameFields: ["eventName", "type"],
    recoverability: "directional",
    confidence: "directional",
    risks: ["Guest batches are consent and batch dependent; do not treat as exact audience totals."],
  },
  {
    sourceName: "analytics_session_facts",
    sourceType: "firestore",
    pathOrTable: "analytics_session_facts",
    earliestTimestamp: null,
    latestTimestamp: null,
    recordCount: null,
    countMode: "not_queried",
    sampleShape: ["sessionId", "anonymousVisitorId", "startedAt", "lastSeenAt", "route"],
    timestampFields: ["startedAt", "lastSeenAt", "createdAt", "updatedAt"],
    actorFields: ["anonymousVisitorId", "sessionId", "userId", "uid"],
    objectFields: ["route", "surface"],
    eventNameFields: ["eventName", "type"],
    recoverability: "directional",
    confidence: "medium",
    risks: ["Identity links are needed before merging guest sessions into user behavior."],
  },
  {
    sourceName: "transactions",
    sourceType: "firestore",
    pathOrTable: "transactions",
    earliestTimestamp: null,
    latestTimestamp: null,
    recordCount: null,
    countMode: "not_queried",
    sampleShape: ["transactionId", "userId", "status", "amount", "completedAt", "dropId"],
    timestampFields: ["completedAt", "createdAt", "updatedAt", "timestamp"],
    actorFields: ["userId", "uid"],
    objectFields: ["transactionId", "purchaseId", "dropId"],
    eventNameFields: ["status", "type"],
    recoverability: "backfillable",
    confidence: "high",
    risks: ["Payment provider records must be parity checked before commerce snapshots include recovered data."],
  },
  {
    sourceName: "unlocks",
    sourceType: "firestore",
    pathOrTable: "unlocks",
    earliestTimestamp: null,
    latestTimestamp: null,
    recordCount: null,
    countMode: "not_queried",
    sampleShape: ["unlockId", "userId", "dropId", "createdAt"],
    timestampFields: ["createdAt", "unlockedAt", "updatedAt"],
    actorFields: ["userId", "uid"],
    objectFields: ["unlockId", "dropId"],
    eventNameFields: ["eventName", "type"],
    recoverability: "backfillable",
    confidence: "medium",
    risks: ["Unlock records must reconcile with viewer/watch events and rollups."],
  },
  {
    sourceName: "drop_views",
    sourceType: "firestore",
    pathOrTable: "drop_views",
    earliestTimestamp: null,
    latestTimestamp: null,
    recordCount: null,
    countMode: "not_queried",
    sampleShape: ["dropId", "userId", "anonymousVisitorId", "sessionId", "createdAt", "route"],
    timestampFields: ["createdAt", "viewedAt", "timestamp"],
    actorFields: ["userId", "anonymousVisitorId", "sessionId"],
    objectFields: ["dropId"],
    eventNameFields: ["eventName", "type"],
    recoverability: "directional",
    confidence: "medium",
    risks: ["Public views may be sampled or duplicated by route reloads."],
  },
  {
    sourceName: "analytics_watch_sessions",
    sourceType: "firestore",
    pathOrTable: "analytics_watch_sessions",
    earliestTimestamp: null,
    latestTimestamp: null,
    recordCount: null,
    countMode: "not_queried",
    sampleShape: ["sessionId", "userId", "dropId", "assetId", "startedAt", "completedAt"],
    timestampFields: ["startedAt", "completedAt", "createdAt", "updatedAt"],
    actorFields: ["userId", "uid", "sessionId"],
    objectFields: ["dropId", "assetId"],
    eventNameFields: ["eventName", "type"],
    recoverability: "backfillable",
    confidence: "medium",
    risks: ["Watch duration needs linked start/end timestamps before speed or completion parity."],
  },
  {
    sourceName: "daily_task_events",
    sourceType: "firestore",
    pathOrTable: "daily_task_events",
    earliestTimestamp: null,
    latestTimestamp: null,
    recordCount: null,
    countMode: "not_queried",
    sampleShape: ["taskId", "userId", "lifecycleState", "createdAt", "completedAt", "failedAt"],
    timestampFields: ["createdAt", "startedAt", "completedAt", "failedAt", "updatedAt"],
    actorFields: ["userId", "uid"],
    objectFields: ["taskId"],
    eventNameFields: ["lifecycleState", "state", "status", "action"],
    recoverability: "backfillable",
    confidence: "high",
    risks: ["Raw task telemetry must not override canonical user task state without reconciliation."],
  },
  {
    sourceName: "task_lifecycle_logs",
    sourceType: "firestore",
    pathOrTable: "task_lifecycle_logs",
    earliestTimestamp: null,
    latestTimestamp: null,
    recordCount: null,
    countMode: "not_queried",
    sampleShape: ["taskId", "userId", "state", "timestamp"],
    timestampFields: ["timestamp", "createdAt", "updatedAt"],
    actorFields: ["userId", "uid"],
    objectFields: ["taskId"],
    eventNameFields: ["state", "status", "action"],
    recoverability: "backfillable",
    confidence: "medium",
    risks: ["Lifecycle order requires taskId/userId linkage before pipeline truth."],
  },
  {
    sourceName: "notifications",
    sourceType: "firestore",
    pathOrTable: "notifications",
    earliestTimestamp: null,
    latestTimestamp: null,
    recordCount: null,
    countMode: "not_queried",
    sampleShape: ["notificationId", "recipientId", "type", "createdAt", "sentAt", "openedAt", "readAt"],
    timestampFields: ["createdAt", "sentAt", "openedAt", "readAt", "clearedAt"],
    actorFields: ["recipientId", "userId", "uid"],
    objectFields: ["notificationId", "dropId", "taskId"],
    eventNameFields: ["type", "eventName"],
    recoverability: "backfillable",
    confidence: "medium",
    risks: ["Web push delivery is not fully observable; sent/open/read parity must stay separate."],
  },
  {
    sourceName: "onboarding_steps",
    sourceType: "firestore",
    pathOrTable: "onboarding_steps",
    earliestTimestamp: null,
    latestTimestamp: null,
    recordCount: null,
    countMode: "not_queried",
    sampleShape: ["userId", "stepId", "state", "startedAt", "completedAt"],
    timestampFields: ["startedAt", "completedAt", "createdAt", "updatedAt"],
    actorFields: ["userId", "uid", "sessionId"],
    objectFields: ["stepId"],
    eventNameFields: ["state", "status", "action"],
    recoverability: "backfillable",
    confidence: "medium",
    risks: ["Auth signups are not onboarding starts; discrepancy is expected unless sources define the same event."],
  },
  {
    sourceName: "users",
    sourceType: "firestore",
    pathOrTable: "users",
    earliestTimestamp: null,
    latestTimestamp: null,
    recordCount: null,
    countMode: "not_queried",
    sampleShape: ["uid", "createdAt", "role", "creatorId", "lastLoginAt"],
    timestampFields: ["createdAt", "updatedAt", "lastLoginAt"],
    actorFields: ["uid", "userId", "creatorId", "adminId", "role"],
    objectFields: ["uid"],
    eventNameFields: ["type", "eventName"],
    recoverability: "directional",
    confidence: "medium",
    risks: ["User records are identity facts, not behavior events; use for identity graph and parity only."],
  },
  {
    sourceName: "presence",
    sourceType: "rtdb",
    pathOrTable: "presence/*",
    earliestTimestamp: null,
    latestTimestamp: null,
    recordCount: null,
    countMode: "not_queried",
    sampleShape: ["uid", "sessionId", "route", "lastSeen", "state"],
    timestampFields: ["lastSeen", "lastSeenAt", "updatedAt"],
    actorFields: ["uid", "userId", "sessionId", "anonymousVisitorId"],
    objectFields: ["route", "surface"],
    eventNameFields: ["state", "eventName"],
    recoverability: "debug_only",
    confidence: "directional",
    risks: ["Presence is volatile and must not become historical canonical truth without lifecycle evidence."],
  },
  {
    sourceName: "admin_audit_logs",
    sourceType: "firestore",
    pathOrTable: "admin_audit_logs",
    earliestTimestamp: null,
    latestTimestamp: null,
    recordCount: null,
    countMode: "not_queried",
    sampleShape: ["adminId", "route", "action", "createdAt"],
    timestampFields: ["createdAt", "timestamp", "updatedAt"],
    actorFields: ["adminId", "userId", "uid"],
    objectFields: ["objectId", "targetId"],
    eventNameFields: ["action", "eventName", "type"],
    recoverability: "backfillable",
    confidence: "medium",
    risks: ["Admin actions are excluded from user/guest behavioral analytics."],
  },
  {
    sourceName: "ga4_daily",
    sourceType: "ga4_bigquery",
    pathOrTable: "events_YYYYMMDD",
    earliestTimestamp: null,
    latestTimestamp: null,
    recordCount: null,
    countMode: "not_queried",
    sampleShape: ["event_name", "event_timestamp", "user_pseudo_id", "user_id", "event_params"],
    timestampFields: ["event_timestamp", "event_date"],
    actorFields: ["user_id", "user_pseudo_id"],
    objectFields: ["event_params.drop_id", "event_params.task_id", "event_params.route"],
    eventNameFields: ["event_name"],
    recoverability: "directional",
    confidence: "medium",
    risks: ["GA4 daily is stable historical validation, not first-party product truth."],
  },
  {
    sourceName: "ga4_intraday",
    sourceType: "ga4_bigquery",
    pathOrTable: "events_intraday_YYYYMMDD",
    earliestTimestamp: null,
    latestTimestamp: null,
    recordCount: null,
    countMode: "not_queried",
    sampleShape: ["event_name", "event_timestamp", "user_pseudo_id", "user_id", "event_params"],
    timestampFields: ["event_timestamp", "event_date"],
    actorFields: ["user_id", "user_pseudo_id"],
    objectFields: ["event_params.drop_id", "event_params.task_id", "event_params.route"],
    eventNameFields: ["event_name"],
    recoverability: "directional",
    confidence: "directional",
    risks: ["Intraday export is incomplete/live-ish; label as directional and never as verified server truth."],
  },
  {
    sourceName: "analytics_admin_metric_snapshots",
    sourceType: "cache",
    pathOrTable: "analytics_admin_metric_snapshots",
    earliestTimestamp: null,
    latestTimestamp: null,
    recordCount: null,
    countMode: "not_queried",
    sampleShape: ["moduleKey", "rangeKey", "values", "generatedAt", "lastVerifiedAt", "parity"],
    timestampFields: ["generatedAt", "lastVerifiedAt", "refreshCompletedAt"],
    actorFields: ["generatedBy", "requestedBy"],
    objectFields: ["moduleKey", "rangeKey"],
    eventNameFields: ["moduleKey"],
    recoverability: "debug_only",
    confidence: "high",
    risks: ["Snapshots are display truth; they must include parity but are not raw event ledgers."],
  },
];

const options = parseLegacyRecoveryCliArgs(process.argv.slice(2));
const filteredSources = options.source
  ? LEGACY_SOURCES.filter((source) => source.sourceName === options.source)
  : LEGACY_SOURCES;

const report: LegacySourceInventoryReport = {
  generatedAt: new Date().toISOString(),
  dryRun: true,
  liveScanEnabled: false,
  sourceFilter: options.source,
  sources: filteredSources,
  summary: {
    sourceCount: filteredSources.length,
    backfillableCount: filteredSources.filter((source) => source.recoverability === "backfillable").length,
    directionalCount: filteredSources.filter((source) => source.recoverability === "directional").length,
    debugOnlyCount: filteredSources.filter((source) => source.recoverability === "debug_only").length,
    unavailableCount: filteredSources.filter((source) => source.recoverability === "unavailable").length,
  },
};

if (!existsSync(dirname(outputPath))) {
  mkdirSync(dirname(outputPath), { recursive: true });
}

writeFileSync(outputPath, `${JSON.stringify(report, null, 2)}\n`);
console.log(`Wrote legacy source inventory to ${outputPath}`);
