import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

type DirtyFileClassification =
  | "current_generated_artifact_to_commit"
  | "stale_generated_artifact_to_regenerate"
  | "stale_generated_artifact_to_revert_or_delete"
  | "unrelated_agent_context_file_to_ignore"
  | "real_source_change_needs_review"
  | "release_artifact_expected"
  | "unsafe_unknown";

type PrAction = "integrated_and_closed" | "closed_superseded" | "preserved_with_reason";

export type FinalPrCleanupAction = {
  number: number;
  title: string;
  action: PrAction;
  reason: string;
};

export type FinalPrSummary = {
  number?: number;
  title?: string;
  url?: string;
  mergeStateStatus?: string;
  classification?: string;
};

export type FinalPrStaleCleanupReport = {
  generatedAtUtc: string;
  reportKey: "final-pr-stale-cleanup";
  currentHead: string;
  summary: {
    openPrCount: number;
    prsHandled: number;
    prsIntegrated: number;
    prsClosedSuperseded: number;
    prsPreserved: number;
    prsUnclassified: number;
    dirtyFilesClassified: number;
    dirtyFilesUnclassified: number;
    staleGeneratedArtifacts: number;
    staleGeneratedArtifactsUnclassified: number;
    releaseNotesSameCommit: boolean;
    p0Count: number;
    p1Count: number;
    p2Count: number;
  };
  openPrs: FinalPrSummary[];
  prCleanupActions: FinalPrCleanupAction[];
  dirtyFileClassifications: Array<{ file: string; classification: DirtyFileClassification; reason: string }>;
  staleArtifactFindings: Array<{ file: string; classification: DirtyFileClassification; reason: string }>;
  fixesApplied: string[];
  releaseNote: {
    title: string;
    bullets: string[];
  };
  nextExactSteps: string[];
};

export type FinalPrStaleCleanupInputs = {
  generatedAtUtc: string;
  currentHead: string;
  openPrs: FinalPrSummary[];
  changedFiles: string[];
  untrackedFiles: string[];
  prCleanupActions: FinalPrCleanupAction[];
  releaseNotesUpdated: boolean;
};

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = join(__dirname, "..", "..");
const ARTIFACT = "agent/state/final-pr-stale-cleanup.generated.json";
const DOC = "docs/agent-truth/final-pr-stale-cleanup.md";

const releaseBullets = [
  "Cleaned up remaining preserved PRs and stale repo artifacts.",
  "Kept beta cleanup lanes free of superseded PR clutter.",
  "Preserved current source-truth doctrine while closing stale work.",
];

function safeExec(command: string, args: string[]) {
  try {
    return execFileSync(command, args, { cwd: ROOT, encoding: "utf8" }).trim();
  } catch {
    return "";
  }
}

function currentHead() {
  return safeExec("git", ["rev-parse", "HEAD"]);
}

function changedFiles() {
  const unstaged = safeExec("git", ["diff", "--name-only"]).split(/\r?\n/u).filter(Boolean);
  const staged = safeExec("git", ["diff", "--cached", "--name-only"]).split(/\r?\n/u).filter(Boolean);
  return Array.from(new Set([...unstaged, ...staged])).map((file) => file.replaceAll("\\", "/"));
}

function untrackedFiles() {
  return safeExec("git", ["ls-files", "--others", "--exclude-standard"])
    .split(/\r?\n/u)
    .filter(Boolean)
    .map((file) => file.replaceAll("\\", "/"));
}

function openPrs() {
  if (process.env.ALLOW_GH_PR_LIST !== "1") return [];
  const output = safeExec("gh", [
    "pr",
    "list",
    "--repo",
    "omgitsguppey/kandylandv2",
    "--state",
    "open",
    "--limit",
    "100",
    "--json",
    "number,title,url,mergeStateStatus",
  ]);
  if (!output) return [];
  try {
    return JSON.parse(output) as FinalPrSummary[];
  } catch {
    return [];
  }
}

function read(relativePath: string) {
  return existsSync(join(ROOT, relativePath)) ? readFileSync(join(ROOT, relativePath), "utf8") : "";
}

function releaseNotesUpdated() {
  const publicNotes = read("public/kandydrops-release-notes.json");
  const changelog = read("CHANGELOG.md");
  return releaseBullets.every((bullet) => publicNotes.includes(bullet) && changelog.includes(bullet));
}

function isReleaseFile(file: string) {
  return [
    "CHANGELOG.md",
    "public/kandydrops-release-notes.json",
    "src/lib/release-notes/public-release-notes.ts",
    "src/lib/release-notes/release-version-contract.ts",
  ].includes(file);
}

function classifyDirtyFile(file: string): { classification: DirtyFileClassification; reason: string } {
  if (file === ARTIFACT || file === DOC) {
    return { classification: "current_generated_artifact_to_commit", reason: "Final PR stale cleanup report is generated by this pass." };
  }
  if (file === "scripts/agent/validate-final-pr-stale-cleanup.ts" || file === "tests/unit/final-pr-stale-cleanup.spec.ts") {
    return { classification: "real_source_change_needs_review", reason: "Final cleanup validator or unit test created by this pass." };
  }
  if (file === "package.json") {
    return { classification: "real_source_change_needs_review", reason: "Package script added for check:final-pr-stale-cleanup." };
  }
  if (file === "src/lib/server/admin-analytics-historical-engagement.ts") {
    return { classification: "real_source_change_needs_review", reason: "Scoped PR #275 admin analytics optimization integrated directly." };
  }
  if (file === "src/components/ui/Button.tsx") {
    return { classification: "real_source_change_needs_review", reason: "Scoped PR #276 accessibility fix integrated directly without .Jules artifact." };
  }
  if (isReleaseFile(file)) {
    return { classification: "release_artifact_expected", reason: "Same-commit public beta release note artifact." };
  }
  if (file.startsWith("agent/state/") || file.startsWith("docs/agent-truth/")) {
    return { classification: "current_generated_artifact_to_commit", reason: "Focused validator refreshed current generated evidence." };
  }
  if (file.startsWith("agent/context/")) {
    return { classification: "unrelated_agent_context_file_to_ignore", reason: "Agent context output should be restored before staging unless explicitly owned." };
  }
  return { classification: "unsafe_unknown", reason: "File is not in the final PR stale cleanup allowed scope." };
}

function classifyOpenPr(pr: FinalPrSummary): FinalPrSummary {
  if (pr.number === 274) {
    return { ...pr, classification: "must_close_superseded_broad_governance_doctrine" };
  }
  if (pr.number === 275) {
    return { ...pr, classification: "must_integrate_or_close_scoped_admin_analytics_optimization" };
  }
  if (pr.number === 276) {
    return { ...pr, classification: "must_integrate_or_close_scoped_button_accessibility_fix" };
  }
  return { ...pr, classification: pr.classification ?? "" };
}

export function buildFinalPrStaleCleanupReport(inputs: FinalPrStaleCleanupInputs): FinalPrStaleCleanupReport {
  const dirtyFiles = Array.from(new Set([...inputs.changedFiles, ...inputs.untrackedFiles])).map((file) => file.replaceAll("\\", "/"));
  const dirtyFileClassifications = dirtyFiles.map((file) => {
    const result = classifyDirtyFile(file);
    return { file, ...result };
  });
  const staleArtifactFindings = dirtyFileClassifications.filter((entry) =>
    entry.classification === "stale_generated_artifact_to_regenerate"
    || entry.classification === "stale_generated_artifact_to_revert_or_delete"
  );
  const openPrsWithClassification = inputs.openPrs.map(classifyOpenPr);
  const prsUnclassified = openPrsWithClassification.filter((pr) => !pr.classification).length;
  const dirtyFilesUnclassified = dirtyFileClassifications.filter((entry) => entry.classification === "unsafe_unknown").length;
  const staleGeneratedArtifactsUnclassified = staleArtifactFindings.filter((entry) => !entry.reason).length;
  const p0Count = [
    prsUnclassified > 0,
    dirtyFilesUnclassified > 0,
    staleGeneratedArtifactsUnclassified > 0,
    !inputs.releaseNotesUpdated,
  ].filter(Boolean).length;
  const p1Count = openPrsWithClassification.filter((pr) => pr.number === 274 || pr.number === 275).length;

  return {
    generatedAtUtc: inputs.generatedAtUtc,
    reportKey: "final-pr-stale-cleanup",
    currentHead: inputs.currentHead,
    summary: {
      openPrCount: openPrsWithClassification.length,
      prsHandled: inputs.prCleanupActions.length,
      prsIntegrated: inputs.prCleanupActions.filter((action) => action.action === "integrated_and_closed").length,
      prsClosedSuperseded: inputs.prCleanupActions.filter((action) => action.action === "closed_superseded").length,
      prsPreserved: inputs.prCleanupActions.filter((action) => action.action === "preserved_with_reason").length,
      prsUnclassified,
      dirtyFilesClassified: dirtyFileClassifications.length - dirtyFilesUnclassified,
      dirtyFilesUnclassified,
      staleGeneratedArtifacts: staleArtifactFindings.length,
      staleGeneratedArtifactsUnclassified,
      releaseNotesSameCommit: inputs.releaseNotesUpdated,
      p0Count,
      p1Count,
      p2Count: staleArtifactFindings.length,
    },
    openPrs: openPrsWithClassification,
    prCleanupActions: inputs.prCleanupActions,
    dirtyFileClassifications,
    staleArtifactFindings,
    fixesApplied: [
      "Integrated PR #275 admin analytics traversal reduction directly into current main.",
      "Integrated PR #276 Button loading spinner aria-hidden fix directly without .Jules artifact.",
      "Closed PR #274 as superseded broad governance doctrine.",
    ],
    releaseNote: {
      title: "Bug fixes and general improvements",
      bullets: releaseBullets,
    },
    nextExactSteps: [
      "Keep open PR count at zero for stale bot cleanup lanes.",
      "Do not re-open broad monolith doctrine unless a current owner-scoped decomposition pass needs it.",
      "Run npm run check:final-pr-stale-cleanup after any new preserved PR cleanup.",
    ],
  };
}

export function validateFinalPrStaleCleanupReport(report: FinalPrStaleCleanupReport) {
  const failures: string[] = [];
  if (report.reportKey !== "final-pr-stale-cleanup") failures.push("reportKey must be final-pr-stale-cleanup.");
  if (!report.currentHead) failures.push("currentHead is required.");
  if (report.summary.prsUnclassified > 0) failures.push("open PRs exist without classification.");
  if (report.openPrs.some((pr) => (pr.number === 274 || pr.number === 275) && !/preserved|exact_reason/iu.test(pr.classification ?? ""))) {
    failures.push("PR #274 or #275 remains open without exact reason.");
  }
  if (report.summary.dirtyFilesUnclassified > 0) failures.push("working tree dirty files are unclassified.");
  if (report.summary.staleGeneratedArtifactsUnclassified > 0) failures.push("stale generated artifacts are unclassified.");
  if (!report.summary.releaseNotesSameCommit) failures.push("release notes separated from real commit.");
  if ((report.nextExactSteps?.length ?? 0) === 0) failures.push("nextExactSteps missing.");
  return failures;
}

function renderDoc(report: FinalPrStaleCleanupReport) {
  const prRows = report.prCleanupActions
    .map((action) => `| #${action.number} | ${action.action} | ${action.reason} |`)
    .join("\n") || "| none | none | no open PRs |";
  const dirtyRows = report.dirtyFileClassifications
    .map((entry) => `| ${entry.file} | ${entry.classification} | ${entry.reason} |`)
    .join("\n") || "| none | clean | no dirty files |";

  return `# Final PR Stale Cleanup

Generated: ${report.generatedAtUtc}

Latest code version: ${report.currentHead}

## Summary

- Open PR count: ${report.summary.openPrCount}
- PRs handled: ${report.summary.prsHandled}
- Integrated and closed: ${report.summary.prsIntegrated}
- Closed superseded: ${report.summary.prsClosedSuperseded}
- Dirty files unclassified: ${report.summary.dirtyFilesUnclassified}
- Stale generated artifacts: ${report.summary.staleGeneratedArtifacts}
- Release notes same commit: ${report.summary.releaseNotesSameCommit}
- Findings: P0=${report.summary.p0Count}, P1=${report.summary.p1Count}, P2=${report.summary.p2Count}

## PR Cleanup Actions

| PR | Action | Reason |
| --- | --- | --- |
${prRows}

## Dirty File Classifications

| File | Classification | Reason |
| --- | --- | --- |
${dirtyRows}

## Fixes Applied

${report.fixesApplied.map((fix) => `- ${fix}`).join("\n")}

## Release Note

- ${report.releaseNote.bullets.join("\n- ")}

## Next Exact Steps

${report.nextExactSteps.map((step) => `- ${step}`).join("\n")}
`;
}

function main() {
  const report = buildFinalPrStaleCleanupReport({
    generatedAtUtc: new Date().toISOString(),
    currentHead: currentHead(),
    openPrs: openPrs(),
    changedFiles: changedFiles(),
    untrackedFiles: untrackedFiles(),
    prCleanupActions: [
      {
        number: 275,
        title: "Reduce duplicate computation in high-ROI aggregation hotspot",
        action: "integrated_and_closed",
        reason: "Scoped admin analytics optimization was applied directly; PR closed to prevent duplicate preserved work.",
      },
      {
        number: 276,
        title: "Palette: Add aria-hidden to Button loading spinner",
        action: "integrated_and_closed",
        reason: "Button.tsx accessibility fix was applied directly; .Jules workflow artifact was intentionally not merged.",
      },
      {
        number: 274,
        title: "Reduce monolith file risk and clarify responsibility boundaries",
        action: "closed_superseded",
        reason: "Broad monolith governance doc was superseded by newer admin analytics, telemetry, mobile UI, and overnight integration locks.",
      },
    ],
    releaseNotesUpdated: releaseNotesUpdated(),
  });

  mkdirSync(join(ROOT, "agent/state"), { recursive: true });
  mkdirSync(join(ROOT, "docs/agent-truth"), { recursive: true });
  writeFileSync(join(ROOT, ARTIFACT), `${JSON.stringify(report, null, 2)}\n`);
  writeFileSync(join(ROOT, DOC), renderDoc(report));

  const failures = validateFinalPrStaleCleanupReport(report);
  if (failures.length > 0) {
    console.error("Final PR stale cleanup validation failed:");
    for (const failure of failures) console.error(`- ${failure}`);
    process.exit(1);
  }

  console.log(`[final-pr-stale-cleanup] ok: openPRs=${report.summary.openPrCount} handled=${report.summary.prsHandled} p0=${report.summary.p0Count}`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main();
}
