import type { AdminAnalyticsPanelRegistryEntry } from "./panel-hydration-contract";

type PanelSeed = Omit<AdminAnalyticsPanelRegistryEntry, "fallbackDisplayState" | "privacyRedactionRule" | "provenZeroRequiredForZero" | "scoreImpact" | "costClass"> & {
  scoreImpact?: AdminAnalyticsPanelRegistryEntry["scoreImpact"];
  costClass?: AdminAnalyticsPanelRegistryEntry["costClass"];
};

const SAFE_SUMMARY_REDACTION =
  "safe summary only: no raw PII, provider IDs, private chat content, private media URLs, push tokens, storage paths, or access tokens";

function panel(seed: PanelSeed): AdminAnalyticsPanelRegistryEntry {
  return {
    fallbackDisplayState: seed.sourceType === "external_required" ? "show_external_required" : "show_collecting",
    privacyRedactionRule: SAFE_SUMMARY_REDACTION,
    provenZeroRequiredForZero: true,
    scoreImpact: seed.scoreImpact ?? { evidenceCompleteness: 1, freshness: 1 },
    costClass: seed.costClass ?? "summary_first",
    ...seed,
  };
}

export const ADMIN_ANALYTICS_PANEL_HYDRATION_REGISTRY: AdminAnalyticsPanelRegistryEntry[] = [
  panel({
    panelId: "traffic_overview",
    panelLabel: "Traffic overview",
    panelGroup: "traffic",
    sourceType: "admin_summary",
    expectedSource: "admin analytics historical snapshot totals",
    expectedEvents: ["page_viewed", "semantic_page_viewed"],
    personMetricIds: ["visits", "page_views"],
    expectedRecentWindow: "24h",
    sourcePath: "src/app/api/admin/analytics/historical/route.ts",
    materializerPath: "analytics_admin_metric_snapshots",
    debugLane: "admin_analytics_overview",
    expectedDaily: true,
  }),
  panel({
    panelId: "active_users",
    panelLabel: "Active users",
    panelGroup: "users",
    sourceType: "admin_summary",
    expectedSource: "snapshot-first realtime active users",
    expectedEvents: ["session_activity_tick", "auth_session_established"],
    personMetricIds: ["sessions"],
    expectedRecentWindow: "1h",
    sourcePath: "src/app/api/admin/analytics/realtime/route.ts",
    materializerPath: "analytics_admin_metric_snapshots:realtime",
    debugLane: "runtime_debug_evidence",
    scoreImpact: { runtimeHealth: 1, freshness: 1 },
    expectedDaily: true,
  }),
  panel({
    panelId: "new_users_signups",
    panelLabel: "New users/signups",
    panelGroup: "auth",
    sourceType: "person_metric",
    expectedSource: "auth runtime event facts and person metrics",
    expectedEvents: ["auth_sign_up_success", "auth_email_signup_completed"],
    personMetricIds: ["auth_runtime_events"],
    expectedRecentWindow: "24h",
    sourcePath: "src/lib/auth/auth-telemetry-contract.ts",
    materializerPath: "person_metrics.auth_runtime_events",
    debugLane: "auth_runtime",
    scoreImpact: { runtimeHealth: 1, evidenceCompleteness: 1 },
    expectedDaily: true,
  }),
  panel({
    panelId: "returning_users",
    panelLabel: "Returning users",
    panelGroup: "users",
    sourceType: "person_metric",
    expectedSource: "sessions and active-days person metrics",
    expectedEvents: ["auth_session_restored", "session_started"],
    personMetricIds: ["sessions", "active_days"],
    expectedRecentWindow: "24h",
    sourcePath: "src/lib/analytics/person-metrics-contract.ts",
    materializerPath: "person_metrics.sessions",
    debugLane: "person_metrics_hydration",
    expectedDaily: true,
  }),
  panel({
    panelId: "guest_to_user_handoff",
    panelLabel: "Guest-to-user handoff",
    panelGroup: "users",
    sourceType: "global_metric",
    expectedSource: "identity handoff and global-user dedupe summaries",
    expectedEvents: ["auth_session_established", "auth_sign_up_success"],
    personMetricIds: ["sessions", "auth_runtime_events"],
    expectedRecentWindow: "24h",
    sourcePath: "src/lib/analytics/identity-handoff-engine.ts",
    materializerPath: "person_metrics.sessions",
    debugLane: "identity_handoff",
    expectedDaily: true,
  }),
  panel({
    panelId: "creator_count",
    panelLabel: "Creator count",
    panelGroup: "creators",
    sourceType: "admin_summary",
    expectedSource: "admin creator/user truth summary",
    expectedEvents: ["creator_dashboard_viewed", "creator_settings_updated"],
    personMetricIds: ["settings_actions"],
    expectedRecentWindow: "7d",
    sourcePath: "src/lib/admin/user-management-contract.ts",
    materializerPath: "admin_user_truth_snapshot",
    debugLane: "user_management",
    expectedDaily: false,
  }),
  panel({
    panelId: "creator_profile_views",
    panelLabel: "Creator profile views",
    panelGroup: "creators",
    sourceType: "person_metric",
    expectedSource: "creator profile event facts",
    expectedEvents: ["creator_profile_viewed"],
    personMetricIds: ["creator_profile_views"],
    expectedRecentWindow: "24h",
    sourcePath: "src/lib/analytics/person-metrics-contract.ts",
    materializerPath: "person_metrics.creator_profile_views",
    debugLane: "person_metrics_hydration",
    expectedDaily: true,
  }),
  panel({
    panelId: "creator_follows",
    panelLabel: "Creator follows",
    panelGroup: "creators",
    sourceType: "person_metric",
    expectedSource: "creator relationship event facts",
    expectedEvents: ["creator_followed", "creator_follow_succeeded"],
    personMetricIds: ["follows"],
    expectedRecentWindow: "7d",
    sourcePath: "src/lib/discovery/creator-relationship-telemetry.ts",
    materializerPath: "person_metrics.follows",
    debugLane: "creator_relationships",
    expectedDaily: false,
  }),
  panel({
    panelId: "drops_live",
    panelLabel: "Drops live",
    panelGroup: "drops",
    sourceType: "admin_summary",
    expectedSource: "admin drop inventory summary",
    expectedEvents: ["admin_creator_drop_reviewed", "creator_drop_submitted"],
    personMetricIds: ["creator_drop_manager_actions"],
    expectedRecentWindow: "7d",
    sourcePath: "src/app/api/admin/overview/route.ts",
    materializerPath: "admin_overview.platformPulse",
    debugLane: "admin_overview",
    expectedDaily: false,
  }),
  panel({
    panelId: "drop_opens",
    panelLabel: "Drop opens",
    panelGroup: "drops",
    sourceType: "person_metric",
    expectedSource: "drop open event facts",
    expectedEvents: ["drop_preview_opened", "drop_preview_page_viewed"],
    personMetricIds: ["drop_opens"],
    expectedRecentWindow: "24h",
    sourcePath: "src/lib/analytics/person-metrics-contract.ts",
    materializerPath: "person_metrics.drop_opens",
    debugLane: "person_metrics_hydration",
    expectedDaily: true,
  }),
  panel({
    panelId: "unlocks",
    panelLabel: "Unlocks",
    panelGroup: "unlocks",
    sourceType: "ledger_summary",
    expectedSource: "server unlock entitlement facts",
    expectedEvents: ["drop_unlocked", "unlock_drop_success", "entitlement_granted"],
    personMetricIds: ["drop_unlocks"],
    expectedRecentWindow: "7d",
    sourcePath: "src/app/api/drops/unlock/route.ts",
    materializerPath: "person_metrics.drop_unlocks",
    debugLane: "drop_watch_time",
    scoreImpact: { runtimeHealth: 1, evidenceCompleteness: 2 },
    expectedDaily: false,
  }),
  panel({
    panelId: "unwraps",
    panelLabel: "Unwraps",
    panelGroup: "unlocks",
    sourceType: "event_fact",
    expectedSource: "payload reveal or consumed drop facts",
    expectedEvents: ["drop_unwrapped", "creator_drop_unwrapped"],
    personMetricIds: ["unwraps"],
    expectedRecentWindow: "7d",
    sourcePath: "src/lib/analytics/person-metrics-contract.ts",
    materializerPath: "person_metrics.unwraps",
    debugLane: "drop_watch_time",
    scoreImpact: { runtimeHealth: 1, evidenceCompleteness: 2 },
    expectedDaily: false,
  }),
  panel({
    panelId: "watch_time",
    panelLabel: "Watch time",
    panelGroup: "watch",
    sourceType: "journey_summary",
    expectedSource: "runtime watch sessions and watch capture summaries",
    expectedEvents: ["watch_session_started", "watch_session_progress", "watch_session_ended"],
    personMetricIds: ["runtime_watch_sessions"],
    expectedRecentWindow: "7d",
    sourcePath: "src/lib/analytics/drop-watch-time-contract.ts",
    materializerPath: "person_metrics.runtime_watch_sessions",
    debugLane: "drop_watch_time",
    scoreImpact: { runtimeHealth: 2, evidenceCompleteness: 1 },
    expectedDaily: false,
  }),
  panel({
    panelId: "completion_rate",
    panelLabel: "Completion rate",
    panelGroup: "watch",
    sourceType: "journey_summary",
    expectedSource: "normalized watch completion summaries",
    expectedEvents: ["drop_watch_completed", "watch_session_ended"],
    personMetricIds: ["runtime_watch_sessions"],
    expectedRecentWindow: "7d",
    sourcePath: "src/lib/math/drop-watch-unlock-math.ts",
    materializerPath: "person_metrics.runtime_watch_sessions",
    debugLane: "drop_watch_time",
    scoreImpact: { runtimeHealth: 2 },
    expectedDaily: false,
  }),
  panel({
    panelId: "wallet_opens",
    panelLabel: "Wallet opens",
    panelGroup: "wallet",
    sourceType: "person_metric",
    expectedSource: "wallet UI event facts",
    expectedEvents: ["wallet_opened"],
    personMetricIds: ["wallet_opens"],
    expectedRecentWindow: "24h",
    sourcePath: "src/lib/analytics/person-metrics-contract.ts",
    materializerPath: "person_metrics.wallet_opens",
    debugLane: "wallet_funnel",
    expectedDaily: true,
  }),
  panel({
    panelId: "package_selections",
    panelLabel: "Package selections",
    panelGroup: "wallet",
    sourceType: "person_metric",
    expectedSource: "wallet package selector event facts",
    expectedEvents: ["purchase_package_selected"],
    personMetricIds: ["package_selections"],
    expectedRecentWindow: "7d",
    sourcePath: "src/lib/analytics/person-metrics-contract.ts",
    materializerPath: "person_metrics.package_selections",
    debugLane: "wallet_funnel",
    expectedDaily: false,
  }),
  panel({
    panelId: "checkout_starts",
    panelLabel: "Checkout starts",
    panelGroup: "payments",
    sourceType: "person_metric",
    expectedSource: "checkout intent telemetry",
    expectedEvents: ["begin_checkout"],
    personMetricIds: ["checkout_starts"],
    expectedRecentWindow: "7d",
    sourcePath: "src/lib/analytics/person-metrics-contract.ts",
    materializerPath: "person_metrics.checkout_starts",
    debugLane: "wallet_funnel",
    expectedDaily: false,
  }),
  panel({
    panelId: "payment_approvals",
    panelLabel: "Payment approvals",
    panelGroup: "payments",
    sourceType: "external_required",
    expectedSource: "server purchase verification plus external provider proof",
    expectedEvents: ["server_purchase_verified", "paypal_capture_completed", "gumdrops_purchase_completed"],
    personMetricIds: ["payment_approvals"],
    expectedRecentWindow: "7d",
    sourcePath: "src/lib/analytics/person-metrics-contract.ts",
    materializerPath: "person_metrics.payment_approvals",
    debugLane: "wallet_funnel",
    costClass: "external_review",
    scoreImpact: { runtimeHealth: 1, evidenceCompleteness: 2 },
    expectedDaily: false,
  }),
  panel({
    panelId: "payment_failures",
    panelLabel: "Payment failures",
    panelGroup: "payments",
    sourceType: "external_required",
    expectedSource: "payment failure event facts plus provider proof when needed",
    expectedEvents: ["gumdrops_purchase_failed", "paypal_capture_failed", "payment_failed"],
    personMetricIds: ["payment_failures"],
    expectedRecentWindow: "7d",
    sourcePath: "src/lib/analytics/person-metrics-contract.ts",
    materializerPath: "person_metrics.payment_failures",
    debugLane: "wallet_funnel",
    costClass: "external_review",
    expectedDaily: false,
  }),
  panel({
    panelId: "gumdrop_balances",
    panelLabel: "GumDrop balances",
    panelGroup: "gumdrops",
    sourceType: "ledger_summary",
    expectedSource: "source-of-funds wallet ledger summary",
    expectedEvents: ["daily_task_reward_granted", "server_purchase_verified"],
    personMetricIds: ["payment_approvals", "daily_task_rewards_granted"],
    expectedRecentWindow: "24h",
    sourcePath: "src/lib/math/gumdrop-ledger-math.ts",
    materializerPath: "wallet_source_ledger",
    debugLane: "daily_task_reward_ledger",
    scoreImpact: { evidenceCompleteness: 1 },
    expectedDaily: true,
  }),
  panel({
    panelId: "reward_gd_grants",
    panelLabel: "Reward GD grants",
    panelGroup: "gumdrops",
    sourceType: "ledger_summary",
    expectedSource: "daily task reward ledger",
    expectedEvents: ["daily_task_reward_granted"],
    personMetricIds: ["daily_task_rewards_granted"],
    expectedRecentWindow: "24h",
    sourcePath: "src/lib/tasks/daily-task-reward-ledger.ts",
    materializerPath: "person_metrics.daily_task_rewards_granted",
    debugLane: "daily_task_reward_ledger",
    expectedDaily: true,
  }),
  panel({
    panelId: "task_starts",
    panelLabel: "Task starts",
    panelGroup: "tasks",
    sourceType: "person_metric",
    expectedSource: "daily task lifecycle event facts",
    expectedEvents: ["daily_task_started"],
    personMetricIds: ["daily_task_starts"],
    expectedRecentWindow: "24h",
    sourcePath: "src/lib/tasks/daily-task-telemetry.ts",
    materializerPath: "person_metrics.daily_task_starts",
    debugLane: "daily_task_lifecycle",
    expectedDaily: true,
  }),
  panel({
    panelId: "task_completions",
    panelLabel: "Task completions",
    panelGroup: "tasks",
    sourceType: "person_metric",
    expectedSource: "daily task completion facts",
    expectedEvents: ["daily_task_completed", "task_completed", "daily_checkin_claimed"],
    personMetricIds: ["daily_task_completions"],
    expectedRecentWindow: "24h",
    sourcePath: "src/lib/tasks/daily-task-telemetry.ts",
    materializerPath: "person_metrics.daily_task_completions",
    debugLane: "daily_task_lifecycle",
    expectedDaily: true,
  }),
  panel({
    panelId: "task_rewards",
    panelLabel: "Task rewards",
    panelGroup: "tasks",
    sourceType: "ledger_summary",
    expectedSource: "server reward truth and reward receipt events",
    expectedEvents: ["daily_task_reward_granted", "daily_task_claimed"],
    personMetricIds: ["daily_task_rewards_granted"],
    expectedRecentWindow: "24h",
    sourcePath: "src/lib/tasks/daily-task-reward-ledger.ts",
    materializerPath: "person_metrics.daily_task_rewards_granted",
    debugLane: "daily_task_reward_ledger",
    expectedDaily: true,
  }),
  panel({
    panelId: "chat_opens",
    panelLabel: "Chat opens",
    panelGroup: "chat",
    sourceType: "person_metric",
    expectedSource: "chat open/thread event facts",
    expectedEvents: ["chat_surface_viewed", "chat_thread_opened"],
    personMetricIds: ["chat_actions"],
    expectedRecentWindow: "24h",
    sourcePath: "src/lib/chat/chat-telemetry-contract.ts",
    materializerPath: "person_metrics.chat_actions",
    debugLane: "chat_telemetry_admin_truth",
    expectedDaily: true,
  }),
  panel({
    panelId: "chat_messages",
    panelLabel: "Chat messages",
    panelGroup: "chat",
    sourceType: "person_metric",
    expectedSource: "redacted chat message event facts",
    expectedEvents: ["chat_message_send_attempted", "chat_message_sent"],
    personMetricIds: ["chat_actions"],
    expectedRecentWindow: "24h",
    sourcePath: "src/lib/chat/chat-telemetry-contract.ts",
    materializerPath: "person_metrics.chat_actions",
    debugLane: "chat_telemetry_admin_truth",
    expectedDaily: true,
  }),
  panel({
    panelId: "chat_blocks_errors",
    panelLabel: "Chat blocks/errors",
    panelGroup: "chat",
    sourceType: "debug_runtime_evidence",
    expectedSource: "chat moderation/block/error summaries without raw transcripts",
    expectedEvents: ["chat_message_blocked", "chat_message_failed", "chat_moderation_blocked"],
    personMetricIds: ["chat_actions"],
    expectedRecentWindow: "7d",
    sourcePath: "src/lib/chat/chat-gating-contract.ts",
    materializerPath: "person_metrics.chat_actions",
    debugLane: "chat_gating_moderation",
    expectedDaily: false,
  }),
  panel({
    panelId: "notification_prompts",
    panelLabel: "Notification prompts",
    panelGroup: "notifications",
    sourceType: "person_metric",
    expectedSource: "notification permission lifecycle summaries",
    expectedEvents: ["notification_prompt_banner_viewed", "notification_prompt_viewed"],
    personMetricIds: ["notification_interactions"],
    expectedRecentWindow: "24h",
    sourcePath: "src/lib/notifications/notification-permission-contract.ts",
    materializerPath: "person_metrics.notification_interactions",
    debugLane: "notification_permission",
    expectedDaily: true,
  }),
  panel({
    panelId: "notification_tokens",
    panelLabel: "Notification tokens",
    panelGroup: "notifications",
    sourceType: "debug_runtime_evidence",
    expectedSource: "push token summary with tokens redacted",
    expectedEvents: ["push_token_registered", "push_token_registration_failed"],
    personMetricIds: ["notification_interactions"],
    expectedRecentWindow: "7d",
    sourcePath: "src/lib/notifications/push-token-contract.ts",
    materializerPath: "person_metrics.notification_interactions",
    debugLane: "push_token_health",
    expectedDaily: false,
  }),
  panel({
    panelId: "notification_intents",
    panelLabel: "Notification intents",
    panelGroup: "notifications",
    sourceType: "debug_runtime_evidence",
    expectedSource: "notification intent evaluation summaries",
    expectedEvents: ["notification_intent_evaluated", "notification_targeting_blocked"],
    personMetricIds: ["notification_interactions"],
    expectedRecentWindow: "7d",
    sourcePath: "src/lib/notifications/notification-intent-contract.ts",
    materializerPath: "person_metrics.notification_interactions",
    debugLane: "notification_targeting",
    expectedDaily: false,
  }),
  panel({
    panelId: "auth_attempts_failures",
    panelLabel: "Auth attempts/failures",
    panelGroup: "auth",
    sourceType: "person_metric",
    expectedSource: "auth runtime telemetry summaries",
    expectedEvents: ["auth_sign_in_attempted", "auth_sign_in_failed", "auth_sign_up_failed"],
    personMetricIds: ["auth_runtime_events"],
    expectedRecentWindow: "24h",
    sourcePath: "src/lib/auth/auth-telemetry-contract.ts",
    materializerPath: "person_metrics.auth_runtime_events",
    debugLane: "auth_runtime",
    expectedDaily: true,
  }),
  panel({
    panelId: "session_restores",
    panelLabel: "Session restores",
    panelGroup: "auth",
    sourceType: "person_metric",
    expectedSource: "auth persistence/session restore summaries",
    expectedEvents: ["auth_session_restored", "auth_session_established"],
    personMetricIds: ["auth_runtime_events", "sessions"],
    expectedRecentWindow: "24h",
    sourcePath: "src/lib/auth/auth-session-stability.ts",
    materializerPath: "person_metrics.auth_runtime_events",
    debugLane: "auth_persistence",
    expectedDaily: true,
  }),
  panel({
    panelId: "media_uploads_access_blocks",
    panelLabel: "Media uploads/access blocks",
    panelGroup: "media",
    sourceType: "debug_runtime_evidence",
    expectedSource: "media upload/access summaries without private URLs",
    expectedEvents: ["media_upload_prepare_completed", "media_access_blocked", "media_access_failed"],
    personMetricIds: ["chat_actions"],
    expectedRecentWindow: "7d",
    sourcePath: "src/lib/media/media-upload-contract.ts",
    materializerPath: "person_metrics.chat_actions",
    debugLane: "runtime_debug_evidence",
    expectedDaily: false,
  }),
  panel({
    panelId: "search_queries",
    panelLabel: "Search queries",
    panelGroup: "search",
    sourceType: "person_metric",
    expectedSource: "redacted search/discovery event facts",
    expectedEvents: ["search_submitted", "search_query_submitted", "drops_searched"],
    personMetricIds: ["search_discovery_actions"],
    expectedRecentWindow: "24h",
    sourcePath: "src/lib/analytics/person-metrics-contract.ts",
    materializerPath: "person_metrics.search_discovery_actions",
    debugLane: "person_metrics_hydration",
    expectedDaily: true,
  }),
  panel({
    panelId: "search_zero_results_clicks",
    panelLabel: "Search zero results/clicks",
    panelGroup: "search",
    sourceType: "person_metric",
    expectedSource: "redacted search result outcome facts",
    expectedEvents: ["search_zero_results", "search_result_clicked"],
    personMetricIds: ["search_discovery_actions"],
    expectedRecentWindow: "7d",
    sourcePath: "src/lib/analytics/person-metrics-contract.ts",
    materializerPath: "person_metrics.search_discovery_actions",
    debugLane: "person_metrics_hydration",
    expectedDaily: false,
  }),
  panel({
    panelId: "support_account_actions",
    panelLabel: "Support/report issue/delete/data export",
    panelGroup: "support",
    sourceType: "person_metric",
    expectedSource: "support and account action telemetry",
    expectedEvents: ["support_ticket_created", "account_delete_request_submitted", "data_export_requested"],
    personMetricIds: ["support_account_actions"],
    expectedRecentWindow: "7d",
    sourcePath: "src/lib/analytics/person-metrics-contract.ts",
    materializerPath: "person_metrics.support_account_actions",
    debugLane: "person_metrics_hydration",
    expectedDaily: false,
  }),
  panel({
    panelId: "error_rate_4xx",
    panelLabel: "Error rate/4xx",
    panelGroup: "errors",
    sourceType: "route_runtime_sample",
    expectedSource: "route runtime health and 4xx rollups",
    expectedEvents: [],
    personMetricIds: [],
    expectedRecentWindow: "1h",
    sourcePath: "src/lib/server/route-runtime-health.ts",
    materializerPath: "route_runtime_health_summary",
    debugLane: "runtime_debug_evidence",
    scoreImpact: { runtimeHealth: 2, costRisk: 1 },
    costClass: "route_sample",
    expectedDaily: true,
  }),
  panel({
    panelId: "cost_risk",
    panelLabel: "Cost risk",
    panelGroup: "cost",
    sourceType: "external_required",
    expectedSource: "cost guard summaries plus external billing review",
    expectedEvents: [],
    personMetricIds: [],
    expectedRecentWindow: "24h",
    sourcePath: "src/lib/math/cost-export-parity-math.ts",
    materializerPath: "cost_guard_summary",
    debugLane: "cost_4xx",
    scoreImpact: { costRisk: 4 },
    costClass: "external_review",
    expectedDaily: true,
  }),
  panel({
    panelId: "journey_funnel",
    panelLabel: "Journey funnel",
    panelGroup: "journeys",
    sourceType: "journey_summary",
    expectedSource: "user journey behavioral intelligence summary",
    expectedEvents: ["auth_modal_opened", "drop_preview_opened", "begin_checkout", "gumdrops_purchase_completed"],
    personMetricIds: ["sessions", "drop_opens", "checkout_starts", "payment_approvals"],
    expectedRecentWindow: "24h",
    sourcePath: "src/lib/admin-analytics-journey-funnel.ts",
    materializerPath: "user_journey_summary",
    debugLane: "user_journey",
    scoreImpact: { evidenceCompleteness: 1, freshness: 1 },
    expectedDaily: true,
  }),
  panel({
    panelId: "realtime_health",
    panelLabel: "Realtime health",
    panelGroup: "realtime",
    sourceType: "route_runtime_sample",
    expectedSource: "snapshot-first realtime route and debug evidence",
    expectedEvents: ["session_activity_tick", "page_viewed"],
    personMetricIds: ["sessions", "page_views"],
    expectedRecentWindow: "1h",
    sourcePath: "src/app/api/admin/analytics/realtime/route.ts",
    materializerPath: "analytics_admin_metric_snapshots:realtime",
    debugLane: "runtime_debug_evidence",
    scoreImpact: { runtimeHealth: 1, freshness: 2 },
    costClass: "route_sample",
    expectedDaily: true,
  }),
  panel({
    panelId: "debug_backlog",
    panelLabel: "Debug backlog",
    panelGroup: "errors",
    sourceType: "debug_runtime_evidence",
    expectedSource: "debug backlog summary",
    expectedEvents: [],
    personMetricIds: [],
    expectedRecentWindow: "24h",
    sourcePath: "src/lib/debug/debug-backlog-builder.ts",
    materializerPath: "debug_backlog_summary",
    debugLane: "open_p1_p2_backlog",
    scoreImpact: { regressionRisk: 1 },
    costClass: "debug_only",
    expectedDaily: true,
  }),
];

export function getAdminAnalyticsPanelRegistryEntry(panelId: string) {
  return ADMIN_ANALYTICS_PANEL_HYDRATION_REGISTRY.find((panel) => panel.panelId === panelId) ?? null;
}
