import { describe, expect, it } from "vitest";

import { buildCreatorOnboardingDiagnostics } from "@/lib/server/creator-onboarding-diagnostics";

describe("creator onboarding diagnostics", () => {
    it("flags missing queue, missing source, missing id metadata, limbo blockers, and role mismatch states", () => {
        const result = buildCreatorOnboardingDiagnostics({
            users: [
                {
                    uid: "projection_only",
                    raw: {
                        creatorApplication: {
                            signupType: "creator",
                            submissionStatus: "awaiting_manual_review",
                            approvalStatus: "creator_pending",
                            queuePosition: 4,
                            onboardingStartedAt: 1,
                            submittedAt: 2,
                            onboardingSubmittedAt: 2,
                            awaitingManualReviewAt: 3,
                            updatedAt: 4,
                            creatorDisplayName: "Projection Only",
                            bypassFanOnboarding: true,
                            legalStatus: "legal_pending",
                            idVerificationStatus: "id_not_requested",
                            segmentationStatus: "segment_unassigned",
                        },
                    },
                },
            ],
            onboardingRecords: [
                {
                    userId: "missing_queue",
                    email: "queue@example.com",
                    role: "user",
                    sourceVersion: 1,
                    signupType: "creator",
                    submissionStatus: "awaiting_manual_review",
                    approvalStatus: "creator_pending",
                    queuePosition: 1,
                    onboardingStartedAt: 1,
                    submittedAt: 2,
                    onboardingSubmittedAt: 2,
                    awaitingManualReviewAt: 3,
                    updatedAt: 4,
                    creatorDisplayName: "Missing Queue",
                    bypassFanOnboarding: true,
                    legalStatus: "legal_pending",
                    idVerificationStatus: "id_not_requested",
                    segmentationStatus: "segment_unassigned",
                    creatorReviewQueueVisible: true,
                    blockingReasons: ["awaiting_legal", "awaiting_id_request", "awaiting_segment_assignment"],
                },
                {
                    userId: "missing_id_metadata",
                    email: "id@example.com",
                    role: "user",
                    sourceVersion: 1,
                    signupType: "creator",
                    submissionStatus: "awaiting_manual_review",
                    approvalStatus: "creator_pending",
                    queuePosition: 2,
                    onboardingStartedAt: 1,
                    submittedAt: 2,
                    onboardingSubmittedAt: 2,
                    awaitingManualReviewAt: 3,
                    updatedAt: 4,
                    creatorDisplayName: "Missing ID Metadata",
                    bypassFanOnboarding: true,
                    legalStatus: "legal_signed",
                    idVerificationStatus: "id_submitted",
                    segmentationStatus: "segment_assigned",
                    creatorReviewQueueVisible: true,
                    blockingReasons: ["awaiting_id_review"],
                },
                {
                    userId: "stuck_no_blockers",
                    email: "stuck@example.com",
                    role: "user",
                    sourceVersion: 1,
                    signupType: "creator",
                    submissionStatus: "awaiting_manual_review",
                    approvalStatus: "creator_pending",
                    queuePosition: 3,
                    onboardingStartedAt: 1,
                    submittedAt: 2,
                    onboardingSubmittedAt: 2,
                    awaitingManualReviewAt: 3,
                    updatedAt: 4,
                    creatorDisplayName: "Stuck No Blockers",
                    bypassFanOnboarding: true,
                    legalStatus: "legal_signed",
                    idVerificationStatus: "id_verified",
                    segmentationStatus: "segment_assigned",
                    creatorReviewQueueVisible: true,
                    blockingReasons: [],
                },
                {
                    userId: "role_mismatch",
                    email: "mismatch@example.com",
                    role: "creator",
                    sourceVersion: 1,
                    signupType: "creator",
                    submissionStatus: "awaiting_manual_review",
                    approvalStatus: "creator_pending",
                    queuePosition: 5,
                    onboardingStartedAt: 1,
                    submittedAt: 2,
                    onboardingSubmittedAt: 2,
                    awaitingManualReviewAt: 3,
                    updatedAt: 4,
                    creatorDisplayName: "Role Mismatch",
                    bypassFanOnboarding: true,
                    legalStatus: "legal_pending",
                    idVerificationStatus: "id_requested",
                    segmentationStatus: "segment_unassigned",
                    creatorReviewQueueVisible: true,
                    blockingReasons: ["awaiting_legal", "awaiting_id_submission", "awaiting_segment_assignment", "role_activation_blocked"],
                },
            ],
            queueRecords: [
                {
                    userId: "missing_id_metadata",
                    creatorDisplayName: "Missing ID Metadata",
                },
                {
                    userId: "stuck_no_blockers",
                    creatorDisplayName: "Stuck No Blockers",
                },
                {
                    userId: "role_mismatch",
                    creatorDisplayName: "Role Mismatch",
                },
                {
                    userId: "queue_without_source",
                    creatorDisplayName: "Queue Without Source",
                },
            ],
        });

        expect(result.summary).toMatchObject({
            totalIssues: 6,
            missingQueueCount: 1,
            missingSourceCount: 1,
            projectionWithoutSourceCount: 1,
            missingIdMetadataCount: 1,
            stuckAwaitingReviewCount: 1,
            roleMismatchCount: 1,
        });
        expect(result.issues.map((issue) => issue.key)).toEqual(expect.arrayContaining([
            "missing_queue_record",
            "missing_source_onboarding",
            "projection_without_source",
            "id_missing_metadata",
            "stuck_without_blockers",
            "role_status_mismatch",
        ]));
    });
});
