import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import {
  isSupportedTelemetryEventNameForRuntime,
  resolveTelemetryEventNameForRuntime,
  TELEMETRY_CANONICAL_EVENT_NAMES,
} from "../../shared/runtime/telemetry-event-manifest";

const repoRoot = process.cwd();

describe("Functions callable telemetry catalog guard", () => {
  it("accepts supported callable telemetry names from the shared catalog-derived manifest", () => {
    expect(TELEMETRY_CANONICAL_EVENT_NAMES.length).toBeGreaterThan(100);
    expect(resolveTelemetryEventNameForRuntime("drop_preview_page_viewed")).toBe("drop_preview_page_viewed");
    expect(isSupportedTelemetryEventNameForRuntime("drop_preview_page_viewed")).toBe(true);
  });

  it("canonicalizes callable telemetry aliases from the shared manifest", () => {
    expect(resolveTelemetryEventNameForRuntime("creator_drop_manager_opened")).toBe("creator_drop_manager_surface_viewed");
    expect(isSupportedTelemetryEventNameForRuntime("creator_drop_manager_opened")).toBe(true);
  });

  it("rejects unsupported callable telemetry names through the shared manifest", () => {
    expect(isSupportedTelemetryEventNameForRuntime("functions_callable_unknown_probe")).toBe(false);
    expect(resolveTelemetryEventNameForRuntime("functions_callable_unknown_probe")).toBeNull();
  });

  it("rejects unsupported callable telemetry names before consent enforcement and fact writes", () => {
    const source = readFileSync(join(repoRoot, "functions/src/analytics-event-facts.ts"), "utf8");
    const guardIndex = source.indexOf("resolveTelemetryEventNameForRuntime(normalizedEvent.eventName)");
    const consentIndex = source.indexOf("enforcePrivacyConsentOnEvent(normalizedEvent)");
    const writeIndex = source.indexOf('db.collection("analytics_event_facts")');

    expect(source).toContain('throw new HttpsError("invalid-argument", "Unsupported telemetry eventName.")');
    expect(guardIndex).toBeGreaterThan(-1);
    expect(consentIndex).toBeGreaterThan(guardIndex);
    expect(writeIndex).toBeGreaterThan(guardIndex);
  });

  it("keeps privacy-denied callable events out of analytics_event_facts writes", () => {
    const source = readFileSync(join(repoRoot, "functions/src/analytics-event-facts.ts"), "utf8");
    const consentIndex = source.indexOf("enforcePrivacyConsentOnEvent(normalizedEvent)");
    const ignoredIndex = source.indexOf('status: "ignored"');
    const writeIndex = source.indexOf('db.collection("analytics_event_facts").doc(eventId)');

    expect(source).toContain('reason: enforcement.reason || "consent_denied"');
    expect(consentIndex).toBeGreaterThan(-1);
    expect(ignoredIndex).toBeGreaterThan(consentIndex);
    expect(writeIndex).toBeGreaterThan(ignoredIndex);
  });

  it("preserves callable duplicate suppression before and after Firestore writes", () => {
    const source = readFileSync(join(repoRoot, "functions/src/analytics-event-facts.ts"), "utf8");
    const uniqueIndex = source.indexOf("const uniqueEvents = new Map<string, unknown>()");
    const dedupedEventsIndex = source.indexOf("const deduplicatedEvents = Array.from(uniqueEvents.values())");
    const writeIndex = source.indexOf('db.collection("analytics_event_facts").doc(eventId)');
    const duplicateReturnIndex = source.indexOf('status: "deduped"');

    expect(source).toContain("!uniqueEvents.has(eId)");
    expect(source).toContain("isFirestoreAlreadyExists(error)");
    expect(uniqueIndex).toBeGreaterThan(-1);
    expect(dedupedEventsIndex).toBeGreaterThan(uniqueIndex);
    expect(writeIndex).toBeGreaterThan(dedupedEventsIndex);
    expect(duplicateReturnIndex).toBeGreaterThan(writeIndex);
  });

  it("keeps the manifest generated from the app telemetry catalog instead of hand-maintained", () => {
    const manifest = readFileSync(join(repoRoot, "shared/runtime/telemetry-event-manifest.ts"), "utf8");

    expect(manifest).toContain("Generated by scripts/agent/build-telemetry-event-manifest.ts");
    expect(manifest).toContain("src/lib/telemetry-catalog.ts + src/lib/analytics/telemetry/surface-telemetry-catalog-events.ts");
    expect(manifest).toContain("Do not edit by hand");
  });
});
