import { describe, expect, it } from "vitest";

import {
  buildScore80ReconciliationLock,
  validateScore80ReconciliationLock,
  type Score80ReconciliationLockReport,
} from "@/lib/agent-score/score-80-reconciliation-lock";

function buildReport() {
  return buildScore80ReconciliationLock({
    generatedAtUtc: "2026-05-21T12:00:00.000Z",
    currentHead: "abc123",
    previousScore: 77.76,
    currentScore: 77.76,
    dimensions: {
      sourceHealth: 100,
      runtimeHealth: 75.5,
      evidenceCompleteness: 63.75,
      freshness: 79.38,
      costRisk: 40,
      regressionRisk: 90,
    },
    readinessStatus: "Visual QA required",
    betaExitCanStart: false,
    aiCritic: {
      criticStatus: "pass",
      p0Count: 0,
      p1Count: 20,
      p2Count: 57,
    },
    runtimeMatrix: {
      manualUiRows: 1,
      formalRuntimeRequiredRows: 10,
      deployedRuntimeSmokeStillRequired: true,
      formalGateImpact: {
        clearsDeployedRuntime: false,
        clearsFormalProvider: false,
        clearsManualVisual: false,
      },
    },
    realUsageConfidence: {
      status: "source_ready_real_usage_confidence_calibrated",
      runtimeHealthCredit: 92,
      formalGateImpact: {
        clearsFormalProvider: false,
        clearsDeployedRuntime: false,
        clearsManualVisual: false,
      },
    },
    refreshQueue: {
      totalEntries: 55,
      automaticEntries: 51,
      blockedEntries: 4,
    },
    refreshSafeguards: {
      staleArtifactsNeedingAction: 18,
    },
    dirtyFiles: [
      {
        path: "agent/state/score-80-reconciliation-lock.generated.json",
        classification: "current_generated_artifact_to_commit",
        reason: "score-80 reconciliation artifact generated by this lock.",
      },
    ],
    openPrs: [
      {
        number: 278,
        title: "Reduce duplicate computation",
        url: "https://github.com/omgitsguppey/kandylandv2/pull/278",
        classification: "deferred_unrelated",
        reason: "Performance PR is outside this reconciliation lock.",
      },
    ],
  });
}

describe("score 80 reconciliation lock", () => {
  it("separates manual-only proof from algorithmic, runtime, provider, and admin proof", () => {
    const report = buildReport();

    expect(report.previousScore).toBe(77.76);
    expect(report.currentScore).toBe(77.76);
    expect(report.distanceTo80).toBe(2.24);
    expect(report.remainingManualOnlyItems).toHaveLength(1);
    expect(report.remainingManualOnlyItems[0]?.proofType).toBe("manual_only");
    expect(report.remainingManualOnlyItems[0]?.requiresManualUI).toBe(true);
    expect(report.remainingAlgorithmicItems.length).toBeGreaterThan(0);
    expect(report.remainingRuntimeRequiredItems.length).toBeGreaterThan(0);
    expect(report.remainingProviderRequiredItems.length).toBeGreaterThan(0);
    expect(report.remainingAdminTruthItems.length).toBeGreaterThan(0);
    expect(validateScore80ReconciliationLock(report)).toEqual([]);
  });

  it("keeps formal gates honest and blocks beta exit review under 80", () => {
    const report = buildReport();

    expect(report.canStartBetaExitReview).toBe(false);
    expect(report.formalGateImpact.clearsDeployedRuntime).toBe(false);
    expect(report.formalGateImpact.clearsFormalProvider).toBe(false);
    expect(report.formalGateImpact.clearsManualVisual).toBe(false);
    expect(report.topNextActions[0]?.rank).toBe(1);
    expect(report.topNextActions[0]?.proofType).toBe("manual_only");
  });

  it("classifies P0/P1/P2 counts from the critic triage without inventing fixes", () => {
    const report = buildReport();

    expect(report.p0Count).toBe(0);
    expect(report.p1Count).toBe(20);
    expect(report.p2Count).toBe(57);
    expect(report.status).toBe("locked_with_formal_gates_remaining");
  });

  it("fails if non-UI algorithmic requirements are mislabeled manual-only", () => {
    const report = buildReport();
    const invalid: Score80ReconciliationLockReport = {
      ...report,
      remainingManualOnlyItems: [
        ...report.remainingManualOnlyItems,
        {
          id: "telemetry_ingest_manual_mislabel",
          label: "Telemetry ingest",
          proofType: "manual_only",
          scoreDimension: "runtimeHealth",
          scoreImpactEstimate: 1.8,
          justification: "Telemetry source lane was mislabeled as manual-only.",
          requiresManualUI: false,
          nextAction: "Run telemetry closure validator.",
        },
      ],
    };

    expect(validateScore80ReconciliationLock(invalid)).toEqual(
      expect.arrayContaining([
        expect.stringContaining("manual-only item telemetry_ingest_manual_mislabel lacks UI/manual justification"),
      ]),
    );
  });

  it("fails if formal gates are falsely cleared, score drops lack a reason, or changed files are unclassified", () => {
    const report = buildReport();
    const invalid: Score80ReconciliationLockReport = {
      ...report,
      currentScore: 76,
      scoreDropReason: "no_drop",
      canStartBetaExitReview: true,
      formalGateImpact: {
        ...report.formalGateImpact,
        clearsDeployedRuntime: true,
      },
      dirtyFiles: [
        {
          path: "mystery.tmp",
          classification: "unsafe_unknown",
          reason: "",
        },
      ],
      openPrs: [
        {
          number: 999,
          title: "unknown",
          url: "https://github.com/omgitsguppey/kandylandv2/pull/999",
          classification: "unsafe_unknown",
          reason: "",
        },
      ],
      topNextActions: [],
    };

    expect(validateScore80ReconciliationLock(invalid)).toEqual(
      expect.arrayContaining([
        expect.stringContaining("must not clear deployed runtime gate"),
        expect.stringContaining("score dropped without an explicit reason"),
        expect.stringContaining("dirty file mystery.tmp is unclassified"),
        expect.stringContaining("open PR #999 is unclassified"),
        expect.stringContaining("ranked next actions are required"),
        expect.stringContaining("cannot start beta exit review"),
      ]),
    );
  });
});
